sass/sass-spec

spec/libsass-closed-issues/issue_803/expected_output.css
spec/libsass-closed-issues/issue_803/input.scss

This PR activates specs for correctly rendered media queries with interpolants (https://github.com/sass/libsass/issues/803).

Activate specs for issue 803

---

spec/libsass-closed-issues/issue_185/hoisting/expected_output.css
spec/libsass-closed-issues/issue_185/hoisting/input.scss

This PR updates the `@media` hoisting specs to cater for interpolants also.

Update the @media hoisting specs to cater for interpolants also

---

spec/libsass-closed-issues/issue_815/expected_output.css
spec/libsass-closed-issues/issue_815/input.scss

This PR activates specs for a regression in `str-slice` when `$end-at` is omitted (https://github.com/sass/libsass/issues/815).

Activate specs for issue 815

---

spec/libsass-closed-issues/issue_817/expected_output.css
spec/libsass-closed-issues/issue_817/input.scss

This PR adds and activates specs for normalising string function arguments to double quotes (https://github.com/sass/libsass/issues/817).

Activate specs for issue 817

---

spec/libsass-todo-issues/issue_820/expected_output.css
spec/libsass-todo-issues/issue_820/input.scss

This PR adds specs for `@charset` not being inserted when utf-8 chars appear in comments before code (https://github.com/sass/libsass/issues/820).

Add specs for issue 820

---

spec/libsass-todo-issues/issue_659/input.scss

test for this issue http://github.com/sass/libsass/issues/659

test for libsass issue 659

---

spec/libsass-closed-issues/issue_828/expected_output.css
spec/libsass-closed-issues/issue_828/input.scss

This PR adds and activates specs for correctly bubbling directives (https://github.com/sass/libsass/issues/829).

Activate specs for correctly bubbling directives

---

spec/libsass-closed-issues/issue_828/expected_output.css
spec/libsass-closed-issues/issue_828/input.scss

This PR adds and activates specs for correctly handling negative values in lists (https://github.com/sass/libsass/issues/828).

Activate specs for correctly handling negative values in lists

---

spec/libsass-closed-issues/issue_646/expected_output.css
spec/libsass-closed-issues/issue_646/input.scss

This PR activates specs for handling comments in function definitions (https://github.com/sass/libsass/issues/646).

Activate specs for handling comments in function definitions

---

spec/libsass-closed-issues/issue_439/expected_output.css
spec/libsass-closed-issues/issue_439/input.scss
spec/libsass-todo-issues/issue_439/expected_output.css
spec/libsass-todo-issues/issue_439/input.scss

This PR updates the spec for https://github.com/sass/libsass/issues/439 to reflect the issue at hand.
The update issue fails as expected, and is hence moved back to todo-issues.

Update and deactivate spec for issue 439

---

spec/libsass-todo-issues/issue_472/expected_output.css
spec/libsass-todo-issues/issue_472/input.scss

This PR adds specs for the correct bubbling behaviour of `@keyframes` (https://github.com/sass/libsass/issues/472).

Add specs for issue 472

---

lib/sass_spec/cli.rb
lib/sass_spec/engine_adapter.rb
lib/sass_spec/runner.rb
lib/sass_spec/test.rb
lib/sass_spec/test_case.rb

I know Ruby Sass is slow, but there's no need to make using it painful. This makes the Sass spec tests run in about 5 seconds on my machine instead of taking more than 4 minutes. This is accomplished by running the sass spec tests in the sass-spec process instead of starting a new ruby process for each test case.
This refactor also makes it easier to support new engines in the future by providing a clean object-oriented interface instead of making assumptions about the CLI that is being invoked.

Speed up the Ruby Sass tests by running them in-process.

---

spec/colors/expected_output.css
spec/colors/input.scss

Included some not-so-edge cases. Expected values checked with ruby sass 3.4 and 3.2. Related to https://github.com/sass/libsass/pull/865
Note the odd behaviour of `saturate()` on grey colours.

Add more saturation/desaturation tests

---

spec/libsass-todo-issues/issue_883/expected_output.css
spec/libsass-todo-issues/issue_883/input.scss

This PR adds spec for the incorrect bubbling of at-rule properties https://github.com/sass/libsass/issues/883.

Add specs for issue 883

---

spec/libsass-todo-issues/issue_873/expected_output.css
spec/libsass-todo-issues/issue_873/input.scss

This PR adds specs for the incorrect parsing of `not` https://github.com/sass/libsass/issues/873.

Add specs for issue 873

---

spec/libsass-closed-issues/issue_877/input.scss

This PR fixes the spec for underscore normalisation https://github.com/sass/libsass/issues/877 so that it's actually testing the desired behaviour.

Fix spec for underscore normalisation

---

spec/libsass-todo-issues/issue_823/expected_output.css
spec/libsass-todo-issues/issue_823/input.scss

This PR adds a spec for a regression in `@extends` https://github.com/sass/libsass/issues/823.

Add spec for issue 823

---

spec/libsass-closed-issues/issue_890/expected_output.css
spec/libsass-closed-issues/issue_890/input.scss

This PR activates specs handling comments in propsets (https://github.com/sass/libsass/issues/890).

Activate specs handling comments in propsets

---

spec/libsass-todo-issues/issue_942/expected.compact.css
spec/libsass-todo-issues/issue_942/expected.compressed.css
spec/libsass-todo-issues/issue_942/expected.expanded.css
spec/libsass-todo-issues/issue_942/expected_output.css
spec/libsass-todo-issues/issue_942/input.scss

https://github.com/sass/libsass/issues/942
Note that there's a big difference between Sass 3.2 and 3.4 behaviour in this case. 3.2 will error on the multi-line string variable, and incorrectly compile the content into `"foo\ bar"`.

Add tests for libsass issue 942

---

spec/libsass-todo-issues/issue_947/expected.compact.css
spec/libsass-todo-issues/issue_947/expected.compressed.css
spec/libsass-todo-issues/issue_947/expected.expanded.css
spec/libsass-todo-issues/issue_947/expected_output.css
spec/libsass-todo-issues/issue_947/input.scss

Add specs for issue 947.

---

spec/libsass/at-error/feature-test/expected.compact.css
spec/libsass/at-error/feature-test/expected.compressed.css
spec/libsass/at-error/feature-test/expected.expanded.css
spec/libsass/at-error/feature-test/expected_output.css
spec/libsass/at-error/feature-test/input.scss

This PR adds specs for the `at-root` feature check.

Activate spec for at-error feature test

---

spec/libsass-closed-issues/issue_1060/input.scss

This PR fixes a broken spec for `@else` introduce (by me) in https://github.com/sass/sass-spec/pull/306.

Fix broken spec for issue 1060

---

Gemfile.lock
spec/libsass-closed-issues/issue_657/default/expected.compact.css
spec/libsass-closed-issues/issue_657/default/expected.compressed.css
spec/libsass-closed-issues/issue_657/default/expected.expanded.css
spec/libsass-closed-issues/issue_657/default/expected_output.css
spec/libsass-closed-issues/issue_657/default/input.scss
spec/libsass-closed-issues/issue_657/limit/expected.compact.css
spec/libsass-closed-issues/issue_657/limit/expected.compressed.css
spec/libsass-closed-issues/issue_657/limit/expected.expanded.css
spec/libsass-closed-issues/issue_657/limit/expected_output.css
spec/libsass-closed-issues/issue_657/limit/input.scss
spec/number-functions/random/expected.compact.css
spec/number-functions/random/expected.compressed.css
spec/number-functions/random/expected.expanded.css
spec/number-functions/random/expected_output.css
spec/number-functions/random/input.scss

This PR fixes specs for the  `random` function, primarily adding an assertion that it is infact somewhat random.
I've also update the Ruby dep to 3.4.13 to fix an issue with Ruby's `random` - http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#3413_26_february_2015

Fix specs for the random function

---

spec/libsass-todo-issues/issue_1098/expected.compact.css
spec/libsass-todo-issues/issue_1098/expected.compressed.css
spec/libsass-todo-issues/issue_1098/expected.expanded.css
spec/libsass-todo-issues/issue_1098/expected_output.css
spec/libsass-todo-issues/issue_1098/input.scss

This PR adds specs for regressions in the IE property hack https://github.com/sass/libsass/issues/1098.

Add specs for issue 1098

---

spec/libsass-todo-issues/issue_1124/input.scss

This PR fixes a typo in the spec for https://github.com/sass/libsass/issues/1124

Fix typo in specs for issue 1124

---

spec/libsass-todo-tests/libsass/compact/expected.compact.css
spec/libsass-todo-tests/libsass/compact/expected.compressed.css
spec/libsass-todo-tests/libsass/compact/expected.expanded.css
spec/libsass-todo-tests/libsass/compact/expected_output.css
spec/libsass-todo-tests/libsass/compact/input.scss
spec/libsass-todo-tests/libsass/eq/expected.compact.css
spec/libsass-todo-tests/libsass/eq/expected.compressed.css
spec/libsass-todo-tests/libsass/eq/expected.expanded.css
spec/libsass-todo-tests/libsass/eq/expected_output.css
spec/libsass-todo-tests/libsass/eq/input.scss

This PR removes or updates specs that incorrect reference the non-standard `compact` function.

Remove invalid specs for non-standard compact function

---

spec/libsass/length/input.scss

This PR fixes a spec that causes the Ruby Sass process to crash due to weird UTF-8 characters.
Originally mentioned in https://github.com/sass/sass-spec/issues/361.

Fix weird UTF-8 characters in the length spec

---

lib/sass_spec/test.rb

This PR fixes a big with sass-spec which causes it to falsely report todo specs as passing. This has resulted in some recent Libsass regressions, and incorrectly closed bugs.
/cc @mgreter

Respect the --ignore-todo flag

---

lib/sass_spec/test.rb

This PR fix a method missing exception for the undefined `asset_not_equal` when using the `--unexpected-pass` flag.

Fix method missing exception

---

spec/libsass-todo-issues/issue_1219/expected.compact.css
spec/libsass-todo-issues/issue_1219/expected.compressed.css
spec/libsass-todo-issues/issue_1219/expected.expanded.css
spec/libsass-todo-issues/issue_1219/expected_output.css
spec/libsass-todo-issues/issue_1219/input.scss

Reverts sass/sass-spec#410
https://github.com/sass/libsass/issues/1219 is testing an error condition, as such this spec should not pass by design.

Revert "Add missing todo spec tests for issue 1219"

---

spec/libsass-todo-tests/libsass/parent-selector/basic/expected.compact.css
spec/libsass-todo-tests/libsass/parent-selector/basic/expected.compressed.css
spec/libsass-todo-tests/libsass/parent-selector/basic/expected.expanded.css
spec/libsass-todo-tests/libsass/parent-selector/basic/expected_output.css
spec/libsass-todo-tests/libsass/parent-selector/basic/input.scss
spec/libsass-todo-tests/libsass/parent-selector/inner-combinator/expected.compact.css
spec/libsass-todo-tests/libsass/parent-selector/inner-combinator/expected.compressed.css
spec/libsass-todo-tests/libsass/parent-selector/inner-combinator/expected.expanded.css
spec/libsass-todo-tests/libsass/parent-selector/inner-combinator/expected_output.css
spec/libsass-todo-tests/libsass/parent-selector/inner-combinator/input.scss
spec/libsass-todo-tests/libsass/parent-selector/inner-pseudo/expected.compact.css
spec/libsass-todo-tests/libsass/parent-selector/inner-pseudo/expected.compressed.css
spec/libsass-todo-tests/libsass/parent-selector/inner-pseudo/expected.expanded.css
spec/libsass-todo-tests/libsass/parent-selector/inner-pseudo/expected_output.css
spec/libsass-todo-tests/libsass/parent-selector/inner-pseudo/input.scss
spec/libsass-todo-tests/libsass/parent-selector/outer-combinator/expected.compact.css
spec/libsass-todo-tests/libsass/parent-selector/outer-combinator/expected.compressed.css
spec/libsass-todo-tests/libsass/parent-selector/outer-combinator/expected.expanded.css
spec/libsass-todo-tests/libsass/parent-selector/outer-combinator/expected_output.css
spec/libsass-todo-tests/libsass/parent-selector/outer-combinator/input.scss
spec/libsass-todo-tests/libsass/parent-selector/outer-pseudo/expected.compact.css
spec/libsass-todo-tests/libsass/parent-selector/outer-pseudo/expected.compressed.css
spec/libsass-todo-tests/libsass/parent-selector/outer-pseudo/expected.expanded.css
spec/libsass-todo-tests/libsass/parent-selector/outer-pseudo/expected_output.css
spec/libsass-todo-tests/libsass/parent-selector/outer-pseudo/input.scss

This PR adds some todo specs for parent selector regressions present in https://github.com/sass/libsass/pull/124

Add some todo specs for parent selectors

---

spec/libsass-todo-tests/libsass/moz-document/basic/expected.compact.css
spec/libsass-todo-tests/libsass/moz-document/basic/expected.compressed.css
spec/libsass-todo-tests/libsass/moz-document/basic/expected.expanded.css
spec/libsass-todo-tests/libsass/moz-document/basic/expected_output.css
spec/libsass-todo-tests/libsass/moz-document/basic/input.scss
spec/libsass-todo-tests/libsass/moz-document/interpolated/expected.compact.css
spec/libsass-todo-tests/libsass/moz-document/interpolated/expected.compressed.css
spec/libsass-todo-tests/libsass/moz-document/interpolated/expected.expanded.css
spec/libsass-todo-tests/libsass/moz-document/interpolated/expected_output.css
spec/libsass-todo-tests/libsass/moz-document/interpolated/input.scss

This PR adds spec coverage for `@-moz-document`.
https://developer.mozilla.org/en-US/docs/Web/CSS/@document
Related https://github.com/sass/sass-spec/tree/master/spec/libsass-todo-tests/scss-tests/127_test_moz_document_interpolation

Add specs for @-moz-document support

---

spec/libsass/features/at-error/expected.compact.css
spec/libsass/features/at-error/expected.compressed.css
spec/libsass/features/at-error/expected.expanded.css
spec/libsass/features/at-error/expected_output.css
spec/libsass/features/at-error/input.scss
spec/libsass/features/extend-selector-pseudoclass/expected.compact.css
spec/libsass/features/extend-selector-pseudoclass/expected.compressed.css
spec/libsass/features/extend-selector-pseudoclass/expected.expanded.css
spec/libsass/features/extend-selector-pseudoclass/expected_output.css
spec/libsass/features/extend-selector-pseudoclass/input.scss
spec/libsass/features/global-variable-shadowing/expected.compact.css
spec/libsass/features/global-variable-shadowing/expected.compressed.css
spec/libsass/features/global-variable-shadowing/expected.expanded.css
spec/libsass/features/global-variable-shadowing/expected_output.css
spec/libsass/features/global-variable-shadowing/input.scss
spec/libsass/features/units-level-3/expected.compact.css
spec/libsass/features/units-level-3/expected.compressed.css
spec/libsass/features/units-level-3/expected.expanded.css
spec/libsass/features/units-level-3/expected_output.css
spec/libsass/features/units-level-3/input.scss

This PR adds specs to assert we implement all defined [Sass features](https://github.com/sass/sass/blob/7a2cb14d5812cd809def8d7c5b5802a92677569b/lib/sass/features.rb#L10-L15).

Add specs for Sass features

---

lib/sass_spec/engine_adapter.rb

ExecutableEngineAdapter and SassEngineAdapter
should consistently return numeric exit code
from the compiler.
Fixes https://github.com/sass/sass-spec/issues/495 (partially)

ExecutableEngineAdapter should return numeric status

---

lib/sass_spec/engine_adapter.rb

Fully-formatted exception as CSS with
a backtrace is useless to have useful
comparison against known errors we
might want to test against.
This is also inconsistent with regards
to other engines invoked via the command-line
(sassc, Ruby sass CLI) - since in that
case the exception is printed on
the standard output.
Therefore return empty string on
the standard output and only an
error message (without backtrace) to stderr.
Fixes: #497 (to some extent)

Return an exception message to stderr

---

lib/sass_spec/cli.rb
lib/sass_spec/runner.rb
spec/sass/basic/input.scss
spec/sass/imported/expected.compact.css
spec/sass/imported/expected.compressed.css
spec/sass/imported/expected.expanded.css
spec/sass/imported/expected_output.css
spec/sass/imported/imported.sass
spec/sass/imported/input.scss

Now input.scss and input.sass are
reconignized as valid input names.
Fixes: https://github.com/sass/sass-spec/issues/247

Support tests with indented syntax

---

lib/sass_spec/cli.rb
lib/sass_spec/engine_adapter.rb
lib/sass_spec/runner.rb
lib/sass_spec/test.rb
lib/sass_spec/test_case.rb

Enable testing for error output
and sass compiler failures.
If files "error" and "status" are existing
in the test directory, do expect errors
and test against them.
Errors returned by the Sass engines are
now treated as test failures, not errors.
Also create error and status files with --nuke.
An error will be reported in this case anyway.
**Important** Now the tests cannot be ran in parallel,
because we need to capture standard error reliably.
Should fix: https://github.com/sass/sass-spec/issues/136 https://github.com/sass/sass-spec/pull/133

Test for error output

---

lib/sass_spec/cli.rb
lib/sass_spec/runner.rb
lib/sass_spec/test.rb
lib/sass_spec/test_case.rb

With --generate format (or "all") it is possible to run a test case and
generate status, error and up to 4 output files.

Implement --generate format option

---

spec/misc/warn-directive/error

This PR removes an `error` file from a non-error spec. This file causes node-sass' spec suite to fail.

Remove error file from non-error spec

---

lib/sass_spec/test.rb

This patch fixes normalisation of file paths in error messages in
the case where the file path appears in the first line.

Fix normalisation of file paths in error messages

---

lib/sass_spec/test.rb

This is another normalisation step for filepaths. The path of the
file is output before the debug output.
```
/libsass-closed-issues/issue_1243/debug/input.scss:1 DEBUG: foo
```

Normalise ignore file path preceeding debug messages

---

lib/sass_spec/test.rb

We testing error specs we sometimes produce the output files for
different output types. This shouldn't cause an error.
```
No error message produced.
Expected: nil
Actual: ""
```

An empty output file should not cause a failure

---

spec/colors/basic/error
spec/libsass-closed-issues/issue_1106/error
spec/libsass-closed-issues/issue_1124/error
spec/libsass-closed-issues/issue_1240/error
spec/libsass-closed-issues/issue_1243/debug/error
spec/libsass-closed-issues/issue_1258/error
spec/libsass-closed-issues/issue_1291/error
spec/libsass-closed-issues/issue_1331/error
spec/libsass-closed-issues/issue_1336/error
spec/libsass-closed-issues/issue_1578/error.todo
spec/libsass-closed-issues/issue_308/error.todo
spec/libsass-closed-issues/issue_674/error
spec/libsass-todo-issues/issue_1096/error
spec/libsass-todo-tests/color-functions/opacity/opacity/error
spec/libsass-todo-tests/extend-tests/200_test_extend_with_subject_transfers_subject_to_extender/error
spec/libsass-todo-tests/extend-tests/201_test_extend_with_subject_transfers_subject_to_extender/error
spec/libsass-todo-tests/extend-tests/202_test_extend_with_subject_retains_subject_on_target/error
spec/libsass-todo-tests/extend-tests/203_test_extend_with_subject_transfers_subject_to_target/error
spec/libsass-todo-tests/extend-tests/204_test_extend_with_subject_retains_subject_on_extender/error
spec/libsass-todo-tests/extend-tests/205_test_extend_with_subject_fails_with_conflicting_subject/error
spec/libsass-todo-tests/libsass/delayed/error
spec/libsass-todo-tests/libsass/propsets/error
spec/libsass-todo-tests/scss-tests/046_test_parent_selector_with_subject/error
spec/libsass-todo-tests/scss-tests/118_test_parent_selector_with_parent_and_subject/error
spec/libsass/unquote/error
spec/libsass/var-args/error
spec/misc/warn-directive/error

This PR adds missing error messages for specs that we're regenerated after error spec support was added.

Add missing error specs

---

lib/sass_spec/runner.rb
spec/libsass/Sáss-UŢF8/expected.compact.css
spec/libsass/Sáss-UŢF8/expected.compressed.css
spec/libsass/Sáss-UŢF8/expected.expanded.css
spec/libsass/Sáss-UŢF8/expected_output.css
spec/libsass/Sáss-UŢF8/input.scss

* The `runner.rb` file change fixes the file enumeration issue in Ruby+Windows+Unicode scenario. (@xzyfer, as discussed on Slack)
* The test is added for sassc and future command executors to test this spec against Windows. The actual issue sass/libsass#1774 is untestable via spec, since in order to test that particular case, our `cwd` should have multibyte std::string. We can probably test that scenario via `libsass/appveyor.yml` separately.
Test for: sass/sassc#156.
Depends on: sass/sassc#156 and sass/libsass#1774.

Add spec for PR 1774

---

lib/sass_spec/runner.rb

A regression was introduced in https://github.com/sass/sass-spec/pull/640 which broken spec file discovery with when `spec_directory` was an absolute path.
/cc @am11

Fix path resolution regressions for absolute spec directory path

---

lib/sass_spec/runner.rb

Reverts sass/sass-spec#653
This patch broke the runner on Windows. This requires further investigation to fix the regression with absolute spec directory path.
/cc @am11

Revert "Fix path resolution regressions for absolute spec directory path"

---

lib/sass_spec/runner.rb

A regression was introduced in #640 which broken spec file discovery
with when `spec_directory` was an absolute path.
//cc @xzyfer

code: Fixes abosolute path issue

---

lib/sass_spec/test.rb
lib/sass_spec/test_case.rb

I haven't yet tested the nuking functionality, but I'm positive it should also work. Makes CI pass again!

Add path cleaning for error spec tests

---

spec/libsass-closed-issues/issue_657/default/input.scss

It's valid to get one or two duplicates for multiple
calls to random. Update test to take it into account!
Not sure why, but this is only really occuring after 3.4.16!

Make random test more fault tolerant

---

lib/sass_spec/runner.rb
sass-spec.rb

This is needed to integrate sass-spec with ruby sass's build.

Add an option to not exit after running tests.

---

Gemfile
Gemfile.lock
lib/sass_spec/version.rb
sass-spec.gemspec

Ruby Sass will consume sass-spec as a rubygem via this git repo. No need to release it to rubygems.org. This structure is just really helpful for doing parallel development and downloading sass-spec for CI and in development.

Ability to consume sass-spec as a rubygem.

---

sass-spec.gemspec

This reverts commit 9a3bf839d156dcc45138688b6ae76d7a303492d8.
@chriseppstein this commit [broke CI](https://travis-ci.org/sass/sass-spec/builds/115480697). I've had to revert to progress with some LibSass stuff.

Revert "These are not dependencies, actually."

---

lib/sass_spec/engine_adapter.rb

LibSass builds on AppVeyor are failing due to `spec/scss/huge`
timing out.

Increase spec timeout

---

lib/sass_spec/capture_with_timeout.rb

Try to address LibSass AppVeyor failures
https://ci.appveyor.com/project/sass/libsass/build/job/it99o7y579upblf7

Fix `Errno::EINVAL` errors on timeout

---

lib/sass_spec/cli.rb
lib/sass_spec/test_case.rb

`:generate` and `:nuke` ended up being identical after my recent work. This removes `:nuke`

Remove :nuke option as it was redundant

---

.gitignore
.travis.yml
Gemfile.lock
Gemfile.sass_3_5
Gemfile.sass_4_0
sass-spec.gemspec
test_all_impls.sh

This patch makes it easy to test sass spec against all ruby versions in development and sets up CI to do this for every build.

Test all ruby versions

---

spec/sass_3_4_x/README.md
spec/sass_3_4_x/options.yml
spec/sass_3_4_x/simple_supports_clause_in_import/expected_output.css
spec/sass_3_4_x/simple_supports_clause_in_import/input.scss
spec/sass_3_4_x/simple_supports_clause_in_import/options.yml

This spec is for a bug in the sass parser for CSS compatiblity: https://github.com/sass/sass/issues/1967
It is marked as TODO for libsass at this time, I will open a bug against libsass for the entire import supports clause feature which was added a few releases ago.

@import ... supports(...) is supposed to allow bare support declarations.

---

Gemfile.lock
sass-spec.gemspec

- Bump the Sass dependency since the current version in the lock causes test failures
- Remove Rake since it wasn't actually being used

Gemfile updates

---

spec/output_styles/compact/scss/interpolation-operators-precedence/options.yml
spec/output_styles/compressed/scss/interpolation-operators-precedence/options.yml
spec/output_styles/expanded/scss/interpolation-operators-precedence/options.yml
spec/scss/interpolation-operators-precedence/options.yml

LibSass is no more or less inconsistent than Ruby Sass, but it is
different. LibSass will address the differences to Ruby Sass when
sass/sass#2160 is resolved.

Disable interpolation-operators-precedence spec for LibSass

---

lib/sass_spec/cli.rb
lib/sass_spec/engine_adapter.rb
spec/output_styles/compact/libsass/properties-in-media/options.yml
spec/output_styles/compact/scss-tests/186_test_newlines_removed_from_selectors_when_compressed/options.yml
spec/output_styles/compact/scss/media2/options.yml
spec/output_styles/compressed/misc/mixin_content/options.yml
spec/output_styles/compressed/scss-tests/188_test_mixin_content/options.yml
spec/output_styles/compressed/scss/color_output/options.yml

Now that Dart Sass exists, just calling this "sass" is confusing.

Call the Ruby implementation "ruby-sass".

---

spec/parser/operations/binary-and-unary/expected_output.css
spec/parser/operations/binary-and-unary/input.scss

This was broken on Dart Sass but there wasn't a failing spec for it yet.

Add specs for mixing unary and binary operators.

---

spec/libsass-closed-issues/issue_154/options.yml
spec/libsass-closed-issues/issue_274/options.yml
spec/libsass-closed-issues/issue_549/options.yml
spec/libsass-closed-issues/issue_623/options.yml
spec/libsass-closed-issues/issue_931/options.yml

This enables specs for the Microsoft-style `=` operator.

Un-mark tests as TODO for Dart Sass.

---

index.js
package.json

Node Sass to have Sass Spec specs as dependency for inclusion in
the node-citgm. The requirement for being the citgm is that a
packages tests should be executable via `npm install`.
This means Node Sass needs to publish it's tests to npm. That
includes Sass Spec. At the moment Sass Spec is a git submodule so
we'd need to publish the entire repo. This is a [problem](https://twitter.com/nodkz/status/773103622678798336) as
Sass Spec weighs in at 69M.
Size aside some users have experienced issues with some unicode
[file names](https://github.com/sass/node-sass/issues/1699) and [long paths](https://github.com/sass/node-sass/issues/1701). To get around these issues
we want remove the git submodule and instead `npm install` the
Sass Spec spec files. We'd do this a `devDependency` so regular …

Make Sass Spec npm installable

---

spec/extend-tests/193_test_media_in_placeholder_selector/input.scss
spec/libsass/variables_in_media/expected_output.css
spec/libsass/variables_in_media/input.scss
spec/libsass/variables_in_media/options.yml
spec/misc/media_interpolation/expected_output.css
spec/misc/media_interpolation/input.scss
spec/misc/media_interpolation/options.yml
spec/scss-tests/123_test_media_interpolation/expected_output.css
spec/scss-tests/123_test_media_interpolation/input.scss
spec/scss-tests/123_test_media_interpolation/options.yml
spec/scss-tests/124_test_script_in_media/expected_output.css
spec/scss-tests/124_test_script_in_media/input.scss
spec/scss-tests/124_test_script_in_media/options.yml
spec/scss-tests/125_test_script_in_media/expected_output.css
spec/scss-tests/125_test_script_in_media/input.scss
spec/scss-tests/125_test_script_in_media/options.yml
spec/scss-tests/126_test_media_interpolation_with_reparse/expected_output.css
spec/scss-tests/126_test_media_interpolation_with_reparse/input.scss
spec/scss-tests/126_test_media_interpolation_with_reparse/options.yml

A number of specs were using "@media ... {a: b}", which produces invalid
CSS. This updates them to use "@media ... {a {b: c}}" instead.

Use valid media rules in specs.

---

spec/libsass-closed-issues/issue_2132/expected_output.css
spec/libsass-closed-issues/issue_2132/options.yml

The spec was updated in #997 with incorrect output generated by a
big in Ruby Sass https://github.com/sass/sass/issues/2211.
This updates the expected output and disables the spec since all
implemenations are now failing.

Fix and disable str-slice spec

---

spec/libsass-closed-issues/issue_2132/options.yml

This spec was updated with incorrect output in #997 due to a Ruby
Sass bug. In #1004 the output was updated to be correct and the spec
disabled for all implementations because they all suffered from the
original bug.
This PR enables it for LibSass which is now passing with correct output.

Enable the troublesom str-slice spec for libsass

---

spec/sass_3_5/fix-parent-with-newline/expected_output.css
spec/sass_3_5/fix-parent-with-newline/input.scss

Related to https://github.com/sass/sass/issues/1976

Test for fix of parent selector with a multiline rule

---

spec/sass_3_5/alpha_hex/error
spec/sass_3_5/alpha_hex/expected_output.css
spec/sass_3_5/alpha_hex/input.scss
spec/sass_3_5/alpha_hex/options.yml

Add specs for deprecating hex alpha colors.

---

spec/sass_3_5/alpha_hex/options.yml

Best to get this out sooner rather than later so people have time
to upgrade.
[skip libsass]

Activate LibSass specs for 3.5 alpha hex deprecation warning

---

spec/libsass/color-functions/rgb/mix/options.yml

This brings Dart Sass up to full sass-spec compliance, with the
exception of two UTF-16 specs that can't be supported until
dart-lang/sdk#11744 is fixed.
Skip dart-sass

Enable one last spec for Dart Sass.

---

spec/extend-tests/092_test_long_extendee/error
spec/extend-tests/092_test_long_extendee/options.yml
spec/extend-tests/093_test_long_extendee_matches_supersets/error
spec/extend-tests/093_test_long_extendee_matches_supersets/options.yml
spec/libsass-closed-issues/issue_1654/nested/error
spec/libsass-closed-issues/issue_1654/nested/options.yml
spec/libsass/inheritance/error
spec/libsass/inheritance/options.yml

See sass/sass#1599
Skip ruby-sass

Add deprecation messages for compound extends.

---

spec/basic/16_hex_arithmetic/error
spec/basic/16_hex_arithmetic/options.yml
spec/colors/basic/error
spec/colors/basic/options.yml
spec/libsass/color-names/error
spec/libsass/color-names/options.yml

See sass/sass#2144
Skip ruby-sass

Add deprecation messages for color arithmetic.

---

spec/sass_3_5/functions/join/error/positional/error-libsass
spec/sass_3_5/functions/join/error/positional_and_named/error-libsass

Messages differ as catched by perl-libsass.
Not sure why this does not fail official spec runner!?

Add specific libsass error messages

---

spec/css/custom_properties/name_interpolation/expected_output.css
spec/css/custom_properties/name_interpolation/input.scss
spec/css/custom_properties/name_interpolation/options.yml
spec/css/custom_properties/value_interpolation/expected_output.css
spec/css/custom_properties/value_interpolation/input.scss

This adds specs for interpolating the name of the property.
See sass/sass#2383
Skip ruby-sass
Skip dart-sass

Add more specs for custom property interpolation

---

lib/sass_spec/test_case.rb
spec/parser/and_and/options.yml

See https://github.com/sass/libsass/pull/2530
Additionally fix error normalization for dart-sass as the reference for error messages.

Remove and and todo for libsass

---

spec/libsass-closed-issues/issue_2446/error-libsass

Corresponding to https://github.com/sass/libsass/pull/2543

Update libsass error for invalid utf8 spec

---

spec/values/numbers/units/multiple/expected_output-dart-sass.css
spec/values/numbers/units/multiple/expected_output.css
spec/values/numbers/units/multiple/input.scss
spec/values/numbers/units/multiple/options.yml

Add specs for unit math with multiple units

---

spec/libsass-closed-issues/issue_1169/error/color/error-libsass

Needed for https://github.com/sass/libsass/pull/2594 since colors are now directly parsed and not lazy evaluated later. IMO it is even more clear this way why such a key is considered a duplicate, since it is made clear that the key is interpreted as a color.

Adjust error for duplicate key with color keys

---

spec/extend-tests/092_test_long_extendee/error
spec/extend-tests/093_test_long_extendee_matches_supersets/error
spec/libsass-closed-issues/issue_1654/nested/error
spec/libsass/inheritance/error

Use a new link for compound extension warnings

---

spec/extend-tests/094_test_long_extendee_runs_unification/error-dart-sass

Update a Dart Sass error for extending compound selectors

---

spec/basic/16_hex_arithmetic/options.yml
spec/colors/basic/options.yml
spec/errors/invalid-operation/mod/error
spec/libsass/color-names/options.yml
spec/output_styles/compact/basic/16_hex_arithmetic/error
spec/output_styles/compact/basic/22_colors_with_alpha/error
spec/output_styles/compact/libsass-closed-issues/issue_1251/error
spec/output_styles/compact/libsass/color-names/error
spec/output_styles/compact/libsass/test/error
spec/output_styles/compact/scss/color_output/error
spec/output_styles/compressed/basic/16_hex_arithmetic/error
spec/output_styles/compressed/basic/22_colors_with_alpha/error
spec/output_styles/compressed/libsass-closed-issues/issue_1251/error
spec/output_styles/compressed/libsass/color-names/error
spec/output_styles/compressed/libsass/test/error
spec/output_styles/nested/basic/16_hex_arithmetic/error
spec/output_styles/nested/basic/22_colors_with_alpha/error
spec/output_styles/nested/libsass-closed-issues/issue_1251/error
spec/output_styles/nested/libsass/color-names/error
spec/output_styles/nested/libsass/test/error
spec/output_styles/nested/scss/color_output/error

[skip libsass]
- update output style specs, that only libsass runs, with the deprecation warning

Enable colour math deprecation warning specs for LibSass

---

tools/skipped-for-impl.sh

This avoids running into GitHub's low rate limits for unauthenticated
requests.

Fetch the pull request body using @sassbot's credentials

---

Gemfile.lock
spec/mixin/error/no_content/error-ruby-sass

Ruby Sass generates a slightly different error than Dart Sass, so it
needs its own expected error file.

Fix a Ruby Sass breakage

---

spec/values/colors/alpha_hex/deprecation/options.yml
spec/values/colors/alpha_hex/initial_digit/options.yml
spec/values/colors/alpha_hex/initial_letter/options.yml

Enable LibSass specs for hex colors with alpha

---

spec/libsass-closed-issues/issue_2346/expected_output-dart-sass.css
spec/libsass/css_nth_selectors/expected_output-dart-sass.css
spec/libsass/css_nth_selectors/input.scss

Also update the expected :nth-child() output for Dart Sass to match
the new behavior.
See sass/dart-sass#465

Add a regression test case for :nth-child() with extra whitespace

---

spec/values/identifiers/escape/normalize/expected_output.css

Properly escape U+001F as unprintable

---

spec/mixin/content/arguments/error/args_for_argless/error-libsass
spec/mixin/content/arguments/error/expected_args/error-libsass
spec/mixin/content/arguments/error/invalid_arglist/error-libsass
spec/mixin/content/arguments/error/invalid_named_arg/error-libsass
spec/mixin/content/arguments/error/missing_arglist/error-libsass
spec/mixin/content/arguments/error/missing_parens/error-libsass
spec/mixin/content/arguments/error/missing_using/error-libsass
spec/mixin/content/arguments/error/too_few_args/error-libsass
spec/mixin/content/arguments/error/too_many_args/error-libsass
spec/mixin/content/arguments/error/using_without_block/error-libsass
spec/mixin/content/arguments/options.yml
spec/mixin/content/arguments/receiving/output-libsass.css

Enable LibSass specs for @content args

---

spec/extend-tests/094_test_long_extendee_runs_unification/error-dart-sass

See https://github.com/sass/dart-sass/pull/576

Fix "compound selectors may *no* longer be extended" error message

---

spec/css/custom_properties/error/unmatched_brackets/curly/error-dart-sass
spec/libsass-closed-issues/issue_1484/error-dart-sass
spec/libsass-closed-issues/issue_2307/error-dart-sass
spec/libsass-closed-issues/issue_2371/error-dart-sass
spec/libsass-closed-issues/issue_2569/error-dart-sass
spec/libsass-todo-issues/issue_1720/error-dart-sass

This adjusts specs for errors that of the form "expected ____" that
are detected at the end of the file, but should be printed as pointing
after the previous non-whitespace character.

Update specs for Dart Sass errors

---

spec/libsass-todo-issues/issue_2016/error-dart-sass

Update a Dart Sass error spec for the @use parser

---

spec/directives/use/error/load.hrx

Make .scss and .sass take precedence over .css in @use

---

spec/css/keyframes.hrx

Add a spec for bubbling an empty @keyframes rule

---

spec/directives/use/error/load.hrx
spec/directives/use/load.hrx

This doesn't specify the interaction between @use and @import, since
sass/language#75 is unresolved.

Add partial specs for loading CSS with @use

---

lib/sass_spec/runner.rb
spec/libsass/Sáss-UŢF8.hrx
spec/libsass/Sáss-UŢF8/input.scss
spec/libsass/Sáss-UŢF8/output.css
spec/libsass/Sáss-UŢF8.hrx
spec/libsass/Sáss-UŢF8/input.scss
spec/libsass/Sáss-UŢF8/output.css

1. Changes `folder` to `dir.to_s` (`folder` no longer exists).
2. Changes `passing.any?` to `!passing.empty?`, as `any?` has pitfalls:
Took me a few minutes to debug when I tried with `input_path` instead of `dir.to_s`, and that was returning `nil` (`[nil].any? #=> false`).

Fix --test-probe

---

spec/directives/supports.hrx

Tests for https://github.com/sass/libsass/issues/2786 fixed by https://github.com/sass/libsass/pull/2860
[skip libsass]

Add test for sass/libsass#2786

---

spec/css/comment.hrx

comment.hrx: libsass fixed in sass/libsass#2849

---

spec/libsass/Sáss-UŢF8.hrx
spec/libsass/Sáss-UŢF8/input.scss
spec/libsass/Sáss-UŢF8/output.css
spec/libsass/Sáss-UŢF8.hrx
spec/libsass/Sáss-UŢF8/input.scss
spec/libsass/Sáss-UŢF8/output.css

This reverts commit 368cfed2dfecc43245fccdb457b0f8c54dee94f1.
The non-HRX versions of these tests now live in the libsass repo (as of https://github.com/sass/libsass/pull/2855)

Revert "De-HRX libsass/Sáss-UŢF8 and libsass/Sáss-UŢF8"

---

spec/string-functions/quote.hrx

Refs https://github.com/sass/libsass/issues/2811
[skip libsass]
libsass PR: https://github.com/sass/libsass/pull/2873

Add tests for `quote`

---

README.md
STYLE_GUIDE.md

I've tried to capture the best practices I've come up with while
writing tests in the HRX format, mixed with best practices from other
testing traditions and a few rules that mostly serve to just establish
a consistent style.

Add a style guide for writing new specs

---

spec/css/custom_properties/error.hrx

libsass issue: https://github.com/sass/libsass/issues/2655
libsass PR: https://github.com/sass/libsass/pull/2882
[skip libsass]

Enable empty custom property tests for libsass

---

spec/nesting/not.hrx

Refs https://github.com/sass/libsass/issues/2630

Add test for nested `&.:not`

---

lib/sass_spec/directory.rb
lib/sass_spec/test.rb

Previously, only the entrypoint file and the expected output and error
files could be seen. This made it difficult to interactively work with
test cases that involved multiple files, and to see the entire test
case at once.

Show the full test case in --interactive mode

---

spec/core_functions/modules/README.md
spec/core_functions/modules/color.hrx
spec/core_functions/modules/general.hrx
spec/core_functions/modules/map.hrx
spec/core_functions/modules/math.hrx
spec/core_functions/modules/meta.hrx
spec/core_functions/modules/options.yml
spec/core_functions/modules/selector.hrx
spec/core_functions/modules/string.hrx

This does not include specs for functions that are newly defined as
part of the module system spec.

Add specs for built-in modules

---

lib/sass_spec/directory.rb

If an HRX directory is being materialized with #with_real_files and it
contains a file that reaches outside itself (with `../`), materialize
its parent directory as well. This allows individual tests to share
utility libraries that are defined in the same HRX archive.

Materialize parent HRX directories if necessary

---

spec/css/plain/error/expression.hrx
spec/css/plain/error/statement.hrx
spec/libsass-todo-issues/issue_2295/error/basic.hrx
spec/libsass-todo-issues/issue_2295/error/wrapped.hrx

Instead of using "root stylesheet" as the member name for the loaded
files, this now uses "@import" or "@use".

Produce better stack traces for syntax errors loaded via import/use

---

spec/directives/forward/member/import.hrx

Add a spec for a nested import of a module that forwards a variable

---

spec/core_functions/meta/load_css/error.hrx
spec/core_functions/meta/load_css/extend.hrx
spec/core_functions/meta/load_css/options.yml
spec/core_functions/meta/load_css/plain_css.hrx
spec/core_functions/meta/load_css/twice.hrx
spec/core_functions/meta/load_css/with.hrx

Add specs for load-css()

---

lib/sass_spec/cli.rb
lib/sass_spec/engine_adapter.rb

Renames `--dart-args` to `--cmd-args`
Allows libsass to work around #1427.
@nex3 I probably will merge this very soon since #1427 is quite a blocker ATM for me.
I think this change makes sense even on its own, but feel free to change it as you see fit.

Allow arguments to be passed to any command

---

spec/core_functions/meta/mixin_exists.hrx

Fix what I assue must be a typo in a filename in `different_module/defined` in `spec/core_functions/meta/mixin_exists.hrx`

Fix a filename typo

---

spec/core_functions/math/max.hrx
spec/core_functions/math/min.hrx

Depends on https://github.com/sass/libsass/pull/2933

fix: Enable libsass 2914

---

spec/core_functions/meta/feature_exists.hrx

This should have been landed along with sass/libsass#2929, but that
ship has sailed.

Update feature-exists() specs for sass/libsass#2929

---

spec/core_functions/meta/keywords.hrx
spec/libsass/variable-scoping/blead-global/expanding/mixin.hrx

We're going against Ruby Sass in normalizing the keys in the
keywords() function, but this is the more user-friendly solution
because it doesn't require users to manually dash-normalize in order
to match caller expectations.

Update a couple specs for eager dash-normalization in Dart Sass

---

lib/sass_spec/engine_adapter.rb

fix: Include spec path as relitive to engine-adapter

---

spec/core_functions/meta/call.hrx

fix: Update call parameter to $function

---

spec/core_functions/color/scale_color/hsl.hrx

These tests are fixed by https://github.com/sass/libsass/pull/2954
[skip libsass]

Enable scale-color saturation tests for libsass

---

spec/core_functions/string/insert.hrx

fix: Add error for non-int str-insert index

---

spec/core_functions/string/slice.hrx

fix: non-integers passed to str-slice

---

spec/directives/import/css.hrx

Add a spec for an unquoted plain-CSS import

---

spec/core_functions/meta/load_css/error.hrx
spec/core_functions/meta/load_css/twice.hrx
spec/core_functions/meta/load_css/with.hrx
spec/core_functions/modules/general.hrx
spec/css/custom_properties/error.hrx
spec/directives/forward/member/as.hrx
spec/directives/forward/member/bare.hrx
spec/directives/forward/member/import.hrx
spec/directives/forward/member/shadowed.hrx
spec/directives/forward/member/visibility.hrx
spec/directives/use/error/member.hrx
spec/directives/use/error/syntax.hrx
spec/directives/use/error/with.hrx
spec/directives/use/member.hrx
spec/directives/use/with.hrx

Change the variable syntax to namespace.$name

---

spec/libsass-todo-issues/issue_2994.hrx

https://github.com/sass/libsass/issues/2994

Add todo spec test for libsass issue 2994

---

.travis.yml
lib/sass_spec/cli.rb
lib/sass_spec/test.rb
tests/cli_spec.rb
tests/fixtures/limit/basic.hrx
tests/spec_helper.rb

This is a set of unit tests on the --limit flag.
It contains two bug fixes:
* Limit flag accepts negative numbers, despite what docs say (which leads to unintuitive behavior)
* When using limits, the runner would always run limit + 1 tests.
This also adds the Unit tests into Travis runs.

Tests + bug fixes on --limit flag

---

spec/libsass/error-directive-nested/function.hrx
spec/libsass/error-directive-nested/mixin.hrx

Update specs to print call-site for @errors in mixins and functions

---

spec/core_functions/color/hsl/error/five_args.hrx
spec/core_functions/color/hsl/error/four_args.hrx
spec/core_functions/color/hsl/error/one_arg.hrx
spec/core_functions/color/hsl/error/three_args.hrx
spec/core_functions/color/hsl/error/two_args.hrx
spec/core_functions/color/hsl/error/zero_args.hrx
spec/core_functions/color/hsla/error/five_args.hrx
spec/core_functions/color/hsla/error/four_args.hrx
spec/core_functions/color/hsla/error/one_arg.hrx
spec/core_functions/color/hsla/error/three_args.hrx
spec/core_functions/color/hsla/error/two_args.hrx
spec/core_functions/color/hsla/error/zero_args.hrx
spec/core_functions/color/rgb/error/five_args.hrx
spec/core_functions/color/rgb/error/four_args.hrx
spec/core_functions/color/rgb/error/one_arg.hrx
spec/core_functions/color/rgb/error/three_args.hrx
spec/core_functions/color/rgb/error/two_args.hrx
spec/core_functions/color/rgb/error/zero_args.hrx
spec/core_functions/color/rgba/error/five_args.hrx
spec/core_functions/color/rgba/error/four_args.hrx
spec/core_functions/color/rgba/error/one_arg.hrx
spec/core_functions/color/rgba/error/three_args.hrx
spec/core_functions/color/rgba/error/two_args.hrx
spec/core_functions/color/rgba/error/zero_args.hrx
spec/core_functions/color/saturate.hrx

Fix errors for overloaded function arguments

---

spec/directives/import/configuration.hrx

Add specs for configuration through imports

---

spec/directives/use/member/namespaced.hrx

Don't include leading underscores in implicit namespaces

---

spec/libsass-closed-issues/issue_2520.hrx

This warning was added by sass/libsass#2913

Add a missing warning to a LibSass spec

---

spec/core_functions/selector/unify/README.md
spec/core_functions/selector/unify/chooses_superselector.hrx
spec/core_functions/selector/unify/complex/combinators.hrx
spec/core_functions/selector/unify/complex/distinct.hrx
spec/core_functions/selector/unify/complex/identical.hrx
spec/core_functions/selector/unify/complex/lcs.hrx
spec/core_functions/selector/unify/complex/overlap.hrx
spec/core_functions/selector/unify/complex/root.hrx
spec/core_functions/selector/unify/complex/superselector.hrx
spec/core_functions/selector/unify/compound.hrx
spec/core_functions/selector/unify/error.hrx
spec/core_functions/selector/unify/format.hrx
spec/core_functions/selector/unify/simple/attribute.hrx
spec/core_functions/selector/unify/simple/class.hrx
spec/core_functions/selector/unify/simple/different_types.hrx
spec/core_functions/selector/unify/simple/id.hrx
spec/core_functions/selector/unify/simple/placeholder.hrx
spec/core_functions/selector/unify/simple/pseudo.hrx
spec/core_functions/selector/unify/simple/type.hrx
spec/core_functions/selector/unify/simple/universal.hrx

Add specs for selector-unify()

---

lib/sass_spec/cli.rb

Caught by the Debian Lintian tool:
`I: sass-spec: spelling-error-in-manpage usr/share/man/man1/sass-spec.1.gz unecessary unnecessary`
Thanks!

Fix typo: unecessary → unnecessary

---

spec/non_conformant/extend-tests/extend-result-of-extend.hrx

Fix single character typo

---

spec/core_functions/map/deep_merge.hrx

Note: this is the same as #1560, but correctly pointed at the
`feature.nested-maps` branch.
See sass/sass#2836

Add specs for map.deep-merge()

---

.travis.yml

Rather than always defaulting to master, if Travis is running for a
feature branch or a pull request targeting a feature branch, it will
default to using the same feature branch in Dart Sass.

Test against a matching Dart Sass feature branch by default

---

spec/core_functions/string/index.hrx

Other `str-*` functions dealing with string indexes have such tests but they were missing for `str-index`. This ensures that `str-index` handles them properly (which is required to be useful when other functions handle them properly).

Add specs covering double width chars for str-index

---

spec/libsass/features/at-error.hrx
spec/libsass/features/extend-selector-pseudoclass.hrx
spec/libsass/features/global-variable-shadowing.hrx
spec/libsass/features/units-level-3.hrx

These specs are exactly the same than the ones available in `core_functions/meta/feature_exists.hrx` (which has more of them).

Remove duplicate specs for feature-exists

---

spec/libsass/Sáss-UŢF8.hrx

Closes https://github.com/sass/sass-spec/issues/1551
I kept the other file as it is the one used in the CI for libsass: https://github.com/sass/libsass/blob/87292ae4b2167401b505be1188d3b82861ab3253/appveyor.yml#L93
And having only one of them won't be an issue.

Remove duplicate file creating issues in a case sensitive filesystem

---

spec/core_functions/meta/call.hrx

The `if()` function has a special evaluation behavior. But `call()` does not have it and so calling `if()` through `call()` must not have this behavior.
This behavior is already good in dart-sass and libsass (and even ruby-sass) but it serves as regression test for https://github.com/scssphp/scssphp/issues/216

Add a spec covering the usage of the if function with call

---

spec/directives/import/error/not_found.hrx

I discovered that the handling of imports in https://github.com/scssphp/scssphp/ is flawed. Importing a file leaks its directory as a load (and before configured load paths), effectively allowing to resolve imports relatively to caller files in the import chain.
This adds a spec preventing such behavior.
Neither dart-sass nor libsass are affected by the issue.

Add a spec enforcing that import don't leak a load path

---

lib/sass_spec/engine_adapter.rb
tests/fixtures/basic/basic.hrx
tests/fixtures/limit/basic.hrx
tests/fixtures/todo/basic.hrx
tests/sass_stub

Closes #1540 
To run specs against a sass binary, use this command:
```
bundle exec ./sass-spec.rb --impl dart-sass -c /path/to/sass --cmd-args='--no-unicode --no-color'
```
`--cmd-args` is needed to match the arguments used by `--dart` so that the output matches the expectation.
Regarding performance, this indeed helps when running only a few specs. Here are the result on my machine. The `-c` run uses the Linux x64 binary for dart-sass 1.28.0 downloaded from the github releases.
Full run:
- `--dart`: Finished in 23.162925s, 251.1773 runs/s
- `-c`: Finished in 131.673413s, 44.1851 runs/s
Run filtered on `spec/directives/import/error/not_found`:
- `--dart`: Finished in 0.264161s, 11.3567 runs/s
- `-c`: Finished in 0.069728s, 43.0243 runs/s

Make the spec runner compatible with the sass executable

---

lib/sass_spec/engine_adapter.rb

The latest dev version of Dart enables null safety by default, so we need to explicitly disable it in the spec running script until we migrate to null safety (which we have to wait for all of our dependencies to migrate first).

Disable null safety when running Dart tests

---

spec/directives/for.hrx

Currently includes commits from #1615. This will get cleaned once it is merged.
Closes #1616
skip dart-sass

Add specs for the handling of unit in for loops

---

spec/css/selector.hrx

This should fix the broken specs and unblock Dart Sass PRs.
Check the CI log manually to confirm there are now failures before submitting, since it's currently not reporting them.
As a sidenote, we should probably do something about specs containing lines ending with whitespace. A lot of editors (including mine) automatically remove trailing whitespace, which makes it easy for errors like this to slip in.

Fix broken selector specs

---

.editorconfig

The configured rules help contributors respect the project styles when their editor support this (which most editors do either natively or with a plugin nowadays), even if their own editor configuration has different defaults.
The configured rules for now are:
- use 2 spaces for indentation
- don't trim trailing whitespaces in HRX files, as some specs rely on them (see #1622)

Add an editorconfig file with basic rules for editors

---

lib-js/cli-args.ts
lib-js/compiler.ts
sass-spec.ts
test/fixtures/mock-compiler.ts
test/test-case/actual.test.ts

In node, write to stdout are asynchronous and can happen over multiple ticks of the event loop.
process.exit() forces the program to exit immediately, without waiting for any remaining pending asynchronous work, which can result in lost output if the output is not fully written yet.
Setting the process.exitCode property instead will configure the exit code to be used, while letting node terminate the process normally when nothing is pending in the event loop anymore.
See https://nodejs.org/api/process.html#process_process_exit_code for the doc about it.

Improve the way to exit from the spec runner

---

spec/directives/at_root.hrx

This case is not covered by any of the existing `@at-root` specs. However, we have a test case for that in the scssphp testsuite. I think upstreaming it here makes sense.

Add a spec covering the case of at-root wrapping a property declaration

---

spec/css/comment.hrx

This ensures that such failures are not ignored silently.
scssphp used to ignore interpolation in comments. Then, interpolation support was implemented but in a lenient way, showing the original source of the comment in case of failure (either due to the parsing of the interpolation or due to its evaluation).
This enforces the proper behavior for comments.

Add specs covering interpolation failures in loud comments

---

spec/directives/extend/error.hrx

While working on scssphp, I discovered that these error cases were not covered anywhere in sass-spec (most of `@extend` is still covered by non-conformant specs, but even those don't cover those cases)

Add specs covering errors for non simple extended selectors

---

spec/core_functions/selector/extend/no_op.hrx
spec/core_functions/selector/extend/simple/pseudo/selector/idempotent.hrx
spec/core_functions/selector/extend/simple/pseudo/selector/match.hrx
spec/core_functions/selector/is_superselector/simple/pseudo/selector_arg/is.hrx
spec/core_functions/selector/nest.hrx
spec/core_functions/selector/parse/selector.hrx
spec/core_functions/selector/replace.hrx
spec/core_functions/selector/unify/simple/pseudo.hrx
spec/css/selector.hrx
spec/directives/use/extend.hrx

Add specs for :is()

---

spec/core_functions/selector/extend/simple/pseudo/selector/match.hrx

Otherwise ruby spec runner is sad :(
https://github.com/sass/libsass/pull/3156/checks?check_run_id=2634854094
```diff
1) Failure:
SassSpec::Test#test__sass-spec/spec/core_functions/selector/extend/simple/pseudo/selector/match/unprefixed/is/class/unequal/has_argument [/home/runner/work/libsass/libsass/sass-spec/lib/sass_spec/test.rb:267]:
expected did not match output.
--- expected
+++ actual
@@ -1,3 +1,4 @@
"a {
b: :is(c d.e, f g);
-}"
+}
+"
```

Add missing newline for expected output

---

lib-js/cli-args.ts
lib-js/compiler.ts

Thet `--verbose` argument is needed by the `dart-sass` implementation for both implementations of the sass-spec Compiler, not only for the DartCompiler. Otherwise, specs are failing when running `npm run sass-spec -- --impl dart-sass -c $(which sass) spec/non_conformant/scss/precision`

Fix the arguments for running specs against the dart-sass command

---

spec/parser/operator_precedence.hrx

This is a regression test for https://github.com/scssphp/scssphp/issues/435 (and https://github.com/scssphp/scssphp/issues/434 which is caused by it)
Due to a bug, scssphp was parsing that as `(true or 1 < 0) and false` instead of `true or (1 < 0 and false)` (it happened due to the 3 operators with precedence of 1, 3 and 2. Removing the `<` operator was not reproducing the issue anymore).

Add a regression test for operator precedence

---

sass-spec.ts

The dart compiler does not break anymore. It properly reports a failure about invalid UTF-8.

Remove the skipping of so-called naughty spec directories

---

lib-js/spec-directory/real-directory.ts

I discovered this issue while scripting #1694 as some files were not properly removed.
It looks like mutations are only tested for VirtualDirectory and not RealDirectory.

Fix the removal of files for real directories

---

.github/workflows/ci.yml
jest.config.js
jest.config.ts
js-api-spec.ts
js-api-spec/legacy/render.test.ts
package-lock.json
package.json

So far this only has one ultra-simple test, but we can build it out
once the core infrastructure is in place.

Add the ability to run shared JS API tests

---

spec/values/calculation/calc/no_operator.hrx
spec/values/calculation/calc/operator.hrx

See sass/sass#3153
See sass/sass#3154

Preserve parentheses around var() functions in calculations

---

spec/core_functions/color/mix.hrx

Bootstrap 5 relies on using unitless weights in `mix()`. Our implementation in scssphp was buggy (which is the root cause of https://github.com/scssphp/scssphp/issues/459), treating `1` as being `100%` rather than `1%` (i.e. treating it the same than alpha channels for the `rgba()` function).
this adds spec covering the usage with unitless numbers rather than percentages.

Add specs covering unitless weights in mix()

---

package-lock.json
package.json

As of version 4, `del` ships its own type definitions.

Remove the deprecated del types package

---

spec/core_functions/selector/unify/simple/type.hrx

This case was copying the previous one instead of doing what its name implies.

Fix assertion for the selector-unify specs

---

spec/core_functions/selector/unify/complex/combinators.hrx

Nesting spec directories inside another spec directory is not supported, and will ignore the nested ones.

Fix the specs for multiple combinators in selector-unify

---

spec/core_functions/selector/is_superselector/simple/pseudo/selector_arg/is.hrx

When reflecting changes from `matches.hrx` to `is.hrx`, the prefixed pseudos have not been replaced properly.

Fix specs covering prefixed :is() for superselector specs

---

js-api-spec.ts
js-api-spec/importer.test.ts
js-api-spec/utils.ts

Add specs for the new JS importer API

---

spec/css/plain/import/conditions.hrx

This adds a spec covering https://github.com/sass/dart-sass/issues/1462
skip dart-sass

Add specs covering functions in import support conditions

---

js-api-spec/legacy/render.test.ts

This avoids getting a warning from the static analysis on each PR.

Remove unused import

---

spec/css/selector.hrx

see sass/sass#3199 [skip dart-sass]

Add spec for css empty namespace attribute selector

---

js-api-spec/legacy/render.test.ts
js-api-spec/legacy/source-map.test.ts

This also updates source map tests to expect that result.map is
undefined rather than null when it's not returned. This matches the
behavior of Node Sass and the TS type declarations.

Enable render() and source map tests for the embedded host

---

spec/core_functions/color/saturation.hrx

A color with 100% lightness is white, whatever its hue and saturation. For such colors, a roundtrip to the RGB values will not preserve the original saturation, making them a bad choice for the tests of the saturation function.
This is the same kind of fix than #1709

Use non-white colors for the saturation tests

---

js-api-spec/compile.test.ts

https://github.com/sass/sass/pull/3226
skip dart-sass

Add specs covering the sourceMapIncludeSources option

---

js-api-spec/compile.test.ts

Some tests were incorrectly grouped. Below is the before and after of this PR.
Before:
```
PASS  js-api-spec/compile.test.ts (17.176 s)
compileString
success
✓ doesn't throw a Sass exception for an argument error (1 ms)
✓ is an instance of Error (82 ms)
input
✓ compiles SCSS by default (187 ms)
✓ compiles SCSS with explicit syntax (154 ms)
✓ compiles indented syntax with explicit syntax (166 ms)
✓ compiles plain CSS with explicit syntax (170 ms)
✓ doesn't take its syntax from the URL's extension (194 ms)
loadedUrls
✓ is empty with no URL (189 ms)
✓ contains the URL if one is passed (1149 ms)
✓ contains an immediate dependency (147 ms)
✓ contains a transitive dependency (121 ms)
✓ url is used to resolve relative loads (104 ms)
✓ recognizes the expanded output style (111 ms)
contains a …
```

Fix compile spec grouping

---

js-api-spec/legacy/source-map.test.ts

This also adds one additional regression test for an issue identified
in https://github.com/webpack-contrib/sass-loader/issues/774#issuecomment-1039253270.

Enable all legacy source map tests for the embedded host

---

js-api-spec/legacy/importer.test.ts

Add a spec for an empty importer list in the legacy API.

---

js-api-spec/compile.test.ts
js-api-spec/sandbox.ts

The newly-tested behavior matches the specification as updated by
sass/sass#3278.

Fix and add specs for relative imports with `compileString()`

---

js-api-spec/legacy/importer.test.ts

Add a regression test for sass/embedded-host-node#126

---

spec/css/plain/import/conditions.hrx

See https://github.com/sass/sass/issues/3285
skip dart-sass

Add specs covering CSS imports with layer conditions

---

js-api-spec/legacy/render.test.ts

Add a regression test for a meta.load-css bug in Dart Sass

---

js-api-spec/compile.test.ts

https://github.com/sass/sass/issues/3242
- https://github.com/sass/sass/pull/3346
See https://github.com/sass/dart-sass/pull/1732
See https://github.com/sass/embedded-host-node/pull/152
See https://github.com/sass/dart-sass-embedded/pull/91

Add spec for js-api charset option

---

spec/core_functions/color/adjust_hue.hrx
spec/core_functions/color/hwb/three_args/units.hrx

Add specs for passing non-deg units to hwb's hue

---

spec/core_functions/color/adjust_color/error/bounds.hrx
spec/core_functions/color/change_color/error/bounds.hrx
spec/core_functions/color/fade_in.hrx
spec/core_functions/color/fade_out.hrx

Improve error messages for incorrect units in color functions

---

lib-js/spec-directory/index.ts
lib-js/spec-directory/real-directory.ts
lib-js/spec-directory/spec-directory.ts
lib-js/spec-directory/spec-path.ts
lib-js/spec-directory/virtual-directory.ts
test/spec-directory/iteration.test.ts

This makes directory addressing transparent across both of these, so 
passing `spec/expressions/` or `spec/expressions/syntax.hrx` will no longer
break the runner.

Runner: Allow directories to be passed with trailing slashes/`.hrx`

---

lint-spec.ts

recombines all existing directory unit tests into HRX files reverting files breaking up on #1817
Fixes #1821

hrx linter no longer validates or breaks down HRX where the root is a unit test

---

spec/libsass-closed-issues/issue_1739/basic.hrx
spec/libsass-closed-issues/issue_1739/interpolate/both.hrx
spec/libsass-closed-issues/issue_1739/interpolate/left.hrx
spec/libsass-closed-issues/issue_1739/interpolate/right.hrx
spec/libsass-closed-issues/issue_893.hrx
spec/non_conformant/parser/operations/addition/dimensions/pairs.hrx
spec/non_conformant/parser/operations/addition/numbers/pairs.hrx
spec/non_conformant/parser/operations/addition/strings/pairs.hrx
spec/non_conformant/parser/operations/subtract/strings/pairs.hrx
spec/non_conformant/scss/interpolation-operators-precedence.hrx
spec/operators/minus.hrx
spec/operators/plus.hrx

Update specs for strict unary deprecation

---

spec/core_functions/color/adjust_color/units.hrx
spec/core_functions/color/adjust_hue.hrx
spec/core_functions/color/change_color/units.hrx
spec/core_functions/color/hsl/three_args/units.hrx
spec/core_functions/color/hwb/three_args/units.hrx

Update specs to convert angle units to deg

---

.gitignore
js-api-spec/importer.test.ts
js-api-spec/legacy/importer.test.ts
js-api-spec/utils.ts

Test invalid arguments for importer results.
- Tests contents not being string values
- Tests SassException argument errors have better output
- Adds sandbox directory to .gitignore
See https://github.com/sass/dart-sass/pull/1816

Test invalid contents for importer results

---

js-api-spec/importer.test.ts

This await is actually needed or the promise returned by `expect()` would run away because the promise is created but the funciton returns `undefined` immmedately after constuct the promise. Or alternatively the curly bracket before `expect` needs to be removed, so that the async function returns a promise that will be waited.

Fix runaway promise

---

js-api-spec/function.test.ts
js-api-spec/legacy/function.test.ts

Add tests for strict whitespace in JS function signatures

---

.github/workflows/ci.yml

I added this under the erroneous impression that we ran *language*
tests against Dart Sass rather than just *JS API* tests.

Don't auto-skip dart-sass-embedded along with dart-sass

---

lib/spec-directory/index.ts
lint-spec.ts
sass-spec.ts
test/spec-directory/iteration.test.ts
test/spec-directory/mutations.test.ts
test/spot-check.test.ts

This clarifies that this should only be used for the root directory of
a test suite, since it won't consider any options that come from
parent directories. This also refactors lint-spec.ts to avoid using
this function for subdirectories.

Rename `fromPath()` to `fromRoot()`

---

lib/spec-directory/index.ts
lib/spec-directory/real-directory.ts
lib/spec-directory/spec-directory.ts
lib/spec-directory/virtual-directory.ts

This allows us to stop eagerly fetching options to pass to subdirectories,
which helps ensure correctness when parent directory options are modified.
Having access to the parent directory also makes more complex and powerful
automated refactors possible.

Add `SpecDirectory.parent()`

---

lib/compiler.ts

If Dart chose to block while writing stdout or stderr, only requesting
one of them could cause the runner to deadlock.

Fix a race condition in the Dart compiler

---

spec/parser/selector.hrx

See https://github.com/sass/dart-sass/issues/1855

Add regression test for escaped backslash

---

.github/workflows/ci.yml

Our unit tests are having issues on Node >14, so we're leaving most tests as-is for now.
For the JS API, this updates to test on 18/16/14 instead of 16/14/12, since Node 12 no longer works.

Update Node for JS API to 18/16/14, leave other tests at 14

---

.github/workflows/ci.yml

The embedded host now uses buf to compile its protobufs, which it can
install through npm.

Stop using arduino/setup-protoc

---

spec/css/font-face.hrx
spec/css/keyframes.hrx

See: https://github.com/sass/dart-sass/pull/1899

Specs for pulling the @font-face at-rule to root.

---

lib/cli-args.ts
lib/test-case/compare.ts
lib/test-case/test-case.ts
sass-spec.ts

Adds 3 new CLI flags to configure how warning and error diffs are handled. 
Closes https://github.com/sass/sass-spec/issues/1679

add new flags for comparing warning and error diffs

---

js-api-spec.ts

This fixes a breakage caused by moving the specs to a literate
programming style in sass/sass#3552.

Run specs against the JS API doc typedefs

---

.github/workflows/ci.yml

This PR fixes the following warning:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

Fix deprecation warnings in GitHub Actions

---

js-api-spec.ts
karma.config.js
package-lock.json
package.json

The default reporter only prints tests on a single line as they run,
which makes it much harder to debug failures, particularly on CI.

Report JS API tests as they pass or fail

---

js-api-spec/legacy/importer.node.test.ts

Issue: https://github.com/sass/dart-sass/issues/1962
See: https://github.com/sass/embedded-host-node/pull/226

JS API tests for loading multiple nested paths with renderSync

---

spec/core_functions/selector/unify/complex/combinators/multiple.hrx
spec/core_functions/selector/unify/complex/combinators/next_sibling.hrx
spec/non_conformant/extend-tests/146_test_combinator_unification_tilde_plus.hrx

This really _shouldn't_ affect any CSS output, but these changes are
semantically irrelevant and arguably better-looking than the old
versions.

Update specs for Dart-3-style Dart Sass

---

spec/values/calculation/abs.hrx

https://github.com/sass/dart-sass/pull/2084

Fix abs-percent warning span

---

js-api-spec/importer.node.test.ts
js-api-spec/importer.test.ts

Add tests for containing URL support

---

spec/core_functions/color/hsl/error/one_arg.hrx
spec/core_functions/color/lab/_utils.scss
spec/core_functions/color/lab/alpha.hrx
spec/core_functions/color/lab/error.hrx
spec/core_functions/color/lab/no_alpha.hrx
spec/core_functions/color/lab/options.yml
spec/core_functions/color/lab/special_functions/alpha.hrx
spec/core_functions/color/lab/special_functions/no_alpha.hrx
spec/core_functions/color/lab/special_functions/slash_list.hrx
spec/core_functions/color/rgb/error/one_arg.hrx

This still needs error output, but Dart Sass currently doesn't support
missing alpha channels or the is-missing() function so they can't be
generated yet.
See https://github.com/sass/sass/issues/2831

[Color 4] Add tests for `lab()`

---

spec/core_functions/color/hsl/one_arg/relative_color.hrx
spec/core_functions/color/rgb/one_arg/relative_color.hrx

https://github.com/sass/sass/pull/3673

Add specs for the support of relative CSS colors

---

.github/workflows/ci.yml

This PR helps us avoid manually updating node versions to test in the future.

Use lts/* and lts/-n for node version

---

js-api-spec/compiler.node.test.ts
js-api-spec/compiler.test.ts

[Issue](https://github.com/sass/sass/issues/3296)
Blocked until [proposal](https://github.com/sass/sass/blob/main/proposal/shared-resources.d.ts.md) is accepted.
- https://github.com/sass/sass/pull/3744
- https://github.com/sass/dart-sass/pull/2134
- https://github.com/sass/embedded-host-node/pull/261

[Shared Resources] Add JS API tests

---

js-api-spec/node-package-importer.node.test.ts

https://github.com/sass/dart-sass/issues/2183
Adds the positive checks for what export keys should be matched given a subpath `color` or `color.scss`.
sass- https://github.com/sass/sass/pull/3793
dart-sass- https://github.com/sass/dart-sass/pull/2184

[Hotfix Node Package Importer]- Handle subpath without extensions

---

js-api-spec/deprecations.test.ts

See https://github.com/sass/sass/pull/3826

Add tests for the deprecations API

---

.github/util/dart-sass/action.yml
.github/workflows/ci.yml
js-api-spec/deprecations.test.ts
js-api-spec/importer.test.ts

See https://github.com/sass/sass/pull/3834

Merge main into feature.color-4

---

spec/css/keyframes.hrx
spec/libsass/selectors/simple.hrx

Add tests for `@keyframes` nesting errors

---

spec/core_functions/color/is_missing.hrx
spec/core_functions/color/is_powerless/error.hrx

This also adds a missing case-sensitivity test for `is-powerless()`.
See sass/sass#3851

[Color 4] Add tests for `is-missing()`

---

spec/directives/function.hrx
spec/directives/mixin.hrx

Add tests for underscores where hyphens aren't allowed

---

js-api-spec.ts
js-api-spec/deprecations.node.test.ts
js-api-spec/deprecations.test.ts

See https://github.com/sass/sass/pull/3872.

Update deprecations tests to use YAML list

---

spec/css/functions/special.hrx
spec/css/style_rule.hrx
spec/css/supports/comment.hrx
spec/css/unknown_directive/comment.hrx
spec/css/unknown_directive/plain.hrx
spec/directives/import/comment.hrx
spec/libsass-closed-issues/issue_1263.hrx

Add tests for comments in more expression-like contexts

---

js-api-spec/deprecations.node.test.ts

I think this test got changed to work with the embedded host after the tests had already passed on Dart Sass

Fix test for legacy JS API warning

---

spec/core_functions/selector/unify/complex/combinators/child.hrx
spec/core_functions/selector/unify/complex/combinators/multiple.hrx
spec/core_functions/selector/unify/complex/combinators/next_sibling.hrx
spec/core_functions/selector/unify/complex/combinators/sibling.hrx
spec/core_functions/selector/unify/complex/rootish.hrx
spec/core_functions/selector/unify/compound.hrx
spec/libsass-closed-issues/issue_2289.hrx
spec/non_conformant/extend-tests/127_test_nested_extender_with_early_child_selector.hrx
spec/non_conformant/extend-tests/142_test_combinator_unification_double_tilde.hrx
spec/non_conformant/extend-tests/146_test_combinator_unification_tilde_plus.hrx
spec/non_conformant/extend-tests/150_test_combinator_unification_tilde_plus.hrx
spec/non_conformant/extend-tests/156_test_combinator_unification_double_angle.hrx
spec/non_conformant/extend-tests/158_test_combinator_unification_double_angle.hrx
spec/non_conformant/extend-tests/160_test_combinator_unification_double_plus.hrx
spec/non_conformant/extend-tests/162_test_combinator_unification_double_plus.hrx
spec/non_conformant/extend-tests/176_test_combinator_unification_nested.hrx
spec/non_conformant/extend-tests/177_test_combinator_unification_nested.hrx
spec/non_conformant/extend-tests/178_test_combinator_unification_with_newlines.hrx
spec/non_conformant/extend-tests/238_unify_root_pseudoelement.hrx

See https://github.com/sass/dart-sass/issues/2335
See https://github.com/sass/dart-sass/pull/2350

Update tests for fixing unifyCompound() and unifyComplex() ordering of pseudo class/element selectors

---

js-api-spec/value/color/color-4-conversions.test.ts

Add tests for `SassColor.interpolate()` without options

---

spec/core_functions/color/invert/error.hrx
spec/core_functions/color/invert/global.hrx
spec/core_functions/global/color/invert.hrx
spec/libsass-closed-issues/issue_456.hrx

Remove global-builtin deprecation for plain-CSS `invert()`

---

spec/values/calculation/abs.hrx
spec/values/calculation/max.hrx
spec/values/calculation/min.hrx
spec/values/calculation/round/error.hrx
spec/values/calculation/round/one_argument.hrx

This also updates tests expect global function warnings when
calculations are falling back on global Sass functions.
See sass/sass#3803
Closes #2036

Add tests for CSS `round()` with one argument

---

spec/directives/extend/error.hrx

Test `@extend` without a selector

---

js-api-spec/value/boolean.test.ts

See https://github.com/sass/embedded-host-node/pull/359

Test that sassTrue and sassFalse are instances of SassBoolean

---

js-api-spec/value/function.test.ts
js-api-spec/value/mixin.test.ts

https://github.com/sass/dart-sass/issues/2542
https://github.com/sass/dart-sass/pull/2544
https://github.com/sass/embedded-host-node/pull/367

Disallow passing functions/mixins across compilations
