- spec/libsass-todo-issues/issue_813/expected_output.css
- spec/libsass-todo-issues/issue_813/input.scss
This PR adds specs for passing vararg arguments by value (https://github.com/sass/libsass/issues/813).
> Add specs for issue 813

- spec/libsass-closed-issues/issue_859/expected_output.css
- spec/libsass-closed-issues/issue_859/input.scss
This PR activates specs for https://github.com/sass/libsass/issues/859 in preparation for https://github.com/sass/libsass/pull/861
> Activate specs for issue 859

- spec/colors/expected_output.css
- spec/colors/input.scss
Ensure that saturation of fully saturated colours or desaturation of fully desaturated colours has no effect.
See https://github.com/sass/libsass/issues/864 https://github.com/sass/libsass/pull/865
> Check saturation/desaturation

- spec/libsass-todo-issues/issue_870/expected_output.css
- spec/libsass-todo-issues/issue_870/input.scss
http://github.com/sass/libsass/issues/870
> Add test for libsass issue 870

- spec/libsass-closed-issues/issue_877/expected_output.css
- spec/libsass-closed-issues/issue_877/input.scss
This PR activates specs for underscore normalisation https://github.com/sass/libsass/issues/877 in preparation for https://github.com/sass/libsass/pull/888.
> Activate specs for underscore normalisation

- spec/libsass/calc/expected_output.css
- spec/libsass/calc/input.scss
This PR updates the calc spec to test `-ms-calc` (https://github.com/sass/libsass/issues/842)
> Update calc spec to test -ms-calc

- spec/libsass-todo-issues/issue_893/expected_output.css
- spec/libsass-todo-issues/issue_893/input.scss
adds a spec for sass/libsass#893
> add spec for libsass issue 893

- spec/libsass-closed-issues/issue_452/expected.compact.css
- spec/libsass-closed-issues/issue_452/expected.compressed.css
- spec/libsass-closed-issues/issue_452/expected.expanded.css
- spec/libsass-closed-issues/issue_452/expected_output.css
- spec/libsass-closed-issues/issue_452/input.scss
- spec/libsass-todo-issues/issue_452/expected.compact.css
- spec/libsass-todo-issues/issue_452/expected.compressed.css
- spec/libsass-todo-issues/issue_452/expected.expanded.css
- spec/libsass-todo-issues/issue_452/expected_output.css
- spec/libsass-todo-issues/issue_452/input.scss
Also adds some other tests for open issues!
> Activate test for libsass issue 452

- spec/libsass-todo-issues/issue_1007/expected.compact.css
- spec/libsass-todo-issues/issue_1007/expected.compressed.css
- spec/libsass-todo-issues/issue_1007/expected.expanded.css
- spec/libsass-todo-issues/issue_1007/expected_output.css
- spec/libsass-todo-issues/issue_1007/input.scss
Bug: https://github.com/sass/libsass/issues/1007
PR: https://github.com/sass/libsass/pull/1008
> Add spec test for libsass issue 1007

- spec/libsass/units/feature-test/expected.compact.css
- spec/libsass/units/feature-test/expected.compressed.css
- spec/libsass/units/feature-test/expected.expanded.css
- spec/libsass/units/feature-test/expected_output.css
- spec/libsass/units/feature-test/input.scss
This PR activates specs for the `units-level-3` feature test.
> Activate spec for units-level-3 feature test

- spec/libsass-todo-issues/issue_1025/expected.compact.css
- spec/libsass-todo-issues/issue_1025/expected.compressed.css
- spec/libsass-todo-issues/issue_1025/expected.expanded.css
- spec/libsass-todo-issues/issue_1025/expected_output.css
- spec/libsass-todo-issues/issue_1025/input.scss
> Add spec for not inserting excessive white spaces in :not() selectors

- spec/libsass-todo-issues/issue_1029/expected.compact.css
- spec/libsass-todo-issues/issue_1029/expected.compressed.css
- spec/libsass-todo-issues/issue_1029/expected.expanded.css
- spec/libsass-todo-issues/issue_1029/expected_output.css
- spec/libsass-todo-issues/issue_1029/input.scss
> Add a spec for a lost rule when extending inside a double for loop

- spec/libsass-todo-issues/issue_1030/expected.compact.css
- spec/libsass-todo-issues/issue_1030/expected.compressed.css
- spec/libsass-todo-issues/issue_1030/expected.expanded.css
- spec/libsass-todo-issues/issue_1030/expected_output.css
- spec/libsass-todo-issues/issue_1030/input.scss
> Add a spec for not inserting a double linefeed in a nested @supports block

- spec/libsass-todo-issues/issue_1026/expected.compact.css
- spec/libsass-todo-issues/issue_1026/expected.compressed.css
- spec/libsass-todo-issues/issue_1026/expected.expanded.css
- spec/libsass-todo-issues/issue_1026/expected_output.css
- spec/libsass-todo-issues/issue_1026/input.scss
> Add spec for incorrect indentation in a multi-line comment

- spec/libsass-closed-issues/issue_1036/expected.compact.css
- spec/libsass-closed-issues/issue_1036/expected.compressed.css
- spec/libsass-closed-issues/issue_1036/expected.expanded.css
- spec/libsass-closed-issues/issue_1036/expected_output.css
- spec/libsass-closed-issues/issue_1036/input.scss
Test was already passing, but IMO it's an interesting edge case so we probably want to be able catch it if ruby sass ever decides to handle this differently.
> Add spec test for libsass issue 1036

- spec/libsass-closed-issues/issue_1060/expected.compact.css
- spec/libsass-closed-issues/issue_1060/expected.compressed.css
- spec/libsass-closed-issues/issue_1060/expected.expanded.css
- spec/libsass-closed-issues/issue_1060/expected_output.css
- spec/libsass-closed-issues/issue_1060/input.scss
This PR activates the specs for https://github.com/sass/libsass/issues/1060.
> Activate specs for issue 1060

- spec/libsass-todo-issues/issue_1081/_import.scss
- spec/libsass-todo-issues/issue_1081/expected.compact.css
- spec/libsass-todo-issues/issue_1081/expected.compressed.css
- spec/libsass-todo-issues/issue_1081/expected.expanded.css
- spec/libsass-todo-issues/issue_1081/expected_output.css
- spec/libsass-todo-issues/issue_1081/input.scss
This PR adds specs for https://github.com/sass/libsass/issues/1081
> Add specs for issue 1081

- spec/libsass-todo-issues/issue_1082/expected.compact.css
- spec/libsass-todo-issues/issue_1082/expected.compressed.css
- spec/libsass-todo-issues/issue_1082/expected.expanded.css
- spec/libsass-todo-issues/issue_1082/expected_output.css
- spec/libsass-todo-issues/issue_1082/input.scss
This PR adds specs for sass/libsass#1082
> Add specs for issue 1082

- spec/libsass-todo-issues/issue_1087/expected.compact.css
- spec/libsass-todo-issues/issue_1087/expected.compressed.css
- spec/libsass-todo-issues/issue_1087/expected.expanded.css
- spec/libsass-todo-issues/issue_1087/expected_output.css
- spec/libsass-todo-issues/issue_1087/input.scss
This PR adds specs for sass/libsass#1087.
> Add specs for issue 1087

- spec/libsass-todo-issues/issue_1061/expected.compact.css
- spec/libsass-todo-issues/issue_1061/expected.compressed.css
- spec/libsass-todo-issues/issue_1061/expected.expanded.css
- spec/libsass-todo-issues/issue_1061/expected_output.css
- spec/libsass-todo-issues/issue_1061/input.scss
> Add specs for preserving new lines more often than they should be

- spec/libsass/variable-scoping/defaults-global-null/expected.compact.css
- spec/libsass/variable-scoping/defaults-global-null/expected.compressed.css
- spec/libsass/variable-scoping/defaults-global-null/expected.expanded.css
- spec/libsass/variable-scoping/defaults-global-null/expected_output.css
- spec/libsass/variable-scoping/defaults-global-null/input.scss
- spec/libsass/variable-scoping/defaults-global/expected.compact.css
- spec/libsass/variable-scoping/defaults-global/expected.compressed.css
- spec/libsass/variable-scoping/defaults-global/expected.expanded.css
- spec/libsass/variable-scoping/defaults-global/expected_output.css
- spec/libsass/variable-scoping/defaults-global/input.scss
- spec/libsass/variable-scoping/defaults-null/expected.compact.css
- spec/libsass/variable-scoping/defaults-null/expected.compressed.css
- spec/libsass/variable-scoping/defaults-null/expected.expanded.css
- spec/libsass/variable-scoping/defaults-null/expected_output.css
- spec/libsass/variable-scoping/defaults-null/input.scss
This accompanies https://github.com/sass/libsass/pull/1084
> Add additional tests for variable scoping

- spec/sass/basic/expected.compact.css
- spec/sass/basic/expected.compressed.css
- spec/sass/basic/expected.expanded.css
- spec/sass/basic/expected_output.css
- spec/sass/basic/input.sass
- spec/sass/basic/input.scss
We actually can test `sass` files by using a simple import in `input.scss`.
> Add first indented syntax test

- spec/libsass-todo-tests/libsass/scale/expected.compact.css
- spec/libsass-todo-tests/libsass/scale/expected.compressed.css
- spec/libsass-todo-tests/libsass/scale/expected.expanded.css
- spec/libsass-todo-tests/libsass/scale/expected_output.css
- spec/libsass-todo-tests/libsass/scale/note.txt
Also see https://github.com/sass/sass/issues/1690
> Fix test case (ruby sass output is wrong)

- spec/libsass-todo-issues/issue_1063/expected.compact.css
- spec/libsass-todo-issues/issue_1063/expected.compressed.css
- spec/libsass-todo-issues/issue_1063/expected.expanded.css
- spec/libsass-todo-issues/issue_1063/expected_output.css
- spec/libsass-todo-issues/issue_1063/input.scss
This PR adds specs for issue sass/libsass#1063
> Add specs for issue 1063

- spec/libsass-todo-issues/issue_1063/expected.compact.css
- spec/libsass-todo-issues/issue_1063/expected.compressed.css
- spec/libsass-todo-issues/issue_1063/expected.expanded.css
- spec/libsass-todo-issues/issue_1063/expected_output.css
- spec/libsass-todo-issues/issue_1063/input.scss
This PR greatly simplifies the spec for https://github.com/sass/libsass/issues/1063
> Simplify spec for issue 1063

- spec/libsass-todo-issues/issue_1080/expected.compact.css
- spec/libsass-todo-issues/issue_1080/expected.compressed.css
- spec/libsass-todo-issues/issue_1080/expected.expanded.css
- spec/libsass-todo-issues/issue_1080/expected_output.css
- spec/libsass-todo-issues/issue_1080/input.scss
This PR adds specs for issue sass/libsass#1080
> Add specs for issue 1080

- spec/libsass-todo-issues/issue_1092/expected.compact.css
- spec/libsass-todo-issues/issue_1092/expected.compressed.css
- spec/libsass-todo-issues/issue_1092/expected.expanded.css
- spec/libsass-todo-issues/issue_1092/expected_output.css
- spec/libsass-todo-issues/issue_1092/input.scss
This PR adds specs for issue sass/libsass#1092
> Add specs for issue 1092

- spec/libsass-todo-issues/issue_1106/input.scss
This PR adds specs for https://github.com/sass/libsass/issues/1106
> Add spec for issue 1106

- spec/libsass-todo-issues/issue_1107/expected.compact.css
- spec/libsass-todo-issues/issue_1107/expected.compressed.css
- spec/libsass-todo-issues/issue_1107/expected.expanded.css
- spec/libsass-todo-issues/issue_1107/expected_output.css
- spec/libsass-todo-issues/issue_1107/input.scss
This PR adds specs for https://github.com/sass/libsass/issues/1107
> Add spec for issue 1107

- spec/libsass-todo-issues/issue_1121/expected.compact.css
- spec/libsass-todo-issues/issue_1121/expected.expanded.css
- spec/libsass-todo-issues/issue_1121/expected_output.css
- spec/libsass-todo-issues/issue_1121/input.scss
This PR adds specs for https://github.com/sass/libsass/issues/1121
> Add specs for issue 1121

- spec/libsass-todo-issues/issue_1124/expected.compact.css
- spec/libsass-todo-issues/issue_1124/expected.compressed.css
- spec/libsass-todo-issues/issue_1124/expected.expanded.css
- spec/libsass-todo-issues/issue_1124/expected_output.css
- spec/libsass-todo-issues/issue_1124/input.scss
This PR add specs for https://github.com/sass/libsass/issues/1124#
> Add specs for issue 1124

- spec/libsass-todo-issues/issue_1127/expected.compact.css
- spec/libsass-todo-issues/issue_1127/expected.compressed.css
- spec/libsass-todo-issues/issue_1127/expected.expanded.css
- spec/libsass-todo-issues/issue_1127/expected_output.css
- spec/libsass-todo-issues/issue_1127/input.scss
This PR adds specs for sass/libsass#1127
> Add specs for issue 1127

- spec/libsass-todo-issues/issue_1133/normal/expected.compact.css
- spec/libsass-todo-issues/issue_1133/normal/expected.compressed.css
- spec/libsass-todo-issues/issue_1133/normal/expected.expanded.css
- spec/libsass-todo-issues/issue_1133/normal/expected_output.css
- spec/libsass-todo-issues/issue_1133/normal/input.scss
- spec/libsass-todo-issues/issue_1133/vararg/expected.compact.css
- spec/libsass-todo-issues/issue_1133/vararg/expected.compressed.css
- spec/libsass-todo-issues/issue_1133/vararg/expected.expanded.css
- spec/libsass-todo-issues/issue_1133/vararg/expected_output.css
- spec/libsass-todo-issues/issue_1133/vararg/input.scss
This PR adds specs for https://github.com/sass/libsass/issues/1133
> Add specs for issue 1133

- spec/libsass-todo-issues/issue_1130/expected.compact.css
- spec/libsass-todo-issues/issue_1130/expected.compressed.css
- spec/libsass-todo-issues/issue_1130/expected.expanded.css
- spec/libsass-todo-issues/issue_1130/expected_output.css
- spec/libsass-todo-issues/issue_1130/input.scss
This PR adds specs for https://github.com/sass/libsass/issues/1130
> Add specs for issue 1130

- spec/libsass-todo-issues/issue_1098/expected.compact.css
- spec/libsass-todo-issues/issue_1098/expected.compressed.css
- spec/libsass-todo-issues/issue_1098/expected.expanded.css
- spec/libsass-todo-issues/issue_1098/expected_output.css
- spec/libsass-todo-issues/issue_1098/input.scss
This PR updates specs for sass/libsass#1098 for greater completeness.
> Update the spec for issue 1098 to cover more cases

- spec/libsass-todo-issues/issue_1096/expected.compact.css
- spec/libsass-todo-issues/issue_1096/expected.compressed.css
- spec/libsass-todo-issues/issue_1096/expected.expanded.css
- spec/libsass-todo-issues/issue_1096/expected_output.css
- spec/libsass-todo-issues/issue_1096/input.scss
This PR adds specs for sass/libsass#1096
> Add specs for issue 1096

- spec/libsass-todo-issues/issue_1102/expected.compact.css
- spec/libsass-todo-issues/issue_1102/expected.compressed.css
- spec/libsass-todo-issues/issue_1102/expected.expanded.css
- spec/libsass-todo-issues/issue_1102/expected_output.css
- spec/libsass-todo-issues/issue_1102/input.scss
This PR adds specs for sass/libsass#1102
> Add specs for issue 1102

- spec/libsass-todo-issues/issue_1103/_import.scss
- spec/libsass-todo-issues/issue_1103/expected.compact.css
- spec/libsass-todo-issues/issue_1103/expected.compressed.css
- spec/libsass-todo-issues/issue_1103/expected.expanded.css
- spec/libsass-todo-issues/issue_1103/expected_output.css
- spec/libsass-todo-issues/issue_1103/input.scss
This PR adds specs for sass/libsass#1103
> Add specs for issue 1103

- spec/libsass/eq/expected.compact.css
- spec/libsass/eq/expected.compressed.css
- spec/libsass/eq/expected.expanded.css
- spec/libsass/eq/expected_output.css
- spec/libsass/eq/input.scss
- spec/libsass/lists/expected.compact.css
- spec/libsass/lists/expected.compressed.css
- spec/libsass/lists/expected.expanded.css
- spec/libsass/lists/expected_output.css
- spec/libsass/lists/input.scss
- spec/libsass/rel/expected.compact.css
- spec/libsass/rel/expected.compressed.css
- spec/libsass/rel/expected.expanded.css
- spec/libsass/rel/expected_output.css
- spec/libsass/rel/input.scss
- https://github.com/sass/libsass/pull/1055
- https://github.com/sass/libsass/pull/1049
- https://github.com/sass/libsass/pull/1047
- https://github.com/sass/libsass/pull/1138
> Activate passing spec tests in preparation for 3.2.1

- spec/libsass-todo-issues/issue_1043/expected.compact.css
- spec/libsass-todo-issues/issue_1043/expected.compressed.css
- spec/libsass-todo-issues/issue_1043/expected.expanded.css
- spec/libsass-todo-issues/issue_1043/expected_output.css
- spec/libsass-todo-issues/issue_1043/input.scss
Issue: https://github.com/sass/libsass/issues/1043
> Add spec test for libsass issue 1043

- spec/libsass-todo-issues/issue_1096/expected.compact.css
- spec/libsass-todo-issues/issue_1096/expected.compressed.css
- spec/libsass-todo-issues/issue_1096/expected.expanded.css
- spec/libsass-todo-issues/issue_1096/expected_output.css
- spec/libsass-todo-issues/issue_1096/input.scss
This PR updates the specs for https://github.com/sass/libsass/issues/1096 covering the cases mentioned in https://github.com/sass/libsass/pull/1196#discussion_r30008425.
> Update specs for issue 1096

- spec/libsass-todo-issues/issue_1025/expected_output.css
- spec/libsass-todo-issues/issue_1188/expected.compact.css
- spec/libsass-todo-issues/issue_1188/expected.compressed.css
- spec/libsass-todo-issues/issue_1188/expected.expanded.css
- spec/libsass-todo-issues/issue_1188/expected_output.css
- spec/libsass-todo-issues/issue_1188/input.scss
- spec/libsass-todo-issues/issue_1192/expected.compact.css
- spec/libsass-todo-issues/issue_1192/expected.expanded.css
- spec/libsass-todo-issues/issue_1192/expected_output.css
- spec/libsass-todo-issues/issue_1192/input.scss
- https://github.com/sass/libsass/issues/1188
- https://github.com/sass/libsass/issues/1192
> Add specs for missing issues

- spec/libsass-todo-issues/issue_1208/expected.compact.css
- spec/libsass-todo-issues/issue_1208/expected.compressed.css
- spec/libsass-todo-issues/issue_1208/expected.expanded.css
- spec/libsass-todo-issues/issue_1208/expected_output.css
- spec/libsass-todo-issues/issue_1208/input.scss
This PR adds specs for https://github.com/sass/libsass/issues/1208.
> Add specs for issue 1208

- spec/libsass-todo-issues/issue_1210/expected.compact.css
- spec/libsass-todo-issues/issue_1210/expected.compressed.css
- spec/libsass-todo-issues/issue_1210/expected.expanded.css
- spec/libsass-todo-issues/issue_1210/expected_output.css
- spec/libsass-todo-issues/issue_1210/input.scss
This PR add specs for sass/libsass#1210
> Add specs for issue 1210

- spec/libsass-todo-issues/issue_1214/expected.compact.css
- spec/libsass-todo-issues/issue_1214/expected.compressed.css
- spec/libsass-todo-issues/issue_1214/expected.expanded.css
- spec/libsass-todo-issues/issue_1214/expected_output.css
- spec/libsass-todo-issues/issue_1214/input.scss
This PR add specs for sass/libsass#1214
> Add specs for issue 1214

- spec/libsass-todo-issues/issue_1218/expected.compact.css
- spec/libsass-todo-issues/issue_1218/expected.compressed.css
- spec/libsass-todo-issues/issue_1218/expected.expanded.css
- spec/libsass-todo-issues/issue_1218/expected_output.css
- spec/libsass-todo-issues/issue_1218/input.scss
This PR add specs for sass/libsass#1218
> Add specs for issue 1218

- spec/libsass-closed-issues/issue_1218/expected.compact.css
- spec/libsass-closed-issues/issue_1218/expected.compressed.css
- spec/libsass-closed-issues/issue_1218/expected.expanded.css
- spec/libsass-closed-issues/issue_1218/expected_output.css
- spec/libsass-closed-issues/issue_1218/input.scss
- spec/libsass-todo-issues/issue_1218/expected.compact.css
- spec/libsass-todo-issues/issue_1218/expected.compressed.css
- spec/libsass-todo-issues/issue_1218/expected.expanded.css
- spec/libsass-todo-issues/issue_1218/expected_output.css
- spec/libsass-todo-issues/issue_1218/input.scss
This PR updates and activates specs for sass/libsass#1218
> Activate specs for issue 1218

- spec/libsass-closed-issues/issue_1224/input.scss
This PR activates specs for sass/libsass#1224
> Activate specs for issue

- spec/libsass-closed-issues/issue_1215/expected.compact.css
- spec/libsass-closed-issues/issue_1215/expected.compressed.css
- spec/libsass-closed-issues/issue_1215/expected.expanded.css
- spec/libsass-closed-issues/issue_1215/expected_output.css
- spec/libsass-closed-issues/issue_1215/input.scss
This PR activates specs for sass/libsass#1215
> Activate specs for issue 1215

- spec/libsass-todo-issues/issue_1251/expected.compact.css
- spec/libsass-todo-issues/issue_1251/expected.compressed.css
- spec/libsass-todo-issues/issue_1251/expected.expanded.css
- spec/libsass-todo-issues/issue_1251/expected_output.css
- spec/libsass-todo-issues/issue_1251/input.scss
This PR add specs for sass/libsass#1251
> Add specs for issue 1251

- spec/libsass-todo-issues/issue_1253/expected.compact.css
- spec/libsass-todo-issues/issue_1253/expected.compressed.css
- spec/libsass-todo-issues/issue_1253/expected.expanded.css
- spec/libsass-todo-issues/issue_1253/expected_output.css
- spec/libsass-todo-issues/issue_1253/input.scss
https://github.com/sass/libsass/issues/1253
> Add missing todo spec tests for issue 1253

- spec/libsass-todo-issues/issue_1219/expected.compact.css
- spec/libsass-todo-issues/issue_1219/expected.compressed.css
- spec/libsass-todo-issues/issue_1219/expected.expanded.css
- spec/libsass-todo-issues/issue_1219/expected_output.css
- spec/libsass-todo-issues/issue_1219/input.scss
https://github.com/sass/libsass/issues/1219
> Add missing todo spec tests for issue 1219

- spec/libsass-todo-issues/issue_1281/expected.compact.css
- spec/libsass-todo-issues/issue_1281/expected.compressed.css
- spec/libsass-todo-issues/issue_1281/expected.expanded.css
- spec/libsass-todo-issues/issue_1281/expected_output.css
- spec/libsass-todo-issues/issue_1281/input.scss
This PR add specs for sass/libsass#1281
> Add specs for issue 1281

- spec/libsass-todo-issues/issue_1279/expected.compact.css
- spec/libsass-todo-issues/issue_1279/expected.compressed.css
- spec/libsass-todo-issues/issue_1279/expected.expanded.css
- spec/libsass-todo-issues/issue_1279/expected_output.css
- spec/libsass-todo-issues/issue_1279/input.scss
This PR add specs for sass/libsass#1279
> Add specs for issue 1279

- spec/libsass-todo-issues/issue_1227/expected.compact.css
- spec/libsass-todo-issues/issue_1227/expected.compressed.css
- spec/libsass-todo-issues/issue_1227/expected.expanded.css
- spec/libsass-todo-issues/issue_1227/expected_output.css
- spec/libsass-todo-issues/issue_1227/input.scss
This PR add specs for sass/libsass#1277
> Add specs for issue 1277

- spec/libsass-todo-issues/issue_1298/expected.compact.css
- spec/libsass-todo-issues/issue_1298/expected.compressed.css
- spec/libsass-todo-issues/issue_1298/expected.expanded.css
- spec/libsass-todo-issues/issue_1298/expected_output.css
- spec/libsass-todo-issues/issue_1298/input.scss
This PR add specs for sass/libsass#1298
> Add specs for issue 1298

- spec/libsass-todo-issues/issue_1297/expected.compact.css
- spec/libsass-todo-issues/issue_1297/expected.compressed.css
- spec/libsass-todo-issues/issue_1297/expected.expanded.css
- spec/libsass-todo-issues/issue_1297/expected_output.css
- spec/libsass-todo-issues/issue_1297/input.scss
This PR add specs for sass/libsass#1297
> Add specs for issue 1297

- spec/libsass-todo-issues/issue_1285/expected.compact.css
- spec/libsass-todo-issues/issue_1285/expected.compressed.css
- spec/libsass-todo-issues/issue_1285/expected.expanded.css
- spec/libsass-todo-issues/issue_1285/expected_output.css
- spec/libsass-todo-issues/issue_1285/input.scss
This PR add specs for sass/libsass#1285
> Add specs for issue 1285

- spec/libsass-todo-issues/issue_1322/expected.compact.css
- spec/libsass-todo-issues/issue_1322/expected.compressed.css
- spec/libsass-todo-issues/issue_1322/expected.expanded.css
- spec/libsass-todo-issues/issue_1322/expected_output.css
- spec/libsass-todo-issues/issue_1322/input.scss
This PR add specs for sass/libsass#1322
> Add specs for issue 1322

- spec/libsass-closed-issues/issue_1323/expected.compact.css
- spec/libsass-closed-issues/issue_1323/expected.compressed.css
- spec/libsass-closed-issues/issue_1323/expected.expanded.css
- spec/libsass-closed-issues/issue_1323/expected_output.css
- spec/libsass-closed-issues/issue_1323/input.scss
This PR activates specs for sass/libsass#1323
> Activate specs for issue 1323

- spec/libsass-closed-issues/issue_1331/input.scss
This PR activates specs for sass/libsass#1331
> Activate specs for issue 1331

- spec/libsass-todo-issues/issue_1305/expected.compact.css
- spec/libsass-todo-issues/issue_1305/expected.compressed.css
- spec/libsass-todo-issues/issue_1305/expected.expanded.css
- spec/libsass-todo-issues/issue_1305/expected_output.css
- spec/libsass-todo-issues/issue_1305/input.scss
This PR add specs for sass/libsass#1305
> Add specs for issue 1305

- spec/libsass-todo-issues/issue_1303/expected.compact.css
- spec/libsass-todo-issues/issue_1303/expected.compressed.css
- spec/libsass-todo-issues/issue_1303/expected.expanded.css
- spec/libsass-todo-issues/issue_1303/expected_output.css
- spec/libsass-todo-issues/issue_1303/input.scss
This PR add specs for sass/libsass#1303
> Add specs for issue 1303

- spec/libsass-todo-issues/issue_1301/expected.compact.css
- spec/libsass-todo-issues/issue_1301/expected.compressed.css
- spec/libsass-todo-issues/issue_1301/expected.expanded.css
- spec/libsass-todo-issues/issue_1301/expected_output.css
- spec/libsass-todo-issues/issue_1301/input.scss
This PR add specs for sass/libsass#1301
> Add specs for issue 1301

- spec/libsass-todo-issues/issue_1336/input.scss
This PR add specs for sass/libsass#1336
> Add specs for issue 1336

- spec/libsass-todo-issues/issue_1333/expected.compact.css
- spec/libsass-todo-issues/issue_1333/expected.compressed.css
- spec/libsass-todo-issues/issue_1333/expected.expanded.css
- spec/libsass-todo-issues/issue_1333/expected_output.css
- spec/libsass-todo-issues/issue_1333/input.scss
This PR add specs for sass/libsass#1333
> Add specs for issue 1333

- spec/libsass-todo-issues/issue_1328/expected.compact.css
- spec/libsass-todo-issues/issue_1328/expected.compressed.css
- spec/libsass-todo-issues/issue_1328/expected.expanded.css
- spec/libsass-todo-issues/issue_1328/expected_output.css
- spec/libsass-todo-issues/issue_1328/input.scss
This PR add specs for sass/libsass#1328
> Add specs for issue 1328

- lib/sass_spec/test_case.rb
Needed to pass one test with output from libsass (libsass issue 1263)!
> Improve white-space cleaning to cover media queries

- spec/libsass-todo-issues/issue_1393/expected.compact.css
- spec/libsass-todo-issues/issue_1393/expected.compressed.css
- spec/libsass-todo-issues/issue_1393/expected.expanded.css
- spec/libsass-todo-issues/issue_1393/expected_output.css
- spec/libsass-todo-issues/issue_1393/input.scss
- spec/libsass-todo-tests/extend-tests/notes.txt
This PR add specs for sass/libsass#1393
> Add specs for issue 1393

- spec/libsass-todo-issues/issue_1396/expected.compact.css
- spec/libsass-todo-issues/issue_1396/expected.compressed.css
- spec/libsass-todo-issues/issue_1396/expected.expanded.css
- spec/libsass-todo-issues/issue_1396/expected_output.css
- spec/libsass-todo-issues/issue_1396/input.scss
This PR add specs for sass/libsass#1396
> Add specs for issue 1396

- spec/libsass-todo-issues/issue_1398/expected.compact.css
- spec/libsass-todo-issues/issue_1398/expected.compressed.css
- spec/libsass-todo-issues/issue_1398/expected.expanded.css
- spec/libsass-todo-issues/issue_1398/expected_output.css
- spec/libsass-todo-issues/issue_1398/input.scss
This PR add specs for sass/libsass#1398
> Add specs for issue 1398

- spec/libsass-todo-issues/issue_1399/expected.compact.css
- spec/libsass-todo-issues/issue_1399/expected.compressed.css
- spec/libsass-todo-issues/issue_1399/expected.expanded.css
- spec/libsass-todo-issues/issue_1399/expected_output.css
- spec/libsass-todo-issues/issue_1399/input.scss
This PR add specs for sass/libsass#1399
> Add specs for issue 1399

- spec/libsass-closed-issues/issue_1425/expected.compact.css
- spec/libsass-closed-issues/issue_1425/expected.compressed.css
- spec/libsass-closed-issues/issue_1425/expected.expanded.css
- spec/libsass-closed-issues/issue_1425/expected_output.css
- spec/libsass-closed-issues/issue_1425/input.scss
This PR activates specs for sass/libsass#1425
> Activate specs for issue 1425

- spec/libsass-todo-issues/issue_1417/expected.compact.css
- spec/libsass-todo-issues/issue_1417/expected.compressed.css
- spec/libsass-todo-issues/issue_1417/expected.expanded.css
- spec/libsass-todo-issues/issue_1417/expected_output.css
- spec/libsass-todo-issues/issue_1417/input.scss
This PR add specs for sass/libsass#1417
> Add specs for issue 1417

- spec/libsass-todo-issues/issue_1434/expected.compact.css
- spec/libsass-todo-issues/issue_1434/expected.compressed.css
- spec/libsass-todo-issues/issue_1434/expected.expanded.css
- spec/libsass-todo-issues/issue_1434/expected_output.css
- spec/libsass-todo-issues/issue_1434/input.scss
> add specs for issue 1434

- spec/libsass-closed-issues/issue_1438/expected.compact.css
- spec/libsass-closed-issues/issue_1438/expected.compressed.css
- spec/libsass-closed-issues/issue_1438/expected.expanded.css
- spec/libsass-closed-issues/issue_1438/expected_output.css
- spec/libsass-closed-issues/issue_1438/input.scss
This PR activates specs for sass/libsass#1438
> Activate specs for issue 1438

- spec/libsass-todo-issues/issue_1482/expected.compact.css
- spec/libsass-todo-issues/issue_1482/expected.compressed.css
- spec/libsass-todo-issues/issue_1482/expected.expanded.css
- spec/libsass-todo-issues/issue_1482/expected_output.css
- spec/libsass-todo-issues/issue_1482/input.scss
This PR add specs for sass/libsass#1482
> Add specs for issue 1482

- spec/libsass-todo-issues/issue_1482/expected.compact.css
- spec/libsass-todo-issues/issue_1482/expected.compressed.css
- spec/libsass-todo-issues/issue_1482/expected.expanded.css
- spec/libsass-todo-issues/issue_1482/expected_output.css
- spec/libsass-todo-issues/issue_1482/input.scss
Applying @mgreter's update spec from #479.
> Update specs for issue 1482

- spec/libsass-closed-issues/issue_1535/expected.compact.css
- spec/libsass-closed-issues/issue_1535/expected.compressed.css
- spec/libsass-closed-issues/issue_1535/expected.expanded.css
- spec/libsass-closed-issues/issue_1535/expected_output.css
- spec/libsass-closed-issues/issue_1535/input.scss
This PR add specs for sass/libsass#1535
> Add specs for issue 1535

- spec/libsass-closed-issues/issue_1546/expected.compact.css
- spec/libsass-closed-issues/issue_1546/expected.compressed.css
- spec/libsass-closed-issues/issue_1546/expected.expanded.css
- spec/libsass-closed-issues/issue_1546/expected_output.css
- spec/libsass-closed-issues/issue_1546/input.sass
This PR add specs for sass/libsass#1546
> Add specs for issue 1546

- spec/libsass-todo-issues/issue_1567/expected.compact.css
- spec/libsass-todo-issues/issue_1567/expected.compressed.css
- spec/libsass-todo-issues/issue_1567/expected.expanded.css
- spec/libsass-todo-issues/issue_1567/expected_output.css
- spec/libsass-todo-issues/issue_1567/input.scss
Add specs for https://github.com/sass/libsass/issues/1567
> Add specs for libsass issue 1567

- spec/libsass-todo-issues/issue_1570/expected.compact.css
- spec/libsass-todo-issues/issue_1570/expected.compressed.css
- spec/libsass-todo-issues/issue_1570/expected.expanded.css
- spec/libsass-todo-issues/issue_1570/expected_output.css
- spec/libsass-todo-issues/issue_1570/input.scss
https://github.com/sass/libsass/issues/1570
> Add spec for libsass issue 1570

- spec/libsass-todo-issues/issue_1566/expected.compact.css
- spec/libsass-todo-issues/issue_1566/expected.compressed.css
- spec/libsass-todo-issues/issue_1566/expected.expanded.css
- spec/libsass-todo-issues/issue_1566/expected_output.css
- spec/libsass-todo-issues/issue_1566/input.scss
https://github.com/sass/libsass/issues/1566
> Add spec for libsass issue 1566

- spec/libsass-todo-issues/issue_1568/input.scss
https://github.com/sass/libsass/issues/1568
> Add spec for libsass issue 1568

- spec/libsass-todo-issues/issue_1557/expected.compact.css
- spec/libsass-todo-issues/issue_1557/expected.compressed.css
- spec/libsass-todo-issues/issue_1557/expected.expanded.css
- spec/libsass-todo-issues/issue_1557/expected_output.css
- spec/libsass-todo-issues/issue_1557/input.scss
https://github.com/sass/libsass/issues/1557
> Add spec for libsass issue 1557

- spec/libsass-todo-issues/issue_1579/expected.compact.css
- spec/libsass-todo-issues/issue_1579/expected.compressed.css
- spec/libsass-todo-issues/issue_1579/expected.expanded.css
- spec/libsass-todo-issues/issue_1579/expected_output.css
- spec/libsass-todo-issues/issue_1579/input.scss
Named arguments after unnamed arguments not being passed in correctly
https://github.com/sass/libsass/issues/1579
> Libsass issue 1579

- spec/libsass-todo-issues/issue_1583/expected.compact.css
- spec/libsass-todo-issues/issue_1583/expected.compressed.css
- spec/libsass-todo-issues/issue_1583/expected.expanded.css
- spec/libsass-todo-issues/issue_1583/expected_output.css
- spec/libsass-todo-issues/issue_1583/input.scss
This PR add specs for sass/libsass#1583
> Add specs for issue 1583

- spec/libsass-todo-issues/issue_1574/expected.compact.css
- spec/libsass-todo-issues/issue_1574/expected.compressed.css
- spec/libsass-todo-issues/issue_1574/expected.expanded.css
- spec/libsass-todo-issues/issue_1574/expected_output.css
- spec/libsass-todo-issues/issue_1574/input.scss
This PR add specs for sass/libsass#1574
> Add specs for issue 1574

- spec/libsass-todo-issues/issue_1584/expected.compact.css
- spec/libsass-todo-issues/issue_1584/expected.compressed.css
- spec/libsass-todo-issues/issue_1584/expected.expanded.css
- spec/libsass-todo-issues/issue_1584/expected_output.css
- spec/libsass-todo-issues/issue_1584/input.scss
https://github.com/sass/libsass/issues/1584
> Libsass 1584: at-root nesting

- spec/libsass-todo-issues/issue_1578/expected.compact.css
- spec/libsass-todo-issues/issue_1578/expected.compressed.css
- spec/libsass-todo-issues/issue_1578/expected.expanded.css
- spec/libsass-todo-issues/issue_1578/expected_output.css
- spec/libsass-todo-issues/issue_1578/input.sass
This PR add specs for sass/libsass#1578
> Add specs for issue 1578

- spec/libsass-todo-issues/issue_1567/expected.compact.css
- spec/libsass-todo-issues/issue_1567/expected.compressed.css
- spec/libsass-todo-issues/issue_1567/expected.expanded.css
- spec/libsass-todo-issues/issue_1567/expected_output.css
- spec/libsass-todo-issues/issue_1567/input.scss
This PR updates specs for sass/libsass#1567
> Update spec for issue 1567

- spec/libsass-todo-issues/issue_1610/expected.compact.css
- spec/libsass-todo-issues/issue_1610/expected.compressed.css
- spec/libsass-todo-issues/issue_1610/expected.expanded.css
- spec/libsass-todo-issues/issue_1610/expected_output.css
- spec/libsass-todo-issues/issue_1610/input.scss
This PR add specs for sass/libsass#1610
> Add specs for issue 1610

- spec/libsass-closed-issues/issue_1610/expected.compact.css
- spec/libsass-closed-issues/issue_1610/expected.compressed.css
- spec/libsass-closed-issues/issue_1610/expected.expanded.css
- spec/libsass-closed-issues/issue_1610/expected_output.css
- spec/libsass-closed-issues/issue_1610/input.scss
- spec/libsass-todo-issues/issue_1610/expected.compressed.css
This PR activates specs for sass/libsass#1610
> Activate specs for issue 1610

- spec/libsass-todo-issues/issue_1612/expected.compact.css
- spec/libsass-todo-issues/issue_1612/expected.compressed.css
- spec/libsass-todo-issues/issue_1612/expected.expanded.css
- spec/libsass-todo-issues/issue_1612/expected_output.css
- spec/libsass-todo-issues/issue_1612/input.scss
This PR add specs for sass/libsass#1612
> Add specs for issue 1612

- spec/libsass-todo-issues/issue_1624/expected.compact.css
- spec/libsass-todo-issues/issue_1624/expected.compressed.css
- spec/libsass-todo-issues/issue_1624/expected.expanded.css
- spec/libsass-todo-issues/issue_1624/expected_output.css
- spec/libsass-todo-issues/issue_1624/input.scss
This PR add specs for sass/libsass#1624
> Add specs for issue 1624

- spec/libsass-todo-issues/issue_1629/expected.compact.css
- spec/libsass-todo-issues/issue_1629/expected.compressed.css
- spec/libsass-todo-issues/issue_1629/expected.expanded.css
- spec/libsass-todo-issues/issue_1629/expected_output.css
- spec/libsass-todo-issues/issue_1629/input.scss
This PR add specs for sass/libsass#1629
> Add specs for issue 1629

- spec/libsass-closed-issues/issue_1624/expected.compact.css
- spec/libsass-closed-issues/issue_1624/expected.compressed.css
- spec/libsass-closed-issues/issue_1624/expected.expanded.css
- spec/libsass-closed-issues/issue_1624/expected_output.css
- spec/libsass-closed-issues/issue_1624/input.scss
- spec/libsass-todo-issues/issue_1624/expected.compact.css
- spec/libsass-todo-issues/issue_1624/expected.compressed.css
- spec/libsass-todo-issues/issue_1624/expected.expanded.css
- spec/libsass-todo-issues/issue_1624/expected_output.css
- spec/libsass-todo-issues/issue_1624/input.scss
This PR activates specs for sass/libsass#1624
> Activate specs for issue 1624

- spec/libsass-closed-issues/issue_1648/expected.compact.css
- spec/libsass-closed-issues/issue_1648/expected.expanded.css
- spec/libsass-closed-issues/issue_1648/expected_output.css
- spec/libsass-closed-issues/issue_1648/input.scss
Issue: https://github.com/sass/libsass/issues/1648
PR: https://github.com/sass/libsass/pull/1649
> Add spec test for libsass issue 1648

- spec/libsass-closed-issues/issue_1654/basic/expected.compact.css
- spec/libsass-closed-issues/issue_1654/basic/expected.compressed.css
- spec/libsass-closed-issues/issue_1654/basic/expected.expanded.css
- spec/libsass-closed-issues/issue_1654/basic/expected_output.css
- spec/libsass-closed-issues/issue_1654/basic/input.scss
- spec/libsass-closed-issues/issue_1654/bem/expected.compact.css
- spec/libsass-closed-issues/issue_1654/bem/expected.compressed.css
- spec/libsass-closed-issues/issue_1654/bem/expected.expanded.css
- spec/libsass-closed-issues/issue_1654/bem/expected_output.css
- spec/libsass-closed-issues/issue_1654/bem/input.scss
- spec/libsass-closed-issues/issue_1654/nested/expected.compact.css
- spec/libsass-closed-issues/issue_1654/nested/expected.compressed.css
- spec/libsass-closed-issues/issue_1654/nested/expected.expanded.css
- spec/libsass-closed-issues/issue_1654/nested/expected_output.css
- spec/libsass-closed-issues/issue_1654/nested/input.scss
Issue: https://github.com/sass/libsass/issues/1654
> Add tests for libsass issue 1654

- spec/libsass-closed-issues/issue_1681/calc/error
- spec/libsass-closed-issues/issue_1681/calc/input.scss
- spec/libsass-closed-issues/issue_1681/element/error
- spec/libsass-closed-issues/issue_1681/element/input.scss
- spec/libsass-closed-issues/issue_1681/expression/error
- spec/libsass-closed-issues/issue_1681/expression/input.scss
- spec/libsass-closed-issues/issue_1681/url/error
- spec/libsass-closed-issues/issue_1681/url/input.scss
This PR activates specs for sass/libsass#1681
> Activate specs for issue 1681

- spec/libsass-closed-issues/issue_1683/error
- spec/libsass-closed-issues/issue_1683/function/error
- spec/libsass-closed-issues/issue_1683/function/input.scss
- spec/libsass-closed-issues/issue_1683/mixin/error
- spec/libsass-closed-issues/issue_1683/mixin/input.scss
This PR activates specs for sass/libsass#1683
> Activate specs for issue 1683

- spec/libsass-closed-issues/issue_1685/input.scss
This PR activates specs for sass/libsass#1685
> Activate specs for issue 1685

- spec/libsass-closed-issues/issue_1672/expected.compact.css
- spec/libsass-closed-issues/issue_1672/expected.compressed.css
- spec/libsass-closed-issues/issue_1672/expected.expanded.css
- spec/libsass-closed-issues/issue_1672/expected_output.css
- spec/libsass-closed-issues/issue_1672/input.scss
This PR activates specs for sass/libsass#1672
> Activate specs for issue 1672

- spec/libsass-closed-issues/issue_1667/expected.compact.css
- spec/libsass-closed-issues/issue_1667/expected.compressed.css
- spec/libsass-closed-issues/issue_1667/expected.expanded.css
- spec/libsass-closed-issues/issue_1667/expected_output.css
- spec/libsass-closed-issues/issue_1667/input.scss
https://github.com/sass/libsass/issues/1667
> Add spec test for libsass issue 1667

- spec/libsass-todo-issues/issue_1671/expected.compact.css
- spec/libsass-todo-issues/issue_1671/expected.compressed.css
- spec/libsass-todo-issues/issue_1671/expected.expanded.css
- spec/libsass-todo-issues/issue_1671/expected_output.css
- spec/libsass-todo-issues/issue_1671/input.scss
This PR add specs for sass/libsass#1671
> Add specs for issue 1671

- spec/libsass-closed-issues/issue_1673/expected.compact.css
- spec/libsass-closed-issues/issue_1673/expected.compressed.css
- spec/libsass-closed-issues/issue_1673/expected.expanded.css
- spec/libsass-closed-issues/issue_1673/expected_output.css
- spec/libsass-closed-issues/issue_1673/input.scss
This PR activates specs for sass/libsass#1673
> Activate specs for issue 1673

- spec/libsass-closed-issues/issue_1671/expected.compact.css
- spec/libsass-closed-issues/issue_1671/expected.compressed.css
- spec/libsass-closed-issues/issue_1671/expected.expanded.css
- spec/libsass-closed-issues/issue_1671/expected_output.css
- spec/libsass-closed-issues/issue_1671/input.scss
- spec/libsass-todo-issues/issue_1671/expected.compact.css
- spec/libsass-todo-issues/issue_1671/expected.compressed.css
- spec/libsass-todo-issues/issue_1671/expected.expanded.css
- spec/libsass-todo-issues/issue_1671/expected_output.css
- spec/libsass-todo-issues/issue_1671/input.scss
This PR activates specs for sass/libsass#1671
> Activate specs for issue 1671

- spec/misc/todo_import_in_mixin/expected.compact.css
- spec/misc/todo_import_in_mixin/expected.compressed.css
- spec/misc/todo_import_in_mixin/expected.expanded.css
- spec/misc/todo_import_in_mixin/expected_output.css
- spec/misc/todo_import_in_mixin/input.scss
Error: Import directives may not be used within control directives or mixins.
https://github.com/sass/libsass/issues/1724
> Add test for libsass issue #1724

- spec/libsass-closed-issues/issue_1726/expected.compact.css
- spec/libsass-closed-issues/issue_1726/expected.compressed.css
- spec/libsass-closed-issues/issue_1726/expected.expanded.css
- spec/libsass-closed-issues/issue_1726/expected_output.css
- spec/libsass-closed-issues/issue_1726/input.scss
https://github.com/sass/libsass/issues/1726
> Add test for libsass issue #1726

- spec/libsass-todo-issues/issue_1722/expected.compact.css
- spec/libsass-todo-issues/issue_1722/expected.compressed.css
- spec/libsass-todo-issues/issue_1722/expected.expanded.css
- spec/libsass-todo-issues/issue_1722/expected_output.css
- spec/libsass-todo-issues/issue_1722/input.scss
White space error after interpolation
https://github.com/sass/libsass/issues/1722
> Add test for libsass issue #1722

- spec/libsass-todo-issues/issue_1729/expected.compact.css
- spec/libsass-todo-issues/issue_1729/expected.compressed.css
- spec/libsass-todo-issues/issue_1729/expected.expanded.css
- spec/libsass-todo-issues/issue_1729/expected_output.css
- spec/libsass-todo-issues/issue_1729/input.scss
https://github.com/sass/libsass/issues/1729
> Add spec for libsass issue #1729

- spec/libsass-todo-issues/issue_1709/expected.compact.css
- spec/libsass-todo-issues/issue_1709/expected.compressed.css
- spec/libsass-todo-issues/issue_1709/expected.expanded.css
- spec/libsass-todo-issues/issue_1709/expected_output.css
- spec/libsass-todo-issues/issue_1709/input.scss
- spec/libsass-todo-issues/issue_1717/expected_output.css
- spec/libsass-todo-issues/issue_1717/input.scss
https://github.com/sass/libsass/issues/1709
> Add test for libsass issue #1709

- spec/libsass-closed-issues/issue_1710/expected.compact.css
- spec/libsass-closed-issues/issue_1710/expected.compressed.css
- spec/libsass-closed-issues/issue_1710/expected.expanded.css
- spec/libsass-closed-issues/issue_1710/expected_output.css
- spec/libsass-closed-issues/issue_1710/input.scss
https://github.com/sass/sass/issues/1886
https://github.com/sass/libsass/issues/1710
> Add test for libsass issue #1710

- spec/libsass-todo-issues/issue_1706/error
- spec/libsass-todo-issues/issue_1706/expected.compact.css
- spec/libsass-todo-issues/issue_1706/expected.compressed.css
- spec/libsass-todo-issues/issue_1706/expected.expanded.css
- spec/libsass-todo-issues/issue_1706/expected_output.css
- spec/libsass-todo-issues/issue_1706/input.scss
https://github.com/sass/libsass/issues/1706
> Add test for libsass issue #1706

- spec/libsass-todo-issues/issue_1768/error
- spec/libsass-todo-issues/issue_1768/input.scss
This PR add specs for sass/libsass#1768
> Add specs for issue 1768

- spec/libsass-todo-issues/issue_1766/expected.compact.css
- spec/libsass-todo-issues/issue_1766/expected.compressed.css
- spec/libsass-todo-issues/issue_1766/expected.expanded.css
- spec/libsass-todo-issues/issue_1766/expected_output.css
- spec/libsass-todo-issues/issue_1766/foo.scss
- spec/libsass-todo-issues/issue_1766/input.scss
This PR add specs for sass/libsass#1766
> Add specs for issue 1766

- spec/libsass-todo-issues/issue_1583/expected.compact.css
- spec/libsass-todo-issues/issue_1583/expected.compressed.css
- spec/libsass-todo-issues/issue_1583/expected.expanded.css
- spec/libsass-todo-issues/issue_1583/expected_output.css
- spec/libsass-todo-issues/issue_1583/input.scss
Updated spec for https://github.com/sass/libsass/issues/1583 based on https://github.com/sass/libsass/issues/1583#issuecomment-160963685
> Update spec for issue 1583

- spec/libsass-todo-issues/issue_1757/each/expected.compact.css
- spec/libsass-todo-issues/issue_1757/each/expected.compressed.css
- spec/libsass-todo-issues/issue_1757/each/expected.expanded.css
- spec/libsass-todo-issues/issue_1757/each/expected_output.css
- spec/libsass-todo-issues/issue_1757/each/input.scss
- spec/libsass-todo-issues/issue_1757/for/expected.compact.css
- spec/libsass-todo-issues/issue_1757/for/expected.compressed.css
- spec/libsass-todo-issues/issue_1757/for/expected.expanded.css
- spec/libsass-todo-issues/issue_1757/for/expected_output.css
- spec/libsass-todo-issues/issue_1757/for/input.scss
This PR add specs for sass/libsass#1757
> Add specs for issue 1757

- spec/libsass-todo-issues/issue_1770/expected.compact.css
- spec/libsass-todo-issues/issue_1770/expected.compressed.css
- spec/libsass-todo-issues/issue_1770/expected.expanded.css
- spec/libsass-todo-issues/issue_1770/expected_output.css
- spec/libsass-todo-issues/issue_1770/input.scss
This PR add specs for sass/libsass#1770
> Add specs for issue 1770

- spec/libsass-todo-issues/issue_1647/directives/expected.compact.css
- spec/libsass-todo-issues/issue_1647/directives/expected.compressed.css
- spec/libsass-todo-issues/issue_1647/directives/expected.expanded.css
- spec/libsass-todo-issues/issue_1647/directives/expected_output.css
- spec/libsass-todo-issues/issue_1647/directives/input.scss
- spec/libsass-todo-issues/issue_1647/selectors/expected.compact.css
- spec/libsass-todo-issues/issue_1647/selectors/expected.compressed.css
- spec/libsass-todo-issues/issue_1647/selectors/expected.expanded.css
- spec/libsass-todo-issues/issue_1647/selectors/expected_output.css
- spec/libsass-todo-issues/issue_1647/selectors/input.scss
This PR add specs for sass/libsass#1647
> Add specs for issue 1647

- spec/libsass-todo-issues/issue_1792/expected.compact.css
- spec/libsass-todo-issues/issue_1792/expected.compressed.css
- spec/libsass-todo-issues/issue_1792/expected.expanded.css
- spec/libsass-todo-issues/issue_1792/expected_output.css
- spec/libsass-todo-issues/issue_1792/input.scss
This PR add specs for sass/libsass#1792
> Add specs for issue 1792

- spec/libsass-todo-issues/issue_1794/expected.compact.css
- spec/libsass-todo-issues/issue_1794/expected.compressed.css
- spec/libsass-todo-issues/issue_1794/expected.expanded.css
- spec/libsass-todo-issues/issue_1794/expected_output.css
- spec/libsass-todo-issues/issue_1794/input.scss
This PR add specs for sass/libsass#1794
> Add specs for issue 1794

- spec/libsass-closed-issues/issue_1096/input.scss
This is to test sass/libsass#1817.
//cc @xzyfer
> spec: Modifies 1096 input with CRLF

- spec/libsass-todo-issues/issue_1819/expected.compact.css
- spec/libsass-todo-issues/issue_1819/expected.compressed.css
- spec/libsass-todo-issues/issue_1819/expected.expanded.css
- spec/libsass-todo-issues/issue_1819/expected_output.css
- spec/libsass-todo-issues/issue_1819/input.scss
This PR add specs for sass/libsass#1819
> Add specs for issue 1819

- spec/libsass-todo-issues/issue_1825/expected.compact.css
- spec/libsass-todo-issues/issue_1825/expected.compressed.css
- spec/libsass-todo-issues/issue_1825/expected.expanded.css
- spec/libsass-todo-issues/issue_1825/expected_output.css
- spec/libsass-todo-issues/issue_1825/input.scss
This PR add specs for sass/libsass#1825
> Add specs for issue 1825

- spec/libsass-todo-issues/issue_1650/negative/expected.compact.css
- spec/libsass-todo-issues/issue_1650/negative/expected.compressed.css
- spec/libsass-todo-issues/issue_1650/negative/expected.expanded.css
- spec/libsass-todo-issues/issue_1650/negative/expected_output.css
- spec/libsass-todo-issues/issue_1650/negative/input.scss
- spec/libsass-todo-issues/issue_1650/positive/expected.compact.css
- spec/libsass-todo-issues/issue_1650/positive/expected.compressed.css
- spec/libsass-todo-issues/issue_1650/positive/expected.expanded.css
- spec/libsass-todo-issues/issue_1650/positive/expected_output.css
- spec/libsass-todo-issues/issue_1650/positive/input.scss
Issue: https://github.com/sass/libsass/issues/1650
PR: https://github.com/sass/libsass/pull/1652
> Add spec test for libsass issue 1650

- spec/libsass-closed-issues/issue_1752/error
- spec/libsass-closed-issues/issue_1752/input.scss
This PR activates specs for sass/libsass#1752
> Activate specs for issue 1752

- spec/libsass-closed-issues/issue_1797/expected.compact.css
- spec/libsass-closed-issues/issue_1797/expected.compressed.css
- spec/libsass-closed-issues/issue_1797/expected.expanded.css
- spec/libsass-closed-issues/issue_1797/expected_output.css
- spec/libsass-closed-issues/issue_1797/input.scss
This PR activates specs for sass/libsass#1797
> Activate specs for issue 1797

- spec/libsass-todo-issues/issue_1096/error
- spec/libsass-todo-tests/extend-tests/200_test_extend_with_subject_transfers_subject_to_extender/error
- spec/libsass-todo-tests/extend-tests/201_test_extend_with_subject_transfers_subject_to_extender/error
- spec/libsass-todo-tests/extend-tests/202_test_extend_with_subject_retains_subject_on_target/error
- spec/libsass-todo-tests/extend-tests/203_test_extend_with_subject_transfers_subject_to_target/error
- spec/libsass-todo-tests/extend-tests/204_test_extend_with_subject_retains_subject_on_extender/error
- spec/libsass-todo-tests/extend-tests/205_test_extend_with_subject_fails_with_conflicting_subject/error
- spec/libsass-todo-tests/scss-tests/046_test_parent_selector_with_subject/error
They weren't re-generated by ruby sass nuke!
> Add some missing deprecation warnings

- spec/libsass-closed-issues/issue_1741/expected.compact.css
- spec/libsass-closed-issues/issue_1741/expected.compressed.css
- spec/libsass-closed-issues/issue_1741/expected.expanded.css
- spec/libsass-closed-issues/issue_1741/expected_output.css
- spec/libsass-closed-issues/issue_1741/input.scss
https://github.com/sass/libsass/issues/1741
> Add spec test for libsass issue 1741

- spec/libsass-todo-issues/issue_1812/expected.compact.css
- spec/libsass-todo-issues/issue_1812/expected.compressed.css
- spec/libsass-todo-issues/issue_1812/expected.expanded.css
- spec/libsass-todo-issues/issue_1812/expected_output.css
- spec/libsass-todo-issues/issue_1812/input.scss
Issue: https://github.com/sass/libsass/issues/1812
> Add specs for libsass issue 1812

- spec/libsass-todo-issues/issue_1796/expected.compact.css
- spec/libsass-todo-issues/issue_1796/expected.compressed.css
- spec/libsass-todo-issues/issue_1796/expected.expanded.css
- spec/libsass-todo-issues/issue_1796/expected_output.css
- spec/libsass-todo-issues/issue_1796/input.scss
https://github.com/sass/libsass/issues/1796
> Add todo spec test for libsass issue 1796

- spec/libsass-todo-issues/issue_1839/expected.compact.css
- spec/libsass-todo-issues/issue_1839/expected.compressed.css
- spec/libsass-todo-issues/issue_1839/expected.expanded.css
- spec/libsass-todo-issues/issue_1839/expected_output.css
- spec/libsass-todo-issues/issue_1839/input.scss
https://github.com/sass/libsass/issues/1839
> Add spec for libsass issue 1839

- spec/libsass-todo-issues/issue_1886/expected.compact.css
- spec/libsass-todo-issues/issue_1886/expected.compressed.css
- spec/libsass-todo-issues/issue_1886/expected.expanded.css
- spec/libsass-todo-issues/issue_1886/expected_output.css
- spec/libsass-todo-issues/issue_1886/input.scss
This PR add specs for sass/libsass#1886
> Add specs for issue 1886

- spec/libsass-todo-issues/issue_1915/expected.compact.css
- spec/libsass-todo-issues/issue_1915/expected.compressed.css
- spec/libsass-todo-issues/issue_1915/expected.expanded.css
- spec/libsass-todo-issues/issue_1915/expected_output.css
- spec/libsass-todo-issues/issue_1915/input.scss
This PR add specs for sass/libsass#1915
> Add specs for issue 1915

- spec/libsass-todo-issues/issue_1944/expected.compact.css
- spec/libsass-todo-issues/issue_1944/expected.compressed.css
- spec/libsass-todo-issues/issue_1944/expected.expanded.css
- spec/libsass-todo-issues/issue_1944/expected_output.css
- spec/libsass-todo-issues/issue_1944/input.scss
> Add specs for sass/libsass#1944

- spec/libsass-closed-issues/issue_1971/expected.compact.css
- spec/libsass-closed-issues/issue_1971/expected.compressed.css
- spec/libsass-closed-issues/issue_1971/expected.expanded.css
- spec/libsass-closed-issues/issue_1971/expected_output.css
- spec/libsass-closed-issues/issue_1971/input.scss
This PR activates specs for sass/libsass#1971
> Activate specs for issue 1971

- spec/libsass-closed-issues/issue_1991/input.scss
- spec/libsass-closed-issues/issue_1996/input.scss
https://github.com/sass/libsass/issues/1991 and https://github.com/sass/libsass/issues/1996
> Spec tests for libsass issue 1991 & 1996

- spec/libsass-closed-issues/issue_1927/expected_output.css
- spec/libsass-closed-issues/issue_1927/input.scss
https://github.com/sass/libsass/issues/1927
> Add and activate spec test for libsass issue 1927

- spec/libsass-closed-issues/issue_1994/expected_output.css
- spec/libsass-closed-issues/issue_1994/input.scss
- spec/libsass-closed-issues/issue_2000/expected_output.css
- spec/libsass-closed-issues/issue_2000/input.scss
https://github.com/sass/libsass/issues/2000 (and already passing https://github.com/sass/libsass/issues/1994)
> Activate spec test for libsass issue 2000

- spec/libsass-todo-issues/issue_2007/expected_output.css
- spec/libsass-todo-issues/issue_2007/input.scss
This PR add specs for sass/libsass#2007
> Add specs for issue 2007

- spec/libsass-todo-issues/issue_2009/expected_output.css
- spec/libsass-todo-issues/issue_2009/input.scss
This PR add specs for sass/libsass#2009
> Add specs for issue 2009

- spec/libsass-todo-issues/issue_91/expected_output.css
- spec/libsass-todo-issues/issue_91/input.scss
https://github.com/sass/libsass/issues/91
> Add todo spec test for libsass issue 91

- spec/libsass-todo-issues/issue_100/expected_output.css
- spec/libsass-todo-issues/issue_100/input.scss
https://github.com/sass/libsass/issues/100
> Add todo spec test for libsass issue 100

- spec/libsass-todo-issues/issue_103/input.scss
https://github.com/sass/libsass/issues/103
> Add todo spec test for libsass issue 103

- spec/libsass-todo-issues/issue_112/expected_output.css
- spec/libsass-todo-issues/issue_112/input.scss
https://github.com/sass/libsass/issues/112
> Add todo spec test for libsass issue 112

- spec/libsass-todo-issues/issue_167/expected_output.css
- spec/libsass-todo-issues/issue_167/input.scss
https://github.com/sass/libsass/issues/167
> Add todo spec test for libsass issue 167

- spec/libsass-todo-issues/issue_201/expected_output.css
- spec/libsass-todo-issues/issue_201/input.scss
https://github.com/sass/libsass/issues/201
> Add todo spec test for libsass issue 201

- spec/libsass-todo-issues/issue_2031/expected_output.css
- spec/libsass-todo-issues/issue_2031/input.scss
https://github.com/sass/libsass/issues/2031
> Add todo spec test for libsass issue 2031

- spec/libsass-todo-issues/issue_267/expected_output.css
- spec/libsass-todo-issues/issue_267/input.scss
https://github.com/sass/libsass/issues/267
> Add todo spec test for libsass issue 267

- spec/libsass-todo-issues/issue_246/expected_output.css
- spec/libsass-todo-issues/issue_246/input.scss
https://github.com/sass/libsass/issues/246
> Add todo spec test for libsass issue 246

- spec/libsass-todo-issues/issue_73/input.scss
https://github.com/sass/libsass/issues/73
> Add todo spec test for libsass issue 73

- spec/libsass-todo-issues/issue_274/expected_output.css
- spec/libsass-todo-issues/issue_274/input.scss
https://github.com/sass/libsass/issues/274
> Add todo spec test for libsass issue 274

- spec/libsass-todo-issues/issue_289/expected_output.css
- spec/libsass-todo-issues/issue_289/input.scss
https://github.com/sass/libsass/issues/289
> Add todo spec test for libsass issue 289

- spec/libsass-todo-issues/issue_309/expected_output.css
- spec/libsass-todo-issues/issue_309/input.scss
https://github.com/sass/libsass/issues/309
> Add todo spec test for libsass issue 309

- spec/libsass-todo-issues/issue_54/expected_output.css
- spec/libsass-todo-issues/issue_54/input.scss
https://github.com/sass/libsass/issues/54
> Add todo spec test for libsass issue 54

- spec/libsass-todo-issues/issue_87/expected_output.css
- spec/libsass-todo-issues/issue_87/input.scss
https://github.com/sass/libsass/issues/87
> Add todo spec test for libsass issue 87

- spec/libsass-todo-issues/issue_86/expected_output.css
- spec/libsass-todo-issues/issue_86/input.scss
https://github.com/sass/libsass/issues/86
> Add todo spec test for libsass issue 86

- spec/libsass-todo-issues/issue_77/expected_output.css
- spec/libsass-todo-issues/issue_77/input.scss
https://github.com/sass/libsass/issues/77
> Add todo spec test for libsass issue 77

- spec/libsass-todo-issues/issue_72/expected_output.css
- spec/libsass-todo-issues/issue_72/input.scss
https://github.com/sass/libsass/issues/72
> Add todo spec test for libsass issue 72

- spec/libsass-todo-issues/issue_70/expected_output.css
- spec/libsass-todo-issues/issue_70/input.scss
https://github.com/sass/libsass/issues/70
> Add todo spec test for libsass issue 70

- spec/libsass-todo-issues/issue_56/expected_output.css
- spec/libsass-todo-issues/issue_56/input.scss
https://github.com/sass/libsass/issues/56
> Add todo spec test for libsass issue 56

- spec/libsass-todo-issues/issue_63/expected_output.css
- spec/libsass-todo-issues/issue_63/input.scss
https://github.com/sass/libsass/issues/63
> Add todo spec test for libsass issue 63

- spec/libsass-todo-issues/issue_6/expected_output.css
- spec/libsass-todo-issues/issue_6/input.scss
https://github.com/sass/libsass/issues/6
> Add todo spec test for libsass issue 6

- spec/libsass-todo-issues/issue_59/expected_output.css
- spec/libsass-todo-issues/issue_59/input.scss
https://github.com/sass/libsass/issues/59
> Add todo spec test for libsass issue 59

- spec/libsass-todo-issues/issue_58/expected_output.css
- spec/libsass-todo-issues/issue_58/input.scss
https://github.com/sass/libsass/issues/58
> Add todo spec test for libsass issue 58

- spec/libsass-todo-issues/issue_558/expected_output.css
- spec/libsass-todo-issues/issue_558/input.scss
https://github.com/sass/libsass/issues/558
> Add todo spec test for libsass issue 558

- spec/libsass-todo-issues/issue_435/expected_output.css
- spec/libsass-todo-issues/issue_435/input.scss
https://github.com/sass/libsass/issues/435
> Add todo spec test for libsass issue 435

- spec/libsass-todo-issues/issue_424/expected_output.css
- spec/libsass-todo-issues/issue_424/input.scss
https://github.com/sass/libsass/issues/424
> Add todo spec test for libsass issue 424

- spec/libsass-todo-issues/issue_312/expected_output.css
- spec/libsass-todo-issues/issue_312/input.scss
https://github.com/sass/libsass/issues/312
> Add todo spec test for libsass issue 312

- spec/libsass-todo-issues/issue_257/expected_output.css
- spec/libsass-todo-issues/issue_257/input.scss
https://github.com/sass/libsass/issues/257
> Add todo spec test for libsass issue 257

- spec/libsass-todo-issues/issue_254/expected_output.css
- spec/libsass-todo-issues/issue_254/input.scss
https://github.com/sass/libsass/issues/254
> Add todo spec test for libsass issue 254

- spec/libsass-todo-issues/issue_239/expected_output.css
- spec/libsass-todo-issues/issue_239/input.scss
https://github.com/sass/libsass/issues/239
> Add todo spec test for libsass issue 239

- spec/libsass-todo-issues/issue_231/expected_output.css
- spec/libsass-todo-issues/issue_231/input.scss
https://github.com/sass/libsass/issues/231
> Add todo spec test for libsass issue 231

- spec/libsass-todo-issues/issue_2020/expected_output.css
- spec/libsass-todo-issues/issue_2020/input.scss
https://github.com/sass/libsass/issues/2020
> Add todo spec test for libsass issue 2020

- spec/libsass-todo-issues/issue_2017/expected_output.css
- spec/libsass-todo-issues/issue_2017/input.scss
https://github.com/sass/libsass/issues/2017
> Add todo spec test for libsass issue 2017

- spec/libsass-todo-issues/issue_1940/expected_output.css
- spec/libsass-todo-issues/issue_1940/input.scss
https://github.com/sass/libsass/issues/1940
> Add todo spec test for libsass issue 1940

- spec/libsass-todo-issues/issue_192/error
- spec/libsass-todo-issues/issue_192/expected_output.css
- spec/libsass-todo-issues/issue_192/input.scss
https://github.com/sass/libsass/issues/192
> Add todo spec test for libsass issue 192

- spec/libsass-todo-issues/issue_154/expected_output.css
- spec/libsass-todo-issues/issue_154/input.scss
https://github.com/sass/libsass/issues/154
> Add todo spec test for libsass issue 154

- spec/libsass-todo-issues/issue_131/expected_output.css
- spec/libsass-todo-issues/issue_131/input.scss
https://github.com/sass/libsass/issues/131
> Add todo spec test for libsass issue 131

- spec/libsass-todo-issues/issue_108/expected_output.css
- spec/libsass-todo-issues/issue_108/input.scss
https://github.com/sass/libsass/issues/108
> Add todo spec test for libsass issue 108

- lib/sass_spec/cli.rb
- lib/sass_spec/runner.rb
- lib/sass_spec/test.rb
- lib/sass_spec/test_case.rb
Fixes https://github.com/sass/sass-spec/issues/600
> Add mode to probe for passing todo tests

- spec/output_styles/compact/libsass/Sáss-UŢF8/expected_output.css
- spec/output_styles/compact/libsass/Sáss-UŢF8/input.scss
- spec/output_styles/compressed/libsass/Sáss-UŢF8/expected_output.css
- spec/output_styles/compressed/libsass/Sáss-UŢF8/input.scss
- spec/output_styles/expanded/libsass/Sáss-UŢF8/expected_output.css
- spec/output_styles/expanded/libsass/Sáss-UŢF8/input.scss
I'm adding these because OSX can't seem to handle them and wont
let me delete the files even though they've been deleted from git.
As a result my tree is always dirty and rapidly driving me crazy.
> Re-add weird unicode specs

- spec/libsass-todo-issues/issue_2054/expected_output.css
- spec/libsass-todo-issues/issue_2054/input.scss
- tools/gen_libsass_todo.cmd
https://github.com/sass/libsass/issues/2054
> Add todo spec test for libsass issue 2054

- spec/libsass-todo-issues/issue_2042/expected_output.css
- spec/libsass-todo-issues/issue_2042/input.scss
https://github.com/sass/libsass/issues/2042
> Add todo spec test for libsass issue 2042

- spec/libsass-todo-issues/issue_2034/expected_output.css
- spec/libsass-todo-issues/issue_2034/input.scss
https://github.com/sass/libsass/issues/2034
> Add todo spec test for libsass issue 2034

- spec/libsass-todo-issues/issue_2057/expected_output.css
- spec/libsass-todo-issues/issue_2057/input.scss
https://github.com/sass/libsass/issues/2057
> Add todo spec test for libsass issue 2057

- spec/libsass-todo-issues/issue_2074/expected_output.css
- spec/libsass-todo-issues/issue_2074/input.scss
https://github.com/sass/libsass/issues/2074
> Add todo spec test for libsass issue 2074

- spec/libsass-closed-issues/issue_1596/expected_output.css
- spec/libsass-closed-issues/issue_1596/input.scss
This PR activates specs for sass/libsass#1596
> Activate specs for issue 1596

- spec/libsass-todo-issues/issue_2112/expected_output.css
- spec/libsass-todo-issues/issue_2112/input.scss
https://github.com/sass/libsass/issues/2112
> Add todo spec test for libsass issue 2112

- spec/libsass-todo-issues/issue_2116/expected_output.css
- spec/libsass-todo-issues/issue_2116/input.scss
This PR add specs for sass/libsass#2116
> Add specs for issue 2116

- spec/libsass-todo-issues/issue_2120/expected_output.css
- spec/libsass-todo-issues/issue_2120/input.scss
https://github.com/sass/libsass/issues/2120
> Add todo spec test for libsass issue 2120

- spec/libsass-todo-issues/issue_2123/expected_output.css
- spec/libsass-todo-issues/issue_2123/input.scss
https://github.com/sass/libsass/issues/2123
> Add todo spec test for libsass issue 2123

- spec/libsass-todo-issues/issue_2124/expected_output.css
- spec/libsass-todo-issues/issue_2124/input.scss
https://github.com/sass/libsass/issues/2124
> Add todo spec test for libsass issue 2124

- spec/libsass-todo-issues/issue_2132/expected_output.css
- spec/libsass-todo-issues/issue_2132/input.scss
https://github.com/sass/libsass/issues/2132
> Add todo spec test for libsass issue 2132

- spec/libsass-closed-issues/47_str_slice/expected_output.css
- spec/libsass-closed-issues/47_str_slice/input.scss
Tests an edgecase found by @danez here:
https://github.com/sass/libsass/issues/2132
> Test Single Character str-slice

- spec/libsass-todo-issues/issue_2139/expected_output.css
- spec/libsass-todo-issues/issue_2139/input.scss
This PR add specs for sass/libsass#2139
> Add specs for issue 2139

- spec/libsass-todo-issues/issue_2140/expected_output.css
- spec/libsass-todo-issues/issue_2140/input.scss
This PR add specs for sass/libsass#2140
> Add specs for issue 2140

- spec/libsass-todo-issues/issue_2154/expected_output.css
- spec/libsass-todo-issues/issue_2154/input.scss
This PR add specs for sass/libsass#2154
> Add specs for issue 2154

- spec/libsass-todo-issues/issue_2150/expected_output.css
- spec/libsass-todo-issues/issue_2150/input.scss
This PR add specs for sass/libsass#2150
> Add specs for issue 2150

- spec/libsass-todo-issues/issue_2158/expected_output.css
- spec/libsass-todo-issues/issue_2158/input.scss
https://github.com/sass/libsass/issues/2158
> Add todo spec test for libsass issue 2158

- spec/libsass-todo-issues/issue_2169/expected_output.css
- spec/libsass-todo-issues/issue_2169/input.scss
https://github.com/sass/libsass/issues/2169
> Add todo spec test for libsass issue 2169

- spec/libsass-todo-issues/issue_2149/expected_output.css
- spec/libsass-todo-issues/issue_2149/input.scss
This PR add specs for sass/libsass#2149
> Add specs for issue 2149

- spec/libsass-todo-issues/issue_2096/expected_output.css
- spec/libsass-todo-issues/issue_2096/input.scss
This PR add specs for sass/libsass#2096
> Add specs for issue 2096

- spec/libsass-todo-issues/issue_2095/input.scss
This PR add specs for sass/libsass#2095
> Add specs for issue 2095

- spec/libsass-todo-issues/issue_2055/expected_output.css
- spec/libsass-todo-issues/issue_2055/input.scss
This PR add specs for sass/libsass#2055
> Add specs for issue 2055

- spec/sass/bem/expected_output.css
- spec/sass/bem/input.sass
- spec/sass/extend/expected_output.css
- spec/sass/extend/input.sass
- spec/sass/functions/expected_output.css
- spec/sass/functions/input.sass
- spec/sass/mixins/expected_output.css
- spec/sass/mixins/input.sass
- spec/sass/pseudo/expected_output.css
- spec/sass/pseudo/input.sass
- spec/sass/selectors/expected_output.css
- spec/sass/selectors/input.sass
Add additional indented sass spec tests
> Add more sass spec tests

- spec/libsass-todo-issues/issue_1781/expected_output.css
- spec/libsass-todo-issues/issue_1781/input.sass
https://github.com/sass/libsass/issues/1781
> Add todo spec test for libsass issue 1781

- spec/libsass-todo-issues/issue_2185/expected_output.css
- spec/libsass-todo-issues/issue_2185/input.scss
https://github.com/sass/libsass/issues/2185
> Add todo spec test for libsass issue 2185

- spec/libsass-todo-issues/issue_2198/expected_output.css
- spec/libsass-todo-issues/issue_2198/input.scss
This PR add specs for sass/libsass#2198
> Add specs for issue 2198

- spec/libsass-todo-issues/issue_2200/expected_output.css
- spec/libsass-todo-issues/issue_2200/input.scss
This PR add specs for sass/libsass#2200
> Add specs for issue 2200

- spec/libsass-todo-issues/issue_2202/expected_output.css
- spec/libsass-todo-issues/issue_2202/input.scss
https://github.com/sass/libsass/issues/2202
> Add todo spec test for libsass issue 2202

- spec/libsass-todo-issues/issue_2205/expected_output.css
- spec/libsass-todo-issues/issue_2205/input.scss
https://github.com/sass/libsass/issues/2205
> Add todo spec test for libsass issue 2205

- lib/sass_spec/cli.rb
- lib/sass_spec/test.rb
- lib/sass_spec/test_case.rb
- lib/sass_spec/test_case_metadata.rb
> Add an :only_on: annotation.

- lib/sass_spec/interactor.rb
- lib/sass_spec/test.rb
> Select interactive options using letters.

- spec/sass_3_5/bracket_lists/options.yml
- spec/sass_3_5/functions/is_bracketed/options.yml
- spec/sass_3_5/functions/join/valid/options.yml
This enables bracketed list tests.
> Un-mark tests as TODO for Dart Sass.

- .travis.yml
When we start shipping 3.5 betas the 3.5 target will become master
> Run sass-spec against LibSass master until 3.4 is stable

- spec/libsass-todo-issues/issue_2235/empty/expected_output.css
- spec/libsass-todo-issues/issue_2235/empty/input.scss
- spec/libsass-todo-issues/issue_2235/not-empty/expected_output.css
- spec/libsass-todo-issues/issue_2235/not-empty/input.scss
This PR add specs for sass/libsass#2235
> Add specs for issue 2235

- spec/css/unknown_directive/expected_output.css
- spec/css/unknown_directive/input.scss
- spec/css/unknown_directive/options.yml
> Add a spec for unknown directive values.

- spec/libsass/units/conversion/resolution/options.yml
- spec/output_styles/compact/libsass/units/conversion/resolution/options.yml
- spec/output_styles/nested/libsass/units/conversion/resolution/options.yml
LibSass needs https://github.com/sass/sass-spec/pull/999 merged
> Mark dps conversion specs as todos for ruby-sass and dart-sass

- spec/libsass-todo-issues/issue_2246/expected_output.css
- spec/libsass-todo-issues/issue_2246/input.scss
- spec/libsass-todo-issues/issue_2246/options.yml
https://github.com/sass/libsass/issues/2246
> Add todo spec test for libsass issue 2246

- lib/sass_spec/test.rb
Seems this functionality got broken at some point.
> Fixes probe-todo mode

- spec/libsass-closed-issues/47_str_slice/options.yml
- spec/output_styles/compact/libsass-closed-issues/47_str_slice/options.yml
- spec/output_styles/compressed/libsass-closed-issues/47_str_slice/options.yml
- spec/output_styles/nested/libsass-closed-issues/47_str_slice/options.yml
> Remove str-slice todos for LibSass

- spec/libsass-todo-issues/issue_2261/expected_output.css
- spec/libsass-todo-issues/issue_2261/input.scss
https://github.com/sass/libsass/issues/2261
> Add todo spec test for libsass issue 2261

- spec/libsass-todo-issues/issue_2243/sass/expected_output.css
- spec/libsass-todo-issues/issue_2243/sass/input.sass
- spec/libsass-todo-issues/issue_2243/scss/expected_output.css
- spec/libsass-todo-issues/issue_2243/scss/input.scss
- spec/libsass-todo-issues/issue_2243/scss/options.yml
https://github.com/sass/libsass/issues/2243
> Add todo spec test for libsass issue 2243

- spec/sass_3_5/functions/invert/weight-parameter/options.yml
https://github.com/sass/libsass/pull/2273
> Activate 3.5 invert with weight for LibSass

- spec/sass_3_5/bracket_lists/options.yml
- spec/sass_3_5/functions/is_bracketed/options.yml
- spec/sass_3_5/functions/join/valid/options.yml
See https://github.com/sass/libsass/pull/2279
Closes #918
> Activate 3.5 bracketed lists for LibSass

- .travis.yml
- tools/skipped-for-impl.sh
> Travis improvements.

- tools/skipped-for-impl.sh
> Fix impl-skipping logic.

- spec/libsass-closed-issues/issue_2289/expected_output.css
- spec/libsass-closed-issues/issue_2289/input.scss
This PR activates specs for sass/libsass#2289
Skip libsass
> Activate specs for issue 2289

- spec/errors/fn-adjust-color-1/options.yml
- spec/errors/fn-change-color-1/options.yml
- spec/errors/fn-random-1/options.yml
- spec/errors/fn-random-2/options.yml
- spec/errors/for-incompatible-units-fn/options.yml
This is just #1047 rebased on master
Closes #1047
> Active some passing specs

- spec/libsass-todo-issues/issue_2291/expected_output.css
- spec/libsass-todo-issues/issue_2291/input.scss
- spec/libsass-todo-issues/issue_2291/options.yml
https://github.com/sass/libsass/issues/2291
> Add todo spec test for libsass issue 2291

- spec/libsass-closed-issues/issue_1923/error-dart-sass
- spec/libsass-closed-issues/issue_1923/options.yml
- spec/libsass-closed-issues/issue_673/error-dart-sass
- spec/libsass-closed-issues/issue_673/options.yml
- spec/libsass-closed-issues/issue_712/error-dart-sass
- spec/libsass-closed-issues/issue_712/options.yml
- spec/libsass/propsets/error-dart-sass
- spec/libsass/propsets/options.yml
> Test cross-media extends on Dart Sass.

- spec/libsass-todo-issues/issue_2309/expected_output.css
- spec/libsass-todo-issues/issue_2309/input.scss
- spec/libsass-todo-issues/issue_2309/options.yml
https://github.com/sass/libsass/issues/2309
> Add todo spec test for libsass issue 2309

- spec/errors/fn-varargs/multiple/error-dart-sass
- spec/errors/fn-varargs/multiple/options.yml
- spec/errors/invalid-operation/gte/error-dart-sass
- spec/errors/invalid-operation/gte/options.yml
- spec/errors/invalid-operation/plus/error-dart-sass
- spec/errors/invalid-operation/plus/options.yml
- spec/errors/invalid-operation/sub/error-dart-sass
- spec/errors/invalid-operation/sub/options.yml
- spec/extend-tests/026_test_universal_unification_with_namespaceless_universal_target/options.yml
- spec/extend-tests/035_test_universal_unification_with_namespaceless_element_target/options.yml
- spec/extend-tests/048_test_element_unification_with_namespaceless_universal_target/options.yml
- spec/extend-tests/057_test_element_unification_with_namespaceless_element_target/options.yml
- spec/extend-tests/139_test_combinator_unification_for_hacky_combinators/options.yml
- spec/extend-tests/234_test_extend_cross_branch_redundancy_elimination/expected_output-dart-sass.css
- spec/extend-tests/234_test_extend_cross_branch_redundancy_elimination/options.yml
- spec/libsass-closed-issues/issue_1550/each_embedded/error-dart-sass
- spec/libsass-closed-issues/issue_1550/each_embedded/options.yml
- spec/libsass-closed-issues/issue_2147/lhs/error-dart-sass
- spec/libsass-closed-issues/issue_2147/lhs/options.yml
- spec/libsass-closed-issues/issue_439/options.yml
- spec/selector-functions/is_superselector/any_is_not_superselector_of_different_prefix/options.yml
- spec/selector-functions/unify/universal_simple/options.yml
> Further Dart Sass fixes.

- spec/libsass-todo-issues/issue_2333/expected_output.css
- spec/libsass-todo-issues/issue_2333/input.scss
https://github.com/sass/libsass/issues/2333
> Add todo spec test for libsass issue 2333

- spec/libsass-todo-issues/issue_2341/expected_output.css
- spec/libsass-todo-issues/issue_2341/input.scss
https://github.com/sass/libsass/issues/2341
> Add todo spec test for libsass issue 2341

- spec/libsass-todo-issues/issue_2347/expected_output.css
- spec/libsass-todo-issues/issue_2347/input.scss
https://github.com/sass/libsass/issues/2347
> Add todo spec test for libsass issue 2347

- spec/libsass-todo-issues/issue_2349/expected_output.css
- spec/libsass-todo-issues/issue_2349/input.scss
https://github.com/sass/libsass/issues/2349
> Add todo spec test for libsass issue 2349

- spec/libsass-todo-issues/issue_2346/expected_output.css
- spec/libsass-todo-issues/issue_2346/input.scss
https://github.com/sass/libsass/issues/2346
> Add todo spec test for libsass issue 2346

- spec/libsass-todo-issues/issue_2320/expected_output.css
- spec/libsass-todo-issues/issue_2320/input.scss
https://github.com/sass/libsass/issues/2320
> Add todo spec test for libsass issue 2320

- spec/sass_3_5/functions/content-exists/basic/options.yml
- spec/sass_3_5/functions/content-exists/errors/inside-function/options.yml
- spec/sass_3_5/functions/content-exists/errors/outside-of-mixin/options.yml
> Activate content-exists specs for LibSass

- spec/sass_3_5/functions/hsl/options.yml
- spec/sass_3_5/functions/hsla/options.yml
- spec/sass_3_5/functions/rgb/options.yml
- spec/sass_3_5/functions/rgba/options.yml
> Activate specs for passing var() to CSS functions for LibSass

- spec/errors/invalid-operation/lte/error-dart-sass
- spec/errors/invalid-operation/lte/options.yml
- spec/libsass-todo-tests/scss-tests/128_test_supports_with_expressions/options.yml
> Dart Sass fixes.

- spec/libsass-todo-issues/issue_2376/expected_output.css
- spec/libsass-todo-issues/issue_2376/input.scss
https://github.com/sass/libsass/issues/2376
> Add todo spec test for libsass issue 2376

- spec/libsass-todo-issues/issue_2374/error
- spec/libsass-todo-issues/issue_2374/expected_output.css
- spec/libsass-todo-issues/issue_2374/input.scss
- spec/libsass-todo-issues/issue_2374/options.yml
https://github.com/sass/libsass/issues/2374
> Add todo spec test for libsass issue 2374

- spec/libsass-todo-issues/issue_2382/expected_output.css
- spec/libsass-todo-issues/issue_2382/input.scss
https://github.com/sass/libsass/issues/2382
> Add todo spec test for libsass issue 2382

- spec/libsass-todo-issues/issue_2359/input.scss
- spec/libsass-todo-issues/issue_2359/options.yml
https://github.com/sass/libsass/issues/2359
> Add todo spec test for libsass issue 2359

- spec/libsass-todo-issues/issue_2358/expected_output.css
- spec/libsass-todo-issues/issue_2358/input.scss
https://github.com/sass/libsass/issues/2358
> Add todo spec test for libsass issue 2358

- spec/libsass-todo-issues/issue_2394/expected_output.css
- spec/libsass-todo-issues/issue_2394/input.scss
https://github.com/sass/libsass/issues/2394
> Add todo spec test for libsass issue 2394

- spec/libsass-todo-issues/issue_2399/expected_output.css
- spec/libsass-todo-issues/issue_2399/input.scss
https://github.com/sass/libsass/issues/2399
> Add todo spec test for libsass issue 2399

- spec/errors/fn-varargs/at-start/error-dart-sass
- spec/errors/fn-varargs/at-start/options.yml
- spec/errors/invalid-operation/gt/error-dart-sass
- spec/errors/invalid-operation/gt/options.yml
- spec/errors/invalid-operation/mod/error-dart-sass
- spec/errors/invalid-operation/mod/options.yml
- spec/errors/invalid-operation/times/error-dart-sass
- spec/errors/invalid-operation/times/options.yml
- spec/libsass-closed-issues/issue_1432/is-superselector/error-dart-sass
- spec/libsass-closed-issues/issue_1432/is-superselector/options.yml
- spec/libsass-closed-issues/issue_1527/selector/first/error-dart-sass
- spec/libsass-closed-issues/issue_1527/selector/first/options.yml
- spec/libsass-closed-issues/issue_1601/error-dart-sass
- spec/libsass-closed-issues/issue_1601/options.yml
- spec/libsass-closed-issues/issue_2309/expected_output-dart-sass.css
- spec/libsass-closed-issues/issue_2309/options.yml
- spec/libsass-closed-issues/issue_2352/error-dart-sass
- spec/libsass-closed-issues/issue_2352/options.yml
- spec/libsass-todo-issues/issue_2295/error/wrapped/error-dart-sass
- spec/libsass-todo-issues/issue_2295/error/wrapped/options.yml
- spec/libsass/properties-in-media/error-dart-sass
- spec/sass_3_5/functions/get-function/errors/illegal-kwarg/error-dart-sass
- spec/sass_3_5/functions/get-function/errors/illegal-kwarg/options.yml
- spec/scss/color_output/expected_output.css
- spec/scss/color_output/input.scss
- spec/scss/color_output/options.yml
> Dart Sass fixes

- spec/sass_3_5/functions/get-function/errors/illegal-kwarg/error-libsass
> Update get-function error output for LibSass

- spec/sass_3_5/functions/get-function/basic/options.yml
- spec/sass_3_5/functions/get-function/builtins/options.yml
- spec/sass_3_5/functions/get-function/css-fn-reference/options.yml
- spec/sass_3_5/functions/get-function/equality/options.yml
- spec/sass_3_5/functions/get-function/errors/function-exists/options.yml
- spec/sass_3_5/functions/get-function/errors/illegal-argument/options.yml
- spec/sass_3_5/functions/get-function/errors/illegal-kwarg/options.yml
- spec/sass_3_5/functions/get-function/errors/math/division/options.yml
- spec/sass_3_5/functions/get-function/errors/non-existent/options.yml
- spec/sass_3_5/functions/get-function/errors/passed-fn-ref/options.yml
- spec/sass_3_5/functions/get-function/local-scope/options.yml
- spec/sass_3_5/functions/get-function/overrides/options.yml
https://github.com/sass/libsass/pull/2373
[skip libsass]
> Activate get-function specs for LibSass

- spec/selectors/options.yml
- spec/selectors/placeholder_in_pseudo/expected_output.css
- spec/selectors/placeholder_in_pseudo/input.scss
- spec/selectors/placeholder_in_pseudo/options.yml
See sass/sass#2228
Skip ruby-sass
> Add a test for placeholders in pseudo-selectors.

- spec/extend-tests/029_test_universal_unification_with_namespaceless_universal_target/options.yml
- spec/extend-tests/031_test_universal_unification_with_namespaced_universal_target/options.yml
- spec/extend-tests/038_test_universal_unification_with_namespaceless_element_target/options.yml
- spec/extend-tests/040_test_universal_unification_with_namespaced_element_target/options.yml
- spec/extend-tests/051_test_element_unification_with_namespaceless_universal_target/options.yml
- spec/extend-tests/053_test_element_unification_with_namespaced_universal_target/options.yml
- spec/extend-tests/060_test_element_unification_with_namespaceless_element_target/options.yml
- spec/extend-tests/062_test_element_unification_with_namespaced_element_target/options.yml
- spec/extend-tests/096_test_long_extender_runs_unification/options.yml
- spec/extend-tests/236_extend_with_universal_selector_empty_namespace/options.yml
- spec/extend-tests/237_extend_with_universal_selector_different_namespace/options.yml
- spec/libsass-closed-issues/issue_2056/options.yml
> Mark sass/sass#2250 as passing for Ruby Sass.

- spec/selector-functions/unify/universal_simple/options.yml
> Mark sass/sass#2247 as passing for Ruby Sass.

- spec/libsass-todo-issues/issue_2429/expected_output.css
- spec/libsass-todo-issues/issue_2429/input.scss
https://github.com/sass/libsass/issues/2429
> Add todo spec test for libsass issue 2429

- spec/sass_3_5/change-equality-of-lists/options.yml
See sass/sass#2121
Skip ruby-sass
> Enable bracketed list equality specs for Ruby Sass

- spec/css/selector/slotted/expected_output.css
- spec/css/selector/slotted/input.scss
- spec/css/selector/slotted/options.yml
See sass/sass#2325
Skip dart-sass
Skip ruby-sass
> Add a spec for extending into ::slotted().

- spec/libsass/color-functions/opacity/fade-out/expected_output.css
- spec/libsass/color-functions/opacity/fade-out/options.yml
- spec/libsass/color-functions/opacity/transparentize/expected_output.css
- spec/libsass/color-functions/opacity/transparentize/options.yml
- spec/libsass/color-functions/other/change-color/a/expected_output.css
- spec/libsass/color-functions/other/change-color/a/options.yml
- spec/libsass/color-functions/rgb/rgba/a/expected_output.css
- spec/libsass/color-functions/rgb/rgba/a/options.yml
- spec/libsass/color-names/expected_output.css
- spec/libsass/color-names/options.yml
See sass/sass#1782
Skip dart-sass
Skip ruby-sass
> Expect transparent generated colors to be emitted in rgba format

- test_all_impls.sh
https://github.com/koalaman/shellcheck/wiki/SC2006
> chore: use newer Bash command substitution syntax

- spec/libsass-todo-issues/issue_2467/expected_output.css
- spec/libsass-todo-issues/issue_2467/input.scss
- spec/libsass-todo-issues/issue_2467/options.yml
This PR add specs for sass/libsass#2467
> Add specs for issue 2467

- spec/libsass-closed-issues/issue_2106/test/error-dart-sass
- spec/libsass-todo-issues/issue_2295/error/basic/error-dart-sass
- spec/libsass-todo-issues/issue_2295/error/wrapped/error-dart-sass
> Update a Dart Sass error message

- spec/libsass-todo-issues/issue_2488/input.scss
https://github.com/sass/libsass/issues/2488
> Add todo spec test for libsass issue 2488

- spec/libsass-todo-issues/issue_2480/expected_output.css
- spec/libsass-todo-issues/issue_2480/input.scss
https://github.com/sass/libsass/issues/2480
> Add todo spec test for libsass issue 2480

- spec/libsass-todo-issues/issue_2468/expected_output-dart-sass.css
- spec/libsass-todo-issues/issue_2468/expected_output.css
- spec/libsass-todo-issues/issue_2468/input.scss
https://github.com/sass/libsass/issues/2468
> Add todo spec test for libsass issue 2468

- spec/libsass-todo-issues/issue_2464/expected_output.css
- spec/libsass-todo-issues/issue_2464/input.scss
https://github.com/sass/libsass/issues/2464
> Add todo spec test for libsass issue 2464

- spec/libsass-todo-issues/issue_2053/expected_output.css
- spec/libsass-todo-issues/issue_2053/input.scss
- spec/libsass-todo-issues/issue_2053/options.yml
https://github.com/sass/libsass/issues/2053
> Add todo spec test for libsass issue 2053

- spec/libsass-todo-issues/issue_2472/error
- spec/libsass-todo-issues/issue_2472/error-dart-sass
- spec/libsass-todo-issues/issue_2472/expected_output.css
- spec/libsass-todo-issues/issue_2472/input.scss
- spec/libsass-todo-issues/issue_2472/options.yml
https://github.com/sass/libsass/issues/2472
> Add todo spec test for libsass issue 2472

- spec/libsass-todo-issues/issue_2232/expected_output.css
- spec/libsass-todo-issues/issue_2232/input.scss
- spec/libsass-todo-issues/issue_2232/options.yml
https://github.com/sass/libsass/issues/2232
> Add todo spec test for libsass issue 2232

- spec/number-functions/round/expected_output.css
- spec/number-functions/round/input.scss
See sass/sass#2409
Skip ruby-sass
Skip dart-sass
> Add more thorough round() specs

- spec/parser/and_and/error
- spec/parser/and_and/error-ruby-sass
- spec/parser/and_and/expected_output.css
- spec/parser/and_and/input.scss
- spec/parser/and_and/options.yml
See sass/sass#2429
Skip dart-sass
Skip ruby-sass
> Add specs for a warning for "&&"

- spec/libsass-todo-issues/issue_2520/expected_output.css
- spec/libsass-todo-issues/issue_2520/input.scss
- spec/libsass-todo-issues/issue_2520/options.yml
https://github.com/sass/libsass/issues/2520
> Add todo spec test for libsass issue 2520

- spec/libsass-todo-issues/issue_2509/expected_output.css
- spec/libsass-todo-issues/issue_2509/input.scss
- spec/libsass-todo-issues/issue_2509/options.yml
https://github.com/sass/libsass/issues/2509
> Add todo spec test for libsass issue 2509

- spec/core_functions/feature_exists/options.yml
- spec/css/custom_properties/error/bang_in_ident/options.yml
- spec/css/custom_properties/error/top_level_bang/error-libsass
- spec/css/custom_properties/error/top_level_bang/options.yml
- spec/css/custom_properties/error/unmatched_brackets/curly/options.yml
- spec/css/custom_properties/error/unmatched_brackets/curly_in_square/options.yml
- spec/css/custom_properties/error/unmatched_brackets/paren/error-libsass
- spec/css/custom_properties/error/unmatched_brackets/paren/options.yml
- spec/css/custom_properties/error/unmatched_brackets/paren_in_curly/options.yml
- spec/css/custom_properties/error/unmatched_brackets/square/error-libsass
- spec/css/custom_properties/error/unmatched_brackets/square/options.yml
- spec/css/custom_properties/error/unmatched_brackets/square_in_paren/options.yml
- spec/css/custom_properties/name_interpolation/options.yml
- spec/css/custom_properties/nesting_characters/options.yml
- spec/css/custom_properties/script/options.yml
- spec/css/custom_properties/simple/options.yml
https://github.com/sass/libsass/pull/2534
skip libsass
> Enable custom property specs for libsass

- spec/parser/and_and/error
Spec is failing in perl-libsass otherwise
> Adjust path reported in and_and error spec

- spec/css/custom_properties/without_semicolon/expected_output-libsass.css
- spec/css/custom_properties/without_semicolon/expected_output.css
- spec/css/custom_properties/without_semicolon/input.scss
> Test custom properties without trailing semicolons

- spec/libsass-todo-issues/issue_2560/expected_output.css
- spec/libsass-todo-issues/issue_2560/input.scss
https://github.com/sass/libsass/issues/2560
> Add todo spec test for libsass issue 2560

- spec/core_functions/rgba/success/expected_output.css
- spec/core_functions/rgba/success/input.scss
> Enable additional specs for var support in color functions

- spec/sass/comment/loud/expected_output-ruby-sass.css
- spec/sass/comment/loud/expected_output.css
- spec/sass/comment/loud/input.sass
- spec/sass/comment/loud/options.yml
See sass/dart-sass#238
Skip dart-sass
> Add a spec for loud comments in the indented syntax

- spec/sass/selectors/expected_output.css
- spec/sass/selectors/input.sass
See sass/dart-sass#235
Skip dart-sass
> Add a spec for multiline selectors in the indented syntax

- spec/libsass-closed-issues/issue_2452/expected_output.css
- spec/libsass-closed-issues/issue_2452/input.scss
This PR add specs for sass/libsass#2452
[skip libsass]
> Add specs for issue 2452

- spec/libsass-todo-issues/issue_2582/expected_output.css
- spec/libsass-todo-issues/issue_2582/input.scss
https://github.com/sass/libsass/issues/2582
> Add todo spec test for libsass issue 2582

- spec/libsass-todo-issues/issue_2360/expected_output.css
- spec/libsass-todo-issues/issue_2360/input.sass
https://github.com/sass/libsass/issues/2360
> Add todo spec test for libsass issue 2360

- spec/libsass-todo-issues/issue_2604/expected_output.css
- spec/libsass-todo-issues/issue_2604/input.scss
https://github.com/sass/libsass/issues/2604
> Add todo spec test for libsass issue 2604

- spec/libsass-todo-issues/issue_2179/expected_output.css
- spec/libsass-todo-issues/issue_2179/input.scss
- spec/libsass-todo-issues/issue_2179/options.yml
https://github.com/sass/libsass/issues/2179
> Add todo spec test for libsass issue 2179

- spec/css/custom_properties/name_interpolation/expected_output.css
- spec/css/custom_properties/name_interpolation/input.scss
> Add a spec for custom vars with an #{interp} value

- spec/css/custom_properties/exclamation/options.yml
See https://github.com/sass/sass/pull/2492
See https://github.com/sass/libsass/pull/2610
[skip libsass]
> Allow ! in custom property values for LibSass

- spec/directives/import/index/options.yml
> Enable LibSass index imports

- spec/scss/media/nesting/options.yml
> Enable mediq query nesting specs for libsass

- spec/libsass-closed-issues/issue_2625/expected_output.css
- spec/libsass-closed-issues/issue_2625/input.scss
This PR activates specs for sass/libsass#2625
[skip libsass]
> Activate specs for issue 2625

- spec/libsass-closed-issues/issue_2352/error-dart-sass
> Update a span in a Dart Sass error

- spec/libsass-closed-issues/issue_945/error-dart-sass
> Improve Dart Sass error output

- spec/css/moz_document/README.md
- spec/css/moz_document/empty_prefix/expected_output-libsass.css
- spec/css/moz_document/empty_prefix/expected_output-ruby-sass.css
- spec/css/moz_document/empty_prefix/expected_output.css
- spec/css/moz_document/empty_prefix/input.scss
- spec/css/moz_document/functions/interpolated/error
- spec/css/moz_document/functions/interpolated/expected_output.css
- spec/css/moz_document/functions/interpolated/input.scss
- spec/css/moz_document/functions/interpolated/options.yml
- spec/css/moz_document/functions/static/error
- spec/css/moz_document/functions/static/expected_output.css
- spec/css/moz_document/functions/static/input.scss
- spec/css/moz_document/multi_function/error
- spec/css/moz_document/multi_function/expected_output.css
- spec/css/moz_document/multi_function/input.scss
- spec/css/moz_document/options.yml
- spec/libsass-closed-issues/issue_54/expected_output.css
- spec/libsass-closed-issues/issue_54/input.scss
- spec/libsass/keyframes/expected_output-dart-sass.css
- spec/libsass/keyframes/expected_output.css
- spec/libsass/keyframes/input.scss
- spec/libsass/moz-document/basic/expected_output.css
- spec/libsass/moz-document/basic/input.scss
- spec/libsass/moz-document/interpolated/expected_output.css
- spec/libsass/moz-document/interpolated/input.scss
- spec/scss-tests/127_test_moz_document_interpolation/expected_output.css
- spec/scss-tests/127_test_moz_document_interpolation/input.scss
> Consolidate specs for @-moz-document and add deprecation warnings

- spec/extend-tests/094_test_long_extendee_runs_unification/error-dart-sass
- spec/extend-tests/selector_list/expected_output-dart-sass.css
- spec/extend-tests/selector_list/expected_output.css
- spec/extend-tests/selector_list/input.scss
> Add a spec for extending a selector list

- spec/scss/media/nesting/merged_and_retained/expected_output.css
- spec/scss/media/nesting/merged_and_retained/input.scss
> Add a spec for merging and retaining the same media query

- spec/css/plain/single_equals/expected_output.css
- spec/css/plain/single_equals/input.scss
- spec/css/plain/single_equals/plain.css
> Add a spec for an IE-style single equals operator in plain CSS

- spec/values/identifiers/escape/normalize/expected_output.css
- spec/values/identifiers/escape/normalize/input.scss
See sass/sass#1542
See sass/dart-sass#485
> Properly escape digits at the beginning of identifiers

- spec/css/min_max/error/dangling_operator/error-ruby-sass
- spec/css/min_max/error/plain_css_function/error-ruby-sass
- spec/css/min_max/options.yml
- spec/css/min_max/plain_css/expected_output-ruby-sass.css
See sass/ruby-sass#77
[skip ruby-sass]
> Enable plain CSS min/max specs for Ruby Sass

- spec/css/media/range/error/invalid_binary_operator/before_colon/error-ruby-sass
- spec/css/media/range/error/invalid_binary_operator/eq/error-ruby-sass
- spec/css/media/range/error/invalid_binary_operator/gt/error-ruby-sass
- spec/css/media/range/error/invalid_binary_operator/gte/error-ruby-sass
- spec/css/media/range/error/invalid_binary_operator/in_subexpression/error-ruby-sass
- spec/css/media/range/error/invalid_binary_operator/lt/error-ruby-sass
- spec/css/media/range/error/invalid_binary_operator/lte/error-ruby-sass
- spec/css/media/range/error/invalid_comparison/gte/error-ruby-sass
- spec/css/media/range/error/invalid_comparison/lte/error-ruby-sass
- spec/css/media/range/error/invalid_comparison/range_gte/error-ruby-sass
- spec/css/media/range/error/mismatched_range/gt_lt/error-ruby-sass
- spec/css/media/range/error/mismatched_range/gte_lte/error-ruby-sass
- spec/css/media/range/error/mismatched_range/lt_gt/error-ruby-sass
- spec/css/media/range/error/mismatched_range/lte_gte/error-ruby-sass
- spec/css/media/range/options.yml
- spec/css/media/range/static/expected_output-ruby-sass.css
> Enable range-syntax media query tests for Ruby Sass

- spec/libsass-closed-issues/issue_1793/error-dart-sass
- spec/libsass-closed-issues/issue_1804/inline/error-dart-sass
- spec/libsass-closed-issues/issue_1804/variable/error-dart-sass
> Update some Dart Sass error messages

- spec/values/identifiers/escape/normalize/expected_output.css
- spec/values/identifiers/escape/normalize/input.scss
See sass/ruby-sass#94
[skip ruby-sass]
> Add a spec for an escaped raw tab

- .travis.yml
- lib/sass_spec.rb
- spec/values/identifiers/escape/normalize/expected_output.css
- spec/values/identifiers/escape/normalize/input.scss
> Add more specs for escaped tabs

- spec/css/selector/attribute/dash-dash/input.scss
- spec/css/selector/attribute/dash-dash/output.css
> Add specs for attribute selectors that begin with "--"

- spec/libsass-closed-issues/issue-2681/input.scss
- spec/libsass-closed-issues/issue-2681/output-dart-sass.css
- spec/libsass-closed-issues/issue-2681/output.css
> Add spec for LibSass issue 2681

- spec/libsass-closed-issues/issue-2640/input.scss
- spec/libsass-closed-issues/issue-2640/output.css
https://github.com/sass/libsass/issues/2640
> Specs for LibSass issue 2640

- lib/sass_spec/runner.rb
- lib/sass_spec/test.rb
- lib/sass_spec/test_case.rb
This reverts commit 1b279f606a61325dfbda8dff65a6146502d7462b.
Closes #1321
> Revert "Remove the --run-todo summary"

- spec/extend-tests/220_test_extend_in_double_nested_media_query/output-dart-sass.css
- spec/libsass-closed-issues/issue_1224/options.yml
- spec/libsass-closed-issues/issue_1224/output.css
- spec/libsass-closed-issues/issue_185/media_wrapper_selector/output-dart-sass.css
- spec/libsass-closed-issues/issue_185/mixin/output-dart-sass.css
- spec/libsass-closed-issues/issue_185/selector_wrapper_media/output-dart-sass.css
- spec/scss/media/nesting/merged/input.scss
- spec/scss/media/nesting/merged/output.css
- spec/scss/media/nesting/retained/input.scss
- spec/scss/media/nesting/retained/output.css
> Add specs for merging media queries that contain "all and"

- .travis.yml
- spec/directives/use/error/syntax.hrx
- spec/directives/use/options.yml
- spec/libsass-todo-issues/issue_2016/error-dart-sass
> Add @use syntax error tests

- spec/selectors/attribute.hrx
> Add a regression test for attribute selectors with a trailing dot

- spec/libsass-closed-issues/issue_1081.hrx
- spec/libsass-closed-issues/issue_1632.hrx
- spec/libsass-closed-issues/issue_759.hrx
- spec/libsass/variable-scoping/blead-global/expanding/at-root.hrx
- spec/libsass/variable-scoping/blead-global/expanding/each.hrx
- spec/libsass/variable-scoping/blead-global/expanding/else.hrx
- spec/libsass/variable-scoping/blead-global/expanding/elseif.hrx
- spec/libsass/variable-scoping/blead-global/expanding/for.hrx
- spec/libsass/variable-scoping/blead-global/expanding/function.hrx
- spec/libsass/variable-scoping/blead-global/expanding/if.hrx
- spec/libsass/variable-scoping/blead-global/expanding/mixin.hrx
- spec/libsass/variable-scoping/blead-global/expanding/ruleset.hrx
- spec/libsass/variable-scoping/blead-global/expanding/while.hrx
- spec/libsass/variable-scoping/blead-global/functional/each.hrx
- spec/libsass/variable-scoping/blead-global/functional/else.hrx
- spec/libsass/variable-scoping/blead-global/functional/elseif.hrx
- spec/libsass/variable-scoping/blead-global/functional/for.hrx
- spec/libsass/variable-scoping/blead-global/functional/if.hrx
- spec/libsass/variable-scoping/blead-global/functional/while.hrx
- spec/libsass/variable-scoping/defaults-global-null.hrx
- spec/libsass/variable-scoping/defaults-global.hrx
- spec/libsass/variable-scoping/defaults.hrx
- spec/variables.hrx
> Add specs for !global deprecation warnings

- spec/operations/division.hrx
> Add specs for stringifying slash-separated numbers in operations

- spec/libsass-closed-issues/issue_1801/import-cycle.hrx
- spec/libsass-todo-issues/issue_1801/simple-import-loop.hrx
> Update Dart Sass error specs for the @use loader

- spec/directives/use/error/extend.hrx
- spec/directives/use/extend.hrx
- spec/directives/use/load.hrx
> Add @extend tests for @use

- spec/core_functions/function_exists.hrx
- spec/core_functions/mixin_exists.hrx
> Remove todos for LibSass *-exists core functions

- spec/directives/use/extend.hrx
> Add a spec for @extend being isolated to a single @use

- spec/libsass-todo-issues/issue_2863.hrx
- tools/gen_libsass_todo.cmd
https://github.com/sass/libsass/issues/2863
>  Add todo spec test for libsass issue 2863 

- spec/core_functions/inspect.hrx
Refs https://github.com/sass/libsass/issues/2826
[skip libsass]
libsass PR: https://github.com/sass/libsass/pull/2874
> Enable core_functions/inspect/string/quoted for libsass

- spec/core_functions/inspect.hrx
Refs https://github.com/sass/libsass/issues/2654
> Add spec for `inspect` with nested list

- spec/css/url.hrx
> Add a spec for ! in url()s

- spec/directives/use/error/load.hrx
- spec/directives/use/error/member.hrx
> Fix weird and unhelpful @use stack traces

- spec/core_functions/function_exists.hrx
- spec/core_functions/get_function.hrx
- spec/core_functions/global_variable_exists.hrx
- spec/core_functions/mixin_exists.hrx
- spec/core_functions/variable_exists.hrx
- spec/directives/forward/css.hrx
- spec/directives/forward/error/extend.hrx
- spec/directives/forward/error/load.hrx
- spec/directives/forward/error/member.hrx
- spec/directives/forward/error/syntax.hrx
- spec/directives/forward/extend.hrx
- spec/directives/forward/member/as.hrx
- spec/directives/forward/member/bare.hrx
- spec/directives/forward/member/import.hrx
- spec/directives/forward/member/shadowed.hrx
- spec/directives/forward/member/visibility.hrx
- spec/directives/forward/options.yml
- spec/directives/use/error/load.hrx
> Add specs for @forward

- lib/sass_spec/directory.rb
- spec/core_functions/meta/module_functions.hrx
- spec/core_functions/meta/module_variables.hrx
> Add specs for module-variables() and module-functions()

- spec/directives/use/error/syntax.hrx
- spec/directives/use/error/with.hrx
- spec/directives/use/with.hrx
> Add support for "@use with"

- spec/core_functions/color/adjust_color/hsl.hrx
- spec/core_functions/color/alpha.hrx
- spec/core_functions/color/invert.hrx
- spec/core_functions/color/saturate.hrx
- spec/core_functions/list/append.hrx
- spec/core_functions/list/join/empty.hrx
- spec/core_functions/list/join/error.hrx
- spec/core_functions/list/separator.hrx
- spec/core_functions/list/zip.hrx
- spec/core_functions/map/remove.hrx
- spec/core_functions/string/insert.hrx
- spec/core_functions/string/slice.hrx
- spec/libsass-closed-issues/issue_151.hrx
> Remove Dart Sass TODOs for function specs

- spec/core_functions/color/mix.hrx
Depends on https://github.com/sass/libsass/pull/2934
[skip libsass]
> fix: Enable for libsass 2894

- spec/css/plain/error/statement.hrx
> Fix typo in silent comment error message

- spec/core_functions/math/comparable.hrx
> fix: Update comparable signature in LibSass

- spec/core_functions/color/adjust_color/error/bounds.hrx
- spec/core_functions/color/change_color/error/bounds.hrx
- spec/core_functions/color/darken.hrx
- spec/core_functions/color/desaturate.hrx
- spec/core_functions/color/fade_in.hrx
- spec/core_functions/color/fade_out.hrx
- spec/core_functions/color/invert.hrx
- spec/core_functions/color/lighten.hrx
- spec/core_functions/color/mix.hrx
- spec/core_functions/color/saturate.hrx
- spec/core_functions/color/scale_color/error/bounds.hrx
- spec/core_functions/list/join/error.hrx
- spec/errors/fn-saturate-out-of-range.hrx
- spec/libsass-closed-issues/issue_1452.hrx
- spec/libsass-closed-issues/issue_2779.hrx
> Clean up a few error messages

- .travis.yml
- Remove deprecated "sudo" option
- Use named matrix sets instead of conditions
> chore: Flatten Travis config

- spec/core_functions/color/invert.hrx
> update LibSass specs for throwing when weight is passed to CSS3 invert()

- spec/core_functions/string/slice.hrx
> fix: Enable libsass#2920

- spec/core_functions/meta/function_exists.hrx
- spec/core_functions/meta/get_function/same_module.hrx
- spec/core_functions/meta/global_variable_exists.hrx
- spec/core_functions/meta/variable_exists.hrx
> Add some dash-insensitivity specs for meta functions

- Gemfile
- Gemfile.lock
- README.md
- tests/fixtures/test_case_metadata/ignore_dart_sass/options.yml
- tests/spec_helper.rb
- tests/test_case_metadata_spec.rb
This is the first unit test!
I'll probably be biasing towards integration tests with Aruba, but this was a good way to get rspec setup.
I added RSpec + instructions to Gemfile/Readme accordingly.
> Test case metadata units

- spec/css/custom_properties/syntax.hrx
- spec/libsass-closed-issues/issue_2000.hrx
- spec/libsass-closed-issues/issue_2140.hrx
> Properly handle some CSS identifier edge cases

- spec/css/plain/extend.hrx
> Add a spec for extending a selector from a plain CSS file

- spec/libsass-todo-issues/issue_2980.hrx
https://github.com/sass/libsass/issues/2980
> Add todo spec test for libsass issue 2980

- spec/libsass-todo-issues/issue_2975.hrx
https://github.com/sass/libsass/issues/2975
> Add todo spec test for libsass issue 2975

- spec/libsass-todo-issues/issue_2808.hrx
https://github.com/sass/libsass/issues/2808
> Add todo spec test for libsass issue 2808

- spec/libsass-todo-issues/issue_2633.hrx
https://github.com/sass/libsass/issues/2633
> Add todo spec test for libsass issue 2633

- spec/libsass-todo-issues/issue_2884.hrx
https://github.com/sass/libsass/issues/2884
> Add todo spec test for libsass issue 2884

- spec/libsass-todo-issues/issue_2959.hrx
https://github.com/sass/libsass/issues/2959
> Add todo spec test for libsass issue 2959

- spec/libsass-todo-issues/issue_2818.hrx
https://github.com/sass/libsass/issues/2818
> Add todo spec test for libsass issue 2818

- spec/core_functions/meta/load_css/with.hrx
- spec/directives/use/with.hrx
> Add specs for using core module in configured module

- spec/css/plain/functions.hrx
> Add a spec for saturate() in a plain CSS file

- spec/core_functions/modules/color.hrx
> Improve error messages for color functions that aren't in sass:color

- spec/core_functions/meta/load_css/plain_css.hrx
> Add a regression test for sass/dart-sass#843

- spec/directives/use/with.hrx
> Add a regression test for sass/dart-sass#854

- spec/css/custom_properties/trailing_comment.hrx
> Add specs for custom properties with trailing comments

- spec/css/comment.hrx
> Add specs for inline comments

- spec/directives/forward/error/member.hrx
- spec/directives/forward/member/import.hrx
- spec/directives/import/error/member.hrx
> Expand @import specs

- spec/core_functions/math/clamp.hrx
- spec/core_functions/math/hypot.hrx
Adds specs for new built-in math functions.
> Specs for clamp() and hypot()

- spec/core_functions/math/variables.hrx
> Add specs for built-in variables $e and $pi.

- lib/sass_spec/engine_adapter.rb
> Run Dart Sass with asserts enabled

- spec/directives/forward/error/member.hrx
- spec/directives/forward/member/as.hrx
- spec/directives/forward/member/bare.hrx
- spec/directives/use/error/member.hrx
- spec/directives/use/member/global.hrx
> Add no-conflict specs for mixins and functions

- spec/core_functions/selector/nest.hrx
> Add specs for selector-nest()

- spec/core_functions/selector/replace.hrx
> Add specs for selector-replace()

- spec/css/selector.hrx
> Add regression test for sass/dart-sass#1038

- spec/css/selector.hrx
> Add specs for comments within a selector.

- spec/css/escape.hrx
- spec/css/important.hrx
- spec/directives/if/error/syntax.hrx
> Add specs for syntax error edge cases

- spec/core_functions/selector/nest.hrx
> Remove the TODO for sass/dart-sass#966

- spec/directives/use/error/load.hrx
> Add a regression test for dart-sass#1047

- spec/core_functions/map/deep_merge.hrx
> Add specs for map.deep-merge()

- spec/core_functions/map/get.hrx
> Add specs for nested maps in map-get

- spec/core_functions/map/has_key.hrx
> Add specs for nested maps in has-key

- spec/core_functions/map/set.hrx
See https://github.com/sass/sass/pull/2836
> Add specs for map.set()

- spec/arguments/inovcation.hrx
> Add specs for errors caused by positional arguments after named

- spec/core_functions/map/merge.hrx
- spec/core_functions/map/set.hrx
See https://github.com/sass/sass/pull/2836
> Adds specs for nested maps in map-merge.

- spec/core_functions/map/deep_remove.hrx
> Add specs for map.deep-remove()

- spec/core_functions/color/hwb/error/five_args.hrx
- spec/core_functions/color/hwb/error/four_args.hrx
- spec/core_functions/color/hwb/error/one_arg.hrx
- spec/core_functions/color/hwb/error/three_args.hrx
- spec/core_functions/color/hwb/error/two_args.hrx
- spec/core_functions/color/hwb/error/zero_args.hrx
- spec/core_functions/color/hwb/four_args.hrx
- spec/core_functions/color/hwb/one_arg.hrx
- spec/core_functions/color/hwb/options.yml
- spec/core_functions/color/hwb/three_args/named.hrx
- spec/core_functions/color/hwb/three_args/units.hrx
- spec/core_functions/color/hwb/three_args/w3c/README.md
- spec/core_functions/color/hwb/three_args/w3c/_test-hue.scss
- spec/core_functions/color/hwb/three_args/w3c/blue_magentas.hrx
- spec/core_functions/color/hwb/three_args/w3c/blues.hrx
- spec/core_functions/color/hwb/three_args/w3c/cyan_blues.hrx
- spec/core_functions/color/hwb/three_args/w3c/cyans.hrx
- spec/core_functions/color/hwb/three_args/w3c/green_cyans.hrx
- spec/core_functions/color/hwb/three_args/w3c/greens.hrx
- spec/core_functions/color/hwb/three_args/w3c/magenta_reds.hrx
- spec/core_functions/color/hwb/three_args/w3c/magentas.hrx
- spec/core_functions/color/hwb/three_args/w3c/oranges.hrx
- spec/core_functions/color/hwb/three_args/w3c/reds.hrx
- spec/core_functions/color/hwb/three_args/w3c/yellow_greens.hrx
- spec/core_functions/color/hwb/three_args/w3c/yellows.hrx
> Add specs for the color.hwb() function

- spec/css/custom_properties/name_interpolation.hrx
> Add a spec for sass/dart-sass#1095

- .travis.yml
- spec/core_functions/map/deep_merge.hrx
- spec/core_functions/map/deep_remove.hrx
- spec/core_functions/map/get.hrx
- spec/core_functions/map/has_key.hrx
- spec/core_functions/map/merge.hrx
- spec/core_functions/map/set.hrx
> Merge support for nested map functions

- spec/css/plain/custom_properties.hrx
- spec/css/plain/error/statement.hrx
> Add specs for custom property parsing in plain CSS

- spec/core_functions/color/blackness.hrx
- spec/core_functions/color/whiteness.hrx
See sass/sass#2834
See sass/sass-spec#1570
> Add specs for color.whiteness() and .blackness()

- spec/css/functions.hrx
> Add tests for sass/dart-sass#1050 and related syntax errors

- spec/values/maps/key_equality.hrx
> Add tests for Infinity and NaN as map keys

- spec/core_functions/meta/load_css/error.hrx
- spec/core_functions/meta/load_css/plain_css.hrx
> Fix the argument name for meta.load-css()

- spec/directives/extend/after_target.hrx
> Add a regression spec for sass/dart-sass#1109

- spec/libsass-closed-issues/issue_2779.hrx
> Give spec/libsass-closed-issues/issue_2779.hrx a canonical output

- spec/directives/at_root.hrx
> Add a spec for a case that's currently broken in Dart Sass

- spec/directives/use/error/syntax.hrx
- spec/expressions/syntax.hrx
Fixes #1602 by moving that test into this new directory.
> Create a new top-level directory for expressions

- spec/core_functions/color/adjust_color/units.hrx
- spec/core_functions/color/adjust_hue.hrx
- spec/core_functions/color/change_color/units.hrx
- spec/core_functions/color/hsl/one_arg/no_alpha.hrx
- spec/core_functions/color/hsl/three_args/units.hrx
- spec/core_functions/color/hsla/one_arg/no_alpha.hrx
- spec/core_functions/color/hsla/three_args/units.hrx
- spec/core_functions/modules/color.hrx
> Update color deprecation warnings to include values

- spec/directives/forward/with.hrx
See https://github.com/sass/dart-sass/issues/1222
> Let last !default value of @forward...with be commaless.

- spec/css/selector.hrx
This is taking over https://github.com/sass/sass-spec/pull/1600 to finish it
> Tests on escaping char in selectors: number, non alpha chars and non alpha chars in interpolation

- spec/core_functions/selector/parse/error.hrx
> Update a spec to match output improved during the NNBD migration

- spec/core_functions/color/hwb/error/four_args.hrx
- spec/core_functions/color/hwb/error/one_arg.hrx
> Fix the argument name in hwb spec

- spec/core_functions/meta/content_exists.hrx
> Add specs cover content-exists in control statements

- spec/core_functions/string/slice.hrx
> Add specs enforcing no units for str-slice

- spec/core_functions/selector/extend/simple/pseudo/selector/idempotent.hrx
skip libsass -> https://github.com/sass/libsass/pull/3136
> Enable libsass different prefix in extender

- spec/core_functions/meta/load_css/with.hrx
- spec/directives/forward/with.hrx
- spec/directives/use/with.hrx
> Add specs for null values in configurations

- spec/core_functions/list/length.hrx
This is a regression test for scssphp/scssphp#403
> Add a test covering the usage of lists ending with null

- spec/css/moz_document/functions/interpolated.hrx
- spec/css/moz_document/functions/static.hrx
- spec/css/moz_document/multi_function.hrx
> Update the URL for @-moz-document deprecation warnings

- package-lock.json
- spec/directives/for.hrx
> Add test for `@for` inside property declaration

- spec/directives/forward/member/import/import_to_forward/top_level.hrx
> Add test for post-facto implicit dep with use

- spec/operators/slash.hrx
> Add spec for namespaced variables in / operation

- spec/variables.hrx
> Add a spec for two @ifs in a local scope

- spec/css/unicode_range/error.hrx
> Add a spec for a new kind of invalid Unicode range

- spec/core_functions/selector/extend/list.hrx
> Add specs for extending a selector list in selector.extend()

- spec/values/identifiers/if.hrx
> Add a spec for using if as an unquoted string

- spec/directives/use/extend/optional_and_mandatory.hrx
- spec/directives/use/extend/upstream.hrx
> Add specs for a couple @extend bugs

- lib-js/spec-directory/options.ts
- test/spec-directory/options.test.ts
> Fix the dumping of options in the TS runner

- spec/css/plain/import/conditions.hrx
> Add specs covering the CSS4 import conditions

- spec/directives/at_root.hrx
> Specs for `@at-root` in a nested import

- spec/directives/use/with.hrx
> Add specs for `@forward with` in a file with another variable

- spec/values/calculation/calc/operator.hrx
See sass/sass#3142
See sass/sass#3146
> Allow the + operator for calculations and strings

- spec/values/calculation/calc/operator.hrx
See sass/sass#3147
See sass/sass#3148
> Fix a parenthesizing bug in calculations

- spec/css/functions/min_max/plain_css.hrx
- spec/css/functions/min_max/sass_function.hrx
- spec/values/calculation/calc/no_operator.hrx
> Add specs for extra whitespace in min, max, and calc

- spec/values/calculation/calc/no_operator.hrx
> Add regression specs for interpolation lookahead pitfalls

- js-api-spec/logger.test.ts
- js-api-spec/utils.ts
- package-lock.json
- package.json
> Add specs for the JS logger API

- spec/css/selector.hrx
In this PR I attempt to add a spec for sass/sass#3130
I have never worked with the sass spec before so please let me know if I did something wrong
I have not tested this change on my local machine
> Add spec for where pseudo-selector nesting

- js-api-spec/value/list.test.ts
- js-api-spec/value/map.test.ts
- package-lock.json
See https://github.com/sass/embedded-host-node/pull/68
> Add specs for SassList and SassMap.

- js-api-spec.ts
- js-api-spec/value/boolean.test.ts
- js-api-spec/value/color.test.ts
- js-api-spec/value/list.test.ts
- js-api-spec/value/map.test.ts
- js-api-spec/value/null.test.ts
- js-api-spec/value/number.test.ts
- js-api-spec/value/string.test.ts
- package-lock.json
- package.json
> Add specs for improvements to the new JS API

- js-api-spec/function.test.ts
> Add tests for the new JS API's custom function support

- js-api-spec/compile.test.ts
> Enable a couple basic async compile specs for the embedded host

- js-api-spec/compile.test.ts
> Enable some sync compile functions for the embedded host

- js-api-spec/compile.test.ts
> Enable all compile.test.ts specs for the embedded host

- js-api-spec/function.test.ts
> Enable most custom function specs for the embedded host

- js-api-spec/value/function.test.ts
> Add JS API specs for the SassFunction value type

- js-api-spec/function.test.ts
- js-api-spec/value/argument-list.test.ts
> Expand the specs for the JS API argument list type

- js-api-spec/importer.test.ts
> Enable JS API importer specs for the embedded host

- js-api-spec/logger.test.ts
- js-api-spec/utils.ts
> Enable JS API logger tests for the embedded host

- js-api-spec/legacy/value/null.test.ts
> Add specs for the legacy Null value

- js-api-spec/legacy/value/color.test.ts
> Enable color specs for the embedded host

- js-api-spec/legacy/value/list.test.ts
- js-api-spec/legacy/value/map.test.ts
- js-api-spec/legacy/value/number.test.ts
- js-api-spec/legacy/value/string.test.ts
> Enable specs for the rest of the legacy JS API value types

- js-api-spec/legacy/function.test.ts
- js-api-spec/utils.ts
> Enable function specs for the embedded host

- js-api-spec/legacy/importer.test.ts
> Enable legacy importer specs for the embedded host

- js-api-spec/compile.test.ts
- js-api-spec/legacy/source-map.test.ts
> Enable specs for the source map contents for sass-embedded

- spec/directives/import/css.hrx
> Add regression test for CSS import bug

- spec/css/supports/syntax.hrx
> Add specs for calcs within supports

- js-api-spec/legacy/importer.test.ts
> Add a regression test for sass/embedded-host-node#120

- spec/core_functions/selector/extend/no_op.hrx
- spec/core_functions/selector/extend/simple/pseudo/selector/idempotent.hrx
- spec/core_functions/selector/extend/simple/pseudo/selector/match.hrx
- spec/core_functions/selector/is_superselector/simple/pseudo/selector_arg/is.hrx
- spec/core_functions/selector/is_superselector/simple/pseudo/selector_arg/where.hrx
- spec/core_functions/selector/nest.hrx
- spec/core_functions/selector/parse/selector.hrx
- spec/core_functions/selector/replace.hrx
- spec/core_functions/selector/unify/simple/pseudo.hrx
- spec/css/selector.hrx
See https://github.com/sass/sass/pull/3283
> Add specs for :where()

- spec/core_functions/map/deep_merge.hrx
> Update the order of map.deep-merge()

- js-api-spec/value/number.test.ts
> Test return value of assertUnit/assertNoUnits

- spec/css/functions/var.hrx
It's unclear why this didn't show up in the original PR.
> Fix a broken test

- spec/core_functions/selector/extend/simple/universal.hrx
- spec/core_functions/selector/is_superselector/compound.hrx
- spec/core_functions/selector/is_superselector/simple/type.hrx
- spec/core_functions/selector/is_superselector/simple/universal.hrx
- spec/non_conformant/extend-tests/020_test_universal_unification_with_simple_target.hrx
- spec/non_conformant/extend-tests/021_test_universal_unification_with_simple_target.hrx
- spec/non_conformant/extend-tests/027_test_universal_unification_with_namespaceless_universal_target.hrx
See sass/dart-sass#790
See sass/dart-sass#2728
> Enable and update some Dart Sass superselector tests

- spec/core_functions/selector/is_superselector/complex/adjacent_sibling.hrx
- spec/core_functions/selector/is_superselector/complex/child.hrx
- spec/core_functions/selector/is_superselector/complex/sibling.hrx
- spec/libsass-closed-issues/issue_1091.hrx
See #791
See https://github.com/sass/dart-sass/pull/1778
> Add specs for improvements to combinator superselector logic

- spec/core_functions/math/random.hrx
Deprecation for: https://github.com/sass/sass-spec/issues/1810
> Tests for random-with-units deprecation

- spec/css/media/bubbling.hrx
> Add a regression test for a `@media` bubbling bug

- spec/css/media/logic/nested.hrx
- spec/libsass-closed-issues/issue_485.hrx
> Update specs for media query deprecation warnings

- js-api-spec/compile.test.ts
- js-api-spec/logger.test.ts
> Add tests for MultiSpan in the JS API

- spec/css/media/indentation.hrx
See: sass/dart-sass#1406
See: https://github.com/sass/dart-sass/pull/1814
> Test for selector indentation inside media queries

- spec/css/media/logic/nested.hrx
- spec/libsass-closed-issues/issue_485.hrx
Closes #1798
See https://github.com/sass/sass/issues/2538
> Update specs for full support for Media Queries 4

- spec/core_functions/meta/load_css/extend.hrx
> Add a regression test for sass/sass#3322

- js-api-spec/importer.test.ts
- js-api-spec/legacy/importer.test.ts
- js-api-spec/utils.ts
See: https://github.com/sass/embedded-host-node/pull/167
> Fix importer tests for dart-sass-embedded

- spec/values/numbers/error.hrx
> Add an error spec for "+."

- spec/core_functions/selector/is_superselector/complex/adjacent_sibling.hrx
- spec/core_functions/selector/is_superselector/complex/child.hrx
- spec/core_functions/selector/is_superselector/complex/descendant.hrx
- spec/core_functions/selector/is_superselector/complex/sibling.hrx
> Add specs for multiply-layered combinator superselectors

- spec/values/numbers/error.hrx
See https://github.com/sass/dart-sass/issues/1856
> Expand error tests for trailing dots in numbers

- spec/css/propset.hrx
Bug https://github.com/sass/dart-sass/issues/1857
PR https://github.com/sass/dart-sass/pull/1874
> Test nested properties (aka propsets)

- spec/non_conformant/scss/negation.hrx
> Update a spec to avoid recommended unary minus in calc

- spec/values/strings.hrx
Fixes https://github.com/sass/sass-spec/issues/1358
> Add specs for new-line string values

- spec/libsass-closed-issues/issue_1452.hrx
> Update specs for sass/dart-sass#1769

- .github/workflows/ci.yml
- spec/core_functions/color/hsl/three_args/units.hrx
- spec/core_functions/color/hsl/three_args/w3c/blue_to_red.hrx
- spec/core_functions/color/hsl/three_args/w3c/hue.hrx
- spec/core_functions/color/mix/error.hrx
- spec/core_functions/color/mix/explicit_method.hrx
- spec/core_functions/color/mix/hue_interpolation.hrx
> Update specs for sass/sass#3497

- js-api-spec/legacy/importer.test.ts
https://github.com/sass/embedded-host-node/pull/212
> Add test for resolving against the working directory in legacy API

- spec/libsass-closed-issues/issue_759.hrx
- spec/variables.hrx
> Add specs for deprecating multiple copies of the same variable flag

- spec/css/media/bubbling.hrx
> Don't separate out media queries after one has bubbled

- README.md
The tests asked to run `npm run sass-spec` when instead if should be `npm run js-api-spec`
> Update command to run js-api-spec tests

- spec/css/custom_properties/name_interpolation.hrx
See: https://github.com/sass/dart-sass/pull/2036
> Add regression test for sass/dart-sass#2023

- js-api-spec/value/calculation.test.ts
https://github.com/sass/dart-sass/pull/2043
https://github.com/sass/embedded-host-node/pull/241
> Fix SassCalculation.clamp test

- js-api-spec/importer.test.ts
> Add tests that cover a Dart Sass importer bug

- spec/core_functions/color/hsl/error/four_args.hrx
- spec/core_functions/color/hwb/error/four_args.hrx
- spec/core_functions/color/rgb/error/four_args.hrx
- spec/core_functions/color/rgb/error/two_args.hrx
> Rephrase errors for numbers that must be unitless or %

- spec/core_functions/color/hsl/error/one_arg.hrx
- spec/core_functions/color/hwb/error/four_args.hrx
- spec/core_functions/color/hwb/error/one_arg.hrx
- spec/core_functions/color/hwb/error/three_args.hrx
- spec/core_functions/color/oklab/README.md
- spec/core_functions/color/oklab/_utils.scss
- spec/core_functions/color/oklab/alpha.hrx
- spec/core_functions/color/oklab/error.hrx
- spec/core_functions/color/oklab/no_alpha.hrx
- spec/core_functions/color/oklab/options.yml
- spec/core_functions/color/oklab/special_functions.hrx
- spec/core_functions/color/rgb/error/one_arg.hrx
> [Color 4] Add tests for `oklab()`

- spec/core_functions/color/lch/README.md
- spec/core_functions/color/lch/_utils.scss
- spec/core_functions/color/lch/alpha.hrx
- spec/core_functions/color/lch/error.hrx
- spec/core_functions/color/lch/no_alpha.hrx
- spec/core_functions/color/lch/options.yml
- spec/core_functions/color/lch/special_functions.hrx
> [Color 4] Add tests for lch()

- js-api-spec/importer.test.ts
Closes #1970
See sass/sass#3832
> Add a test for an importer without a base URL

- js-api-spec/importer.node.test.ts
- js-api-spec/legacy/importer.node.test.ts
https://github.com/sass/dart-sass/pull/2209
> Add regression test for sass/dart-sass#2208

- spec/core_functions/color/to_gamut/a98_rgb.hrx
- spec/core_functions/color/to_gamut/display_p3.hrx
- spec/core_functions/color/to_gamut/error.hrx
- spec/core_functions/color/to_gamut/hsl.hrx
- spec/core_functions/color/to_gamut/hwb.hrx
- spec/core_functions/color/to_gamut/lab.hrx
- spec/core_functions/color/to_gamut/lch.hrx
- spec/core_functions/color/to_gamut/named.hrx
- spec/core_functions/color/to_gamut/oklab.hrx
- spec/core_functions/color/to_gamut/oklch.hrx
- spec/core_functions/color/to_gamut/positional.hrx
- spec/core_functions/color/to_gamut/prophoto_rgb.hrx
- spec/core_functions/color/to_gamut/rec2020.hrx
- spec/core_functions/color/to_gamut/rgb.hrx
- spec/core_functions/color/to_gamut/space.hrx
- spec/core_functions/color/to_gamut/srgb.hrx
- spec/core_functions/color/to_gamut/srgb_linear.hrx
- spec/core_functions/color/to_gamut/xyz.hrx
- spec/core_functions/color/to_gamut/xyz_d50.hrx
- spec/core_functions/color/to_space/hwb/oklab.hrx
- spec/core_functions/color/to_space/hwb/oklch.hrx
- spec/core_functions/color/to_space/xyz/oklab.hrx
- spec/core_functions/color/to_space/xyz/oklch.hrx
- spec/core_functions/color/to_space/xyz_d50/xyz-d50/oklab.hrx
- spec/core_functions/color/to_space/xyz_d50/xyz-d50/oklch.hrx
> Add tests for color.to-gamut()

- spec/core_functions/color/change/a98_rgb.hrx
- spec/core_functions/color/change/display_p3.hrx
- spec/core_functions/color/change/error/type.hrx
- spec/core_functions/color/change/hsl.hrx
- spec/core_functions/color/change/hwb.hrx
- spec/core_functions/color/change/lab.hrx
- spec/core_functions/color/change/lch.hrx
- spec/core_functions/color/change/no_space.hrx
- spec/core_functions/color/change/none_case.hrx
- spec/core_functions/color/change/oklab.hrx
- spec/core_functions/color/change/oklch.hrx
- spec/core_functions/color/change/prophoto_rgb.hrx
- spec/core_functions/color/change/rec2020.hrx
- spec/core_functions/color/change/rgb.hrx
- spec/core_functions/color/change/srgb.hrx
- spec/core_functions/color/change/srgb_linear.hrx
- spec/core_functions/color/change/xyz.hrx
- spec/core_functions/color/change/xyz_d50.hrx
> [Color 4] Add tests for none in `color.change()`

- spec/css/keyframes.hrx
See sass/sass#3859
See sass/sass#3861
> Allow at-rules in keyframe blocks

- spec/css/media/comment.hrx
- spec/css/moz_document/comment.hrx
- spec/css/propset.hrx
- spec/css/style_rule.hrx
- spec/css/supports/comment.hrx
- spec/css/unknown_directive/comment.hrx
- spec/directives/at_root.hrx
- spec/directives/extend/comment.hrx
- spec/directives/for.hrx
- spec/directives/forward/comment.hrx
- spec/directives/function.hrx
- spec/directives/if/comment.hrx
- spec/directives/import/comment.hrx
- spec/directives/mixin.hrx
- spec/directives/use/comment.hrx
- spec/directives/warn.hrx
- spec/variables.hrx
A few of these cases are currently broken on Dart Sass.
> Add tests for comments around statements

- spec/directives/at_root.hrx
> Add tests for an empty `@at-root` rule in the indented syntax

- spec/core_functions/global/meta.hrx
- spec/core_functions/meta/feature_exists.hrx
- spec/libsass-closed-issues/issue_702.hrx
- spec/libsass/at-error/feature-test.hrx
- spec/libsass/units/feature-test.hrx
- spec/libsass/variable-scoping/feature-test.hrx
https://github.com/sass/sass/issues/3702
> Update specs for the deprecation of feature-exists

- js-api-spec/deprecations.node.test.ts
- js-api-spec/deprecations.test.ts
- js-api-spec/legacy/render.node.test.ts
See https://github.com/sass/sass/pull/3932
> Test legacy-js-api deprecation warning

- spec/core_functions/color/blackness.hrx
- spec/core_functions/color/blue.hrx
- spec/core_functions/color/green.hrx
- spec/core_functions/color/hue.hrx
- spec/core_functions/color/lightness.hrx
- spec/core_functions/color/red.hrx
- spec/core_functions/color/saturation.hrx
- spec/core_functions/color/whiteness.hrx
- spec/core_functions/global/color/blue.hrx
- spec/core_functions/global/color/green.hrx
- spec/core_functions/global/color/hue.hrx
- spec/core_functions/global/color/lightness.hrx
- spec/core_functions/global/color/red.hrx
- spec/core_functions/global/color/saturation.hrx
- spec/core_functions/modules/color/blue.hrx
- spec/core_functions/modules/color/green.hrx
- spec/core_functions/modules/color/hue.hrx
- spec/core_functions/modules/color/lightness.hrx
- spec/core_functions/modules/color/red.hrx
- spec/core_functions/modules/color/saturation.hrx
- spec/libsass-closed-issues/issue_1132.hrx
- spec/libsass-closed-issues/issue_86.hrx
- spec/non_conformant/basic/22_colors_with_alpha.hrx
- spec/non_conformant/scss/alpha.hrx
- spec/values/colors/alpha_hex/initial_digit.hrx
- spec/values/colors/alpha_hex/initial_letter.hrx
See https://github.com/sass/dart-sass/issues/2353
> Add a `$space` parameter to the channel function deprecation

- spec/core_functions/color/blackness.hrx
- spec/core_functions/color/blue.hrx
- spec/core_functions/color/green.hrx
- spec/core_functions/color/hue.hrx
- spec/core_functions/color/lightness.hrx
- spec/core_functions/color/red.hrx
- spec/core_functions/color/saturation.hrx
- spec/core_functions/color/whiteness.hrx
- spec/core_functions/global/color/blue.hrx
- spec/core_functions/global/color/green.hrx
- spec/core_functions/global/color/hue.hrx
- spec/core_functions/global/color/lightness.hrx
- spec/core_functions/global/color/red.hrx
- spec/core_functions/global/color/saturation.hrx
- spec/core_functions/modules/color/blue.hrx
- spec/core_functions/modules/color/green.hrx
- spec/core_functions/modules/color/hue.hrx
- spec/core_functions/modules/color/lightness.hrx
- spec/core_functions/modules/color/red.hrx
- spec/core_functions/modules/color/saturation.hrx
- spec/libsass-closed-issues/issue_1132.hrx
- spec/libsass-closed-issues/issue_86.hrx
- spec/non_conformant/basic/22_colors_with_alpha.hrx
- spec/non_conformant/scss/alpha.hrx
- spec/values/colors/alpha_hex/initial_digit.hrx
- spec/values/colors/alpha_hex/initial_letter.hrx
> Quote the channel name in color channel deprecations

- js-api-spec/utils.ts
- js-api-spec/value/color/color-4-channels.test.ts
See https://github.com/sass/sass/pull/3951
Closes #2022
> Add tests for parsing missing channels from Sass

- spec/core_functions/math/unit.hrx
- spec/libsass/units/simple.hrx
See: https://github.com/sass/dart-sass/pull/2375
> Test denominator units using the correct syntax

- spec/css/comment.hrx
See https://github.com/sass/dart-sass/issues/2381
> Add a regression test for sass/dart-sass#2381

- spec/values/calculation/calc-size.hrx
> Add tests for `calc-size()`

- spec/values/calculation/round/one_argument.hrx
> Add a regression test for sass/dart-sass#2523

- spec/libsass-closed-issues/issue_1060.hrx
- spec/libsass-closed-issues/issue_1648.hrx
See https://github.com/sass/sass/pull/4057
> Update specs to treat "@elseif" as an unknown at-rule

- js-api-spec/node-package-importer.node.test.ts
> Allow the Node.js pkg importer to return the same URL multiple times

- spec/directives/import/configuration.hrx
See https://github.com/sass/dart-sass/issues/2641
> Add test for implicit configuration coming from imported, forward module
